/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.awt.Color;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author Amar
 */
public class AdminGUI extends javax.swing.JFrame {

    Appointment [] appointments;
    Physician   [] physicians;
    Patient     [] patients;
    public AdminGUI() {
        setUndecorated(true);
        getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK));
        initComponents();
        populateAllAppointmentTable();
        populatePhysicianTable();
        populatePatientTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        mainPnl = new keeptoo.KGradientPanel();
        picturePanel = new javax.swing.JPanel();
        pictureLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        userMnagmentBtn = new keeptoo.KButton();
        logoutBtn = new keeptoo.KButton();
        exitBtn = new keeptoo.KButton();
        welcomeLbl = new javax.swing.JLabel();
        welcomenameLbl = new javax.swing.JLabel();
        appointmenMenagmentBtn = new keeptoo.KButton();
        jPanel3 = new javax.swing.JPanel();
        userMngPnl = new keeptoo.KGradientPanel();
        physicianIconLblUserMngPnl = new javax.swing.JLabel();
        patientIconLblUserMngPnl = new javax.swing.JLabel();
        choseCategoryLblUserMngPnl = new javax.swing.JLabel();
        physicianLblUserMngPnl = new javax.swing.JLabel();
        patientLblUserMngPnl = new javax.swing.JLabel();
        editPhyPnl = new keeptoo.KGradientPanel();
        physicianListlbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        adminPhysicianlisttable = new javax.swing.JTable();
        searchBtnEditPhyPnl = new keeptoo.KButton();
        deleteButtonEditPhyPnl = new keeptoo.KButton();
        createPhysicianBtnEditPhyPnl = new keeptoo.KButton();
        searchTxtFldEditPhyPnl = new javax.swing.JTextField();
        editPatientPnl = new keeptoo.KGradientPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        patientTable_editPatientPnl = new javax.swing.JTable();
        pateintListLblEditPatintPnl = new javax.swing.JLabel();
        searchbtnEditPatintPnl = new keeptoo.KButton();
        SearchTexFealdEditPatintPnl = new javax.swing.JTextField();
        deletepatientBtnEditPatintPnl = new keeptoo.KButton();
        createPatientBtnEditPatintPnl = new keeptoo.KButton();
        editAppointmentPnl = new keeptoo.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EditAppointmentjTable1 = new javax.swing.JTable();
        deleteappointmentBtnEditAppPnl = new keeptoo.KButton();
        jLabel1 = new javax.swing.JLabel();
        createPhysiciantPnl = new keeptoo.KGradientPanel();
        createphysiciantBtnCreatePhysiciantPnl = new keeptoo.KButton();
        phoneLblCreatePhysiciantPnl = new javax.swing.JLabel();
        specialisationLblCreatePhysiciantPnl = new javax.swing.JLabel();
        titleLblCreatePhysiciantPnl = new javax.swing.JLabel();
        housenumberLblCreatePhysiciantPnl = new javax.swing.JLabel();
        emailLblCreatePhysiciantPnl = new javax.swing.JLabel();
        StreetLblCreatePhysiciantPnl = new javax.swing.JLabel();
        familyNameLblCreatePhysiciantPnl = new javax.swing.JLabel();
        nameLblCreatePhysiciantPnl = new javax.swing.JLabel();
        postalCodeLblCreatePhysiciantPnl = new javax.swing.JLabel();
        cityLblCreatePhysiciantPnl = new javax.swing.JLabel();
        nameTxtFldCreatePhysiciantPnl = new javax.swing.JTextField();
        familynameTxtFldCreatePhysiciantPnl = new javax.swing.JTextField();
        streetTxtFldCreatePhysiciantPnl = new javax.swing.JTextField();
        houseNumberTxtFldCreatePhysiciantPnl = new javax.swing.JTextField();
        postalCodeTxtFldCreatePhysiciantPnl = new javax.swing.JTextField();
        cityTxtFldCreatePhysiciantPnl = new javax.swing.JTextField();
        titleTxtFldCreatePhysiciantPnl = new javax.swing.JTextField();
        eamilTxtFldCreatePhysiciantPnl = new javax.swing.JTextField();
        phoneTxtFldCreatePhysiciantPnl = new javax.swing.JTextField();
        passLblCreatePhysiciantPnl = new javax.swing.JLabel();
        passTxtFldCreatePhysiciantPnl = new javax.swing.JTextField();
        specializationComboBox1 = new javax.swing.JComboBox<>();
        createPatientPnl = new keeptoo.KGradientPanel();
        createpatientBtnCreatePatientPnl = new keeptoo.KButton();
        patientnameTxtFldCreatePatientPnl = new javax.swing.JTextField();
        nameLblCreatePatientPnl = new javax.swing.JLabel();
        patientFamilynameTxtFldCreatePatientPnl = new javax.swing.JTextField();
        patientFamilyNameTxFldCreatePatientPnl = new javax.swing.JLabel();
        patientStreetLblCreatePatientPnl = new javax.swing.JLabel();
        patientStreetTxtFldCreatePatientPnl = new javax.swing.JTextField();
        patientHousenumberLblCreatePatientPnl = new javax.swing.JLabel();
        patientHouseNumberTxtFldCreatePatientPnl = new javax.swing.JTextField();
        patientPostalCodeTxtFldCreatePatientPnl = new javax.swing.JTextField();
        patientPostalCodeLblCreatePatientPnl = new javax.swing.JLabel();
        patientCityLblCreatePatientPnl = new javax.swing.JLabel();
        patientTitleLblCreatePatientPnl = new javax.swing.JLabel();
        patientEmailLblCreatePatientPnl = new javax.swing.JLabel();
        patientphoneLblCreatePatientPnl = new javax.swing.JLabel();
        patientPhoneTxtFld1CreatePatientPnl = new javax.swing.JTextField();
        emailTxtFldCreatePatientPnl = new javax.swing.JTextField();
        patienTtitleTxtFldCreatePatientPnl = new javax.swing.JTextField();
        patientCityTxtFldCreatePatientPnl = new javax.swing.JTextField();
        insurance_CreatepatientPnl = new javax.swing.JLabel();
        weightLbl_CreatepatientPnl = new javax.swing.JLabel();
        weightTxtFld_CreatepatientPnl = new javax.swing.JTextField();
        dateOfBirthtLbl_CreatepatientPnl = new javax.swing.JLabel();
        dateOfBirthTxtFld_CreatepatientPnl = new javax.swing.JTextField();
        paswordLbl_CreatepatientPnl = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        insuranceComboBox_createPatientPnl = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPnl.setkEndColor(new java.awt.Color(255, 255, 255));
        mainPnl.setkStartColor(new java.awt.Color(153, 204, 255));
        mainPnl.setLayout(new java.awt.BorderLayout());

        pictureLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/adminpic.jpg"))); // NOI18N
        pictureLbl.setText("jLabel8");

        javax.swing.GroupLayout picturePanelLayout = new javax.swing.GroupLayout(picturePanel);
        picturePanel.setLayout(picturePanelLayout);
        picturePanelLayout.setHorizontalGroup(
                picturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pictureLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 891, Short.MAX_VALUE)
        );
        picturePanelLayout.setVerticalGroup(
                picturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(picturePanelLayout.createSequentialGroup()
                                .addComponent(pictureLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        mainPnl.add(picturePanel, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        userMnagmentBtn.setBorder(null);
        userMnagmentBtn.setText("User Management");
        userMnagmentBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        userMnagmentBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        userMnagmentBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        userMnagmentBtn.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        userMnagmentBtn.setkPressedColor(new java.awt.Color(0, 0, 0));
        userMnagmentBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        userMnagmentBtn.setkStartColor(new java.awt.Color(102, 102, 102));
        userMnagmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userMnagmentBtnActionPerformed(evt);
            }
        });

        logoutBtn.setBorder(null);
        logoutBtn.setText("Logout");
        logoutBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        logoutBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        logoutBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        logoutBtn.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        logoutBtn.setkPressedColor(new java.awt.Color(0, 0, 0));
        logoutBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        logoutBtn.setkStartColor(new java.awt.Color(102, 102, 102));

        exitBtn.setBorder(null);
        exitBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        exitBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        exitBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        exitBtn.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        exitBtn.setkPressedColor(new java.awt.Color(0, 0, 0));
        exitBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        exitBtn.setkStartColor(new java.awt.Color(102, 102, 102));
        exitBtn.setLabel("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        welcomeLbl.setFont(new java.awt.Font("Baskerville Old Face", 2, 20)); // NOI18N
        welcomeLbl.setText("Welcome");

        welcomenameLbl.setFont(new java.awt.Font("Baskerville Old Face", 2, 20)); // NOI18N
        welcomenameLbl.setText("Planincic");

        appointmenMenagmentBtn.setBorder(null);
        appointmenMenagmentBtn.setText("Appointment Management");
        appointmenMenagmentBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        appointmenMenagmentBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        appointmenMenagmentBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        appointmenMenagmentBtn.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        appointmenMenagmentBtn.setkPressedColor(new java.awt.Color(0, 0, 0));
        appointmenMenagmentBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        appointmenMenagmentBtn.setkStartColor(new java.awt.Color(102, 102, 102));
        appointmenMenagmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointmenMenagmentBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(logoutBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                        .addComponent(exitBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(welcomeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(welcomenameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                        .addComponent(appointmenMenagmentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(userMnagmentBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(welcomeLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(welcomenameLbl)
                                .addGap(64, 64, 64)
                                .addComponent(userMnagmentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(appointmenMenagmentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(88, Short.MAX_VALUE))
        );

        mainPnl.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setLayout(new java.awt.CardLayout());

        userMngPnl.setkEndColor(new java.awt.Color(255, 255, 255));
        userMngPnl.setkStartColor(new java.awt.Color(153, 153, 153));

        physicianIconLblUserMngPnl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/doctor-3552.png"))); // NOI18N
        physicianIconLblUserMngPnl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        physicianIconLblUserMngPnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                physicianIconLblUserMngPnlMouseClicked(evt);
            }
        });

        patientIconLblUserMngPnl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/cough-3253 (1).png"))); // NOI18N
        patientIconLblUserMngPnl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        patientIconLblUserMngPnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patientIconLblUserMngPnlMouseClicked(evt);
            }
        });

        choseCategoryLblUserMngPnl.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        choseCategoryLblUserMngPnl.setText("Choose category");

        physicianLblUserMngPnl.setBackground(new java.awt.Color(255, 255, 255));
        physicianLblUserMngPnl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        physicianLblUserMngPnl.setText("Physician");

        patientLblUserMngPnl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        patientLblUserMngPnl.setText("Patient");

        javax.swing.GroupLayout userMngPnlLayout = new javax.swing.GroupLayout(userMngPnl);
        userMngPnl.setLayout(userMngPnlLayout);
        userMngPnlLayout.setHorizontalGroup(
                userMngPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userMngPnlLayout.createSequentialGroup()
                                .addContainerGap(61, Short.MAX_VALUE)
                                .addGroup(userMngPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(choseCategoryLblUserMngPnl)
                                        .addGroup(userMngPnlLayout.createSequentialGroup()
                                                .addGroup(userMngPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(physicianIconLblUserMngPnl)
                                                        .addGroup(userMngPnlLayout.createSequentialGroup()
                                                                .addGap(90, 90, 90)
                                                                .addComponent(physicianLblUserMngPnl)))
                                                .addGroup(userMngPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(userMngPnlLayout.createSequentialGroup()
                                                                .addGap(51, 51, 51)
                                                                .addComponent(patientIconLblUserMngPnl))
                                                        .addGroup(userMngPnlLayout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(patientLblUserMngPnl)
                                                                .addGap(99, 99, 99)))))
                                .addGap(31, 31, 31))
        );
        userMngPnlLayout.setVerticalGroup(
                userMngPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(userMngPnlLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(choseCategoryLblUserMngPnl)
                                .addGap(33, 33, 33)
                                .addGroup(userMngPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(physicianIconLblUserMngPnl)
                                        .addComponent(patientIconLblUserMngPnl))
                                .addGroup(userMngPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(userMngPnlLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                                .addComponent(patientLblUserMngPnl)
                                                .addGap(64, 64, 64))
                                        .addGroup(userMngPnlLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(physicianLblUserMngPnl)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel3.add(userMngPnl, "card4");

        editPhyPnl.setkEndColor(new java.awt.Color(255, 255, 255));
        editPhyPnl.setkStartColor(new java.awt.Color(153, 153, 153));

        physicianListlbl.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        physicianListlbl.setText("Physician list");

        adminPhysicianlisttable.setBackground(new java.awt.Color(204, 204, 204));
        adminPhysicianlisttable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "First name", "Last name", "Specialization", "E-Mail ", "Phone"
                }
        ));
        jScrollPane2.setViewportView(adminPhysicianlisttable);

        searchBtnEditPhyPnl.setBorder(null);
        searchBtnEditPhyPnl.setText("Search");
        searchBtnEditPhyPnl.setkEndColor(new java.awt.Color(255, 255, 255));
        searchBtnEditPhyPnl.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        searchBtnEditPhyPnl.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        searchBtnEditPhyPnl.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        searchBtnEditPhyPnl.setkPressedColor(new java.awt.Color(0, 0, 0));
        searchBtnEditPhyPnl.setkSelectedColor(new java.awt.Color(255, 255, 255));
        searchBtnEditPhyPnl.setkStartColor(new java.awt.Color(102, 102, 102));

        deleteButtonEditPhyPnl.setBorder(null);
        deleteButtonEditPhyPnl.setText("Delete Physician");
        deleteButtonEditPhyPnl.setkEndColor(new java.awt.Color(255, 255, 255));
        deleteButtonEditPhyPnl.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        deleteButtonEditPhyPnl.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        deleteButtonEditPhyPnl.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        deleteButtonEditPhyPnl.setkPressedColor(new java.awt.Color(0, 0, 0));
        deleteButtonEditPhyPnl.setkSelectedColor(new java.awt.Color(255, 255, 255));
        deleteButtonEditPhyPnl.setkStartColor(new java.awt.Color(102, 102, 102));

        createPhysicianBtnEditPhyPnl.setBorder(null);
        createPhysicianBtnEditPhyPnl.setText("Create Physician");
        createPhysicianBtnEditPhyPnl.setkEndColor(new java.awt.Color(255, 255, 255));
        createPhysicianBtnEditPhyPnl.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        createPhysicianBtnEditPhyPnl.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        createPhysicianBtnEditPhyPnl.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        createPhysicianBtnEditPhyPnl.setkPressedColor(new java.awt.Color(0, 0, 0));
        createPhysicianBtnEditPhyPnl.setkSelectedColor(new java.awt.Color(255, 255, 255));
        createPhysicianBtnEditPhyPnl.setkStartColor(new java.awt.Color(102, 102, 102));
        createPhysicianBtnEditPhyPnl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPhysicianBtnEditPhyPnlActionPerformed(evt);
            }
        });

        searchTxtFldEditPhyPnl.setForeground(new java.awt.Color(204, 204, 204));
        searchTxtFldEditPhyPnl.setText("Type here to search...");
        searchTxtFldEditPhyPnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchTxtFldEditPhyPnlMouseClicked(evt);
            }
        });
        searchTxtFldEditPhyPnl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTxtFldEditPhyPnlActionPerformed(evt);
            }
        });
        searchTxtFldEditPhyPnl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchTxtFldEditPhyPnlKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTxtFldEditPhyPnlKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout editPhyPnlLayout = new javax.swing.GroupLayout(editPhyPnl);
        editPhyPnl.setLayout(editPhyPnlLayout);
        editPhyPnlLayout.setHorizontalGroup(
                editPhyPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
                        .addGroup(editPhyPnlLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(editPhyPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(editPhyPnlLayout.createSequentialGroup()
                                                .addComponent(physicianListlbl)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPhyPnlLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(editPhyPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPhyPnlLayout.createSequentialGroup()
                                                                .addComponent(searchTxtFldEditPhyPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(searchBtnEditPhyPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPhyPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(createPhysicianBtnEditPhyPnl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                                                .addComponent(deleteButtonEditPhyPnl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                .addContainerGap())
        );
        editPhyPnlLayout.setVerticalGroup(
                editPhyPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPhyPnlLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(physicianListlbl)
                                .addGap(22, 22, 22)
                                .addGroup(editPhyPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(searchTxtFldEditPhyPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                                        .addComponent(searchBtnEditPhyPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(deleteButtonEditPhyPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(createPhysicianBtnEditPhyPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(78, Short.MAX_VALUE))
        );

        jPanel3.add(editPhyPnl, "card2");

        editPatientPnl.setkEndColor(new java.awt.Color(255, 255, 255));
        editPatientPnl.setkStartColor(new java.awt.Color(153, 153, 153));

        patientTable_editPatientPnl.setBackground(new java.awt.Color(204, 204, 204));
        patientTable_editPatientPnl.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "First name", "Last name", "Insurance", "E-Mail ", "Phone"
                }
        ));
        jScrollPane3.setViewportView(patientTable_editPatientPnl);

        pateintListLblEditPatintPnl.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        pateintListLblEditPatintPnl.setText("Patient list");

        searchbtnEditPatintPnl.setBorder(null);
        searchbtnEditPatintPnl.setText("Search");
        searchbtnEditPatintPnl.setkEndColor(new java.awt.Color(255, 255, 255));
        searchbtnEditPatintPnl.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        searchbtnEditPatintPnl.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        searchbtnEditPatintPnl.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        searchbtnEditPatintPnl.setkPressedColor(new java.awt.Color(0, 0, 0));
        searchbtnEditPatintPnl.setkSelectedColor(new java.awt.Color(255, 255, 255));
        searchbtnEditPatintPnl.setkStartColor(new java.awt.Color(102, 102, 102));

        SearchTexFealdEditPatintPnl.setForeground(new java.awt.Color(204, 204, 204));
        SearchTexFealdEditPatintPnl.setText("Type here to search...");
        SearchTexFealdEditPatintPnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchTexFealdEditPatintPnlMouseClicked(evt);
            }
        });
        SearchTexFealdEditPatintPnl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTexFealdEditPatintPnlActionPerformed(evt);
            }
        });
        SearchTexFealdEditPatintPnl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SearchTexFealdEditPatintPnlKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchTexFealdEditPatintPnlKeyReleased(evt);
            }
        });

        deletepatientBtnEditPatintPnl.setBorder(null);
        deletepatientBtnEditPatintPnl.setText("Delete Patient");
        deletepatientBtnEditPatintPnl.setkEndColor(new java.awt.Color(255, 255, 255));
        deletepatientBtnEditPatintPnl.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        deletepatientBtnEditPatintPnl.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        deletepatientBtnEditPatintPnl.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        deletepatientBtnEditPatintPnl.setkPressedColor(new java.awt.Color(0, 0, 0));
        deletepatientBtnEditPatintPnl.setkSelectedColor(new java.awt.Color(255, 255, 255));
        deletepatientBtnEditPatintPnl.setkStartColor(new java.awt.Color(102, 102, 102));
        deletepatientBtnEditPatintPnl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletepatientBtnEditPatintPnlActionPerformed(evt);
            }
        });

        createPatientBtnEditPatintPnl.setBorder(null);
        createPatientBtnEditPatintPnl.setText("Create Patient");
        createPatientBtnEditPatintPnl.setkEndColor(new java.awt.Color(255, 255, 255));
        createPatientBtnEditPatintPnl.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        createPatientBtnEditPatintPnl.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        createPatientBtnEditPatintPnl.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        createPatientBtnEditPatintPnl.setkPressedColor(new java.awt.Color(0, 0, 0));
        createPatientBtnEditPatintPnl.setkSelectedColor(new java.awt.Color(255, 255, 255));
        createPatientBtnEditPatintPnl.setkStartColor(new java.awt.Color(102, 102, 102));
        createPatientBtnEditPatintPnl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPatientBtnEditPatintPnlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editPatientPnlLayout = new javax.swing.GroupLayout(editPatientPnl);
        editPatientPnl.setLayout(editPatientPnlLayout);
        editPatientPnlLayout.setHorizontalGroup(
                editPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(editPatientPnlLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(editPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                                        .addGroup(editPatientPnlLayout.createSequentialGroup()
                                                .addComponent(pateintListLblEditPatintPnl)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPatientPnlLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(editPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPatientPnlLayout.createSequentialGroup()
                                                                .addComponent(SearchTexFealdEditPatintPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(29, 29, 29)
                                                                .addComponent(searchbtnEditPatintPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(createPatientBtnEditPatintPnl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(deletepatientBtnEditPatintPnl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap())
        );
        editPatientPnlLayout.setVerticalGroup(
                editPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(editPatientPnlLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pateintListLblEditPatintPnl)
                                .addGap(8, 8, 8)
                                .addGroup(editPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(SearchTexFealdEditPatintPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(searchbtnEditPatintPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(deletepatientBtnEditPatintPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(createPatientBtnEditPatintPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(71, Short.MAX_VALUE))
        );

        jPanel3.add(editPatientPnl, "card2");

        editAppointmentPnl.setkEndColor(new java.awt.Color(255, 255, 255));
        editAppointmentPnl.setkStartColor(new java.awt.Color(153, 153, 153));

        EditAppointmentjTable1.setBackground(new java.awt.Color(204, 204, 204));
        EditAppointmentjTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "Patient", "Physician", "Appointment date and time"
                }
        ));
        jScrollPane1.setViewportView(EditAppointmentjTable1);

        deleteappointmentBtnEditAppPnl.setBorder(null);
        deleteappointmentBtnEditAppPnl.setText("Delete Appointment");
        deleteappointmentBtnEditAppPnl.setkEndColor(new java.awt.Color(255, 255, 255));
        deleteappointmentBtnEditAppPnl.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        deleteappointmentBtnEditAppPnl.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        deleteappointmentBtnEditAppPnl.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        deleteappointmentBtnEditAppPnl.setkPressedColor(new java.awt.Color(0, 0, 0));
        deleteappointmentBtnEditAppPnl.setkSelectedColor(new java.awt.Color(255, 255, 255));
        deleteappointmentBtnEditAppPnl.setkStartColor(new java.awt.Color(102, 102, 102));
        deleteappointmentBtnEditAppPnl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteappointmentBtnEditAppPnlActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel1.setText("Appointment list");

        javax.swing.GroupLayout editAppointmentPnlLayout = new javax.swing.GroupLayout(editAppointmentPnl);
        editAppointmentPnl.setLayout(editAppointmentPnlLayout);
        editAppointmentPnlLayout.setHorizontalGroup(
                editAppointmentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editAppointmentPnlLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(deleteappointmentBtnEditAppPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(editAppointmentPnlLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        editAppointmentPnlLayout.setVerticalGroup(
                editAppointmentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(editAppointmentPnlLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(deleteappointmentBtnEditAppPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52))
        );

        jPanel3.add(editAppointmentPnl, "card2");

        createPhysiciantPnl.setkEndColor(new java.awt.Color(255, 255, 255));
        createPhysiciantPnl.setkStartColor(new java.awt.Color(153, 153, 153));

        createphysiciantBtnCreatePhysiciantPnl.setBorder(null);
        createphysiciantBtnCreatePhysiciantPnl.setText("Create Physician");
        createphysiciantBtnCreatePhysiciantPnl.setkEndColor(new java.awt.Color(255, 255, 255));
        createphysiciantBtnCreatePhysiciantPnl.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        createphysiciantBtnCreatePhysiciantPnl.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        createphysiciantBtnCreatePhysiciantPnl.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        createphysiciantBtnCreatePhysiciantPnl.setkPressedColor(new java.awt.Color(0, 0, 0));
        createphysiciantBtnCreatePhysiciantPnl.setkSelectedColor(new java.awt.Color(255, 255, 255));
        createphysiciantBtnCreatePhysiciantPnl.setkStartColor(new java.awt.Color(102, 102, 102));
        createphysiciantBtnCreatePhysiciantPnl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createphysiciantBtnCreatePhysiciantPnlActionPerformed(evt);
            }
        });

        phoneLblCreatePhysiciantPnl.setText("Phone");

        specialisationLblCreatePhysiciantPnl.setText("Specialisation");

        titleLblCreatePhysiciantPnl.setText("Title");

        housenumberLblCreatePhysiciantPnl.setText("House Number");

        emailLblCreatePhysiciantPnl.setText("E-Mail");

        StreetLblCreatePhysiciantPnl.setText("Street");

        familyNameLblCreatePhysiciantPnl.setText("Family name");

        nameLblCreatePhysiciantPnl.setText("Name");

        postalCodeLblCreatePhysiciantPnl.setText("Postal code");

        cityLblCreatePhysiciantPnl.setText("City");

        passLblCreatePhysiciantPnl.setText("Password");

        specializationComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Allgemeinmedizin", "Anästhesiologie", "Anatomie", "Arbeitsmedizin", "Augenheilkunde", "Biochemie", "Chirurgie", "Chirurgie_Allgemeine Chirurgie", "Forensische Psychiatrie", "Frauenheilkunde und Geburtshilfe", "Gefäßchirurgie", "Gynäkologische Onkologie", "Hals-Nasen-Ohrenheilkunde", "Haut- und Geschlechtskrankheiten", "Herzchirurgie", "Humangenetik", "Hygiene und Umweltmedizin", "Innere Medizin ", "Innere Medizin und Endokrinologie und Diabetologie", "Innere Medizin und Gastroenterologie", "Innere Medizin und Hämatologie und Onkologie", "Innere Medizin und Kardiologie", "Innere Medizin und Nephrologie", "Innere Medizin und Pneumologie", "Innere Medizin und Rheumatologie", "Kinder- und Jugendmedizin", "Kinder- und Jugendpsychiatrie und -psychotherapie", "Kinderchirurgie", "Kinderradiologie", "Klinische Pharmakologie", "Laboratoriumsmedizin", "Mikrobiologie, Virologie und Infektionsepidemiologie", "Mund-Kiefer-Gesichtschirurgie", "Neurochirurgie", "Neurologie", "Neuroradiologie", "Nuklearmedizin", "Orthopädie und Unfallchirurgie", "Pathologie ", "Pharmakologie und Toxikologie", "Phoniatrie und Pädaudiologie", "Physikalische und Rehabilitative Medizin", "Physiologie", "Plastische, Rekonstruktive und Ästhetische Chirurgie", "Psychiatrie und Psychotherapie", "Psychosomatische Medizin und Psychotherapie", "Radiologie", "Rechtsmedizin", "SP Gynäkologische Endokrinologie und Reproduktionsmedizin", "SP Kinder-Hämatologie und -Onkologie", "SP Kinder-Kardiologie", "SP Neonatologie", "SP Neuropädiatrie", "Spezielle Geburtshilfe und Perinatalmedizin", "Strahlentherapie", "Thoraxchirurgie", "Transfusionsmedizin", "Urologie", "Viszeralchirurgie", "Innere Medizin und Angiologie", "Öffentliches Gesundheitswesen", " ", " ", " " }));

        javax.swing.GroupLayout createPhysiciantPnlLayout = new javax.swing.GroupLayout(createPhysiciantPnl);
        createPhysiciantPnl.setLayout(createPhysiciantPnlLayout);
        createPhysiciantPnlLayout.setHorizontalGroup(
                createPhysiciantPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createPhysiciantPnlLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(createphysiciantBtnCreatePhysiciantPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                        .addGroup(createPhysiciantPnlLayout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addGroup(createPhysiciantPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nameLblCreatePhysiciantPnl)
                                        .addGroup(createPhysiciantPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(StreetLblCreatePhysiciantPnl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(familyNameLblCreatePhysiciantPnl, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addComponent(housenumberLblCreatePhysiciantPnl)
                                        .addComponent(postalCodeLblCreatePhysiciantPnl)
                                        .addComponent(cityLblCreatePhysiciantPnl)
                                        .addComponent(specialisationLblCreatePhysiciantPnl)
                                        .addComponent(titleLblCreatePhysiciantPnl)
                                        .addComponent(emailLblCreatePhysiciantPnl)
                                        .addComponent(phoneLblCreatePhysiciantPnl)
                                        .addComponent(passLblCreatePhysiciantPnl))
                                .addGap(142, 142, 142)
                                .addGroup(createPhysiciantPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(createPhysiciantPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(phoneTxtFldCreatePhysiciantPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                                .addComponent(nameTxtFldCreatePhysiciantPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                                .addComponent(familynameTxtFldCreatePhysiciantPnl)
                                                .addComponent(streetTxtFldCreatePhysiciantPnl)
                                                .addComponent(houseNumberTxtFldCreatePhysiciantPnl)
                                                .addComponent(postalCodeTxtFldCreatePhysiciantPnl)
                                                .addComponent(cityTxtFldCreatePhysiciantPnl)
                                                .addComponent(titleTxtFldCreatePhysiciantPnl)
                                                .addComponent(eamilTxtFldCreatePhysiciantPnl)
                                                .addComponent(passTxtFldCreatePhysiciantPnl))
                                        .addComponent(specializationComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(12, Short.MAX_VALUE))
        );
        createPhysiciantPnlLayout.setVerticalGroup(
                createPhysiciantPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createPhysiciantPnlLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(createPhysiciantPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(nameLblCreatePhysiciantPnl)
                                        .addComponent(nameTxtFldCreatePhysiciantPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addGroup(createPhysiciantPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(familyNameLblCreatePhysiciantPnl)
                                        .addComponent(familynameTxtFldCreatePhysiciantPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(createPhysiciantPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(streetTxtFldCreatePhysiciantPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(StreetLblCreatePhysiciantPnl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(createPhysiciantPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(houseNumberTxtFldCreatePhysiciantPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(housenumberLblCreatePhysiciantPnl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(createPhysiciantPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(postalCodeTxtFldCreatePhysiciantPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(postalCodeLblCreatePhysiciantPnl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(createPhysiciantPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cityLblCreatePhysiciantPnl)
                                        .addComponent(cityTxtFldCreatePhysiciantPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(createPhysiciantPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(specialisationLblCreatePhysiciantPnl)
                                        .addComponent(specializationComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(createPhysiciantPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(titleLblCreatePhysiciantPnl)
                                        .addComponent(titleTxtFldCreatePhysiciantPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(createPhysiciantPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(emailLblCreatePhysiciantPnl)
                                        .addComponent(eamilTxtFldCreatePhysiciantPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(createPhysiciantPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(phoneLblCreatePhysiciantPnl)
                                        .addComponent(phoneTxtFldCreatePhysiciantPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(createPhysiciantPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(passLblCreatePhysiciantPnl)
                                        .addComponent(passTxtFldCreatePhysiciantPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addComponent(createphysiciantBtnCreatePhysiciantPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(92, Short.MAX_VALUE))
        );

        jPanel3.add(createPhysiciantPnl, "card2");

        createPatientPnl.setkEndColor(new java.awt.Color(255, 255, 255));
        createPatientPnl.setkStartColor(new java.awt.Color(153, 153, 153));

        createpatientBtnCreatePatientPnl.setBorder(null);
        createpatientBtnCreatePatientPnl.setText("Create Patient");
        createpatientBtnCreatePatientPnl.setkEndColor(new java.awt.Color(255, 255, 255));
        createpatientBtnCreatePatientPnl.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        createpatientBtnCreatePatientPnl.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        createpatientBtnCreatePatientPnl.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        createpatientBtnCreatePatientPnl.setkPressedColor(new java.awt.Color(0, 0, 0));
        createpatientBtnCreatePatientPnl.setkSelectedColor(new java.awt.Color(255, 255, 255));
        createpatientBtnCreatePatientPnl.setkStartColor(new java.awt.Color(102, 102, 102));
        createpatientBtnCreatePatientPnl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createpatientBtnCreatePatientPnlActionPerformed(evt);
            }
        });

        nameLblCreatePatientPnl.setText("Name");

        patientFamilyNameTxFldCreatePatientPnl.setText("Family name");

        patientStreetLblCreatePatientPnl.setText("Street");

        patientHousenumberLblCreatePatientPnl.setText("House Number");

        patientPostalCodeLblCreatePatientPnl.setText("Postal code");

        patientCityLblCreatePatientPnl.setText("City");

        patientTitleLblCreatePatientPnl.setText("Title");

        patientEmailLblCreatePatientPnl.setText("E-Mail");

        patientphoneLblCreatePatientPnl.setText("Phone");

        insurance_CreatepatientPnl.setText("Insurance");

        weightLbl_CreatepatientPnl.setText("Weight");

        dateOfBirthtLbl_CreatepatientPnl.setText("Date of birth");

        paswordLbl_CreatepatientPnl.setText("Password");

        insuranceComboBox_createPatientPnl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AOK", "Techniker Krankenkasse", "Allianz" }));

        javax.swing.GroupLayout createPatientPnlLayout = new javax.swing.GroupLayout(createPatientPnl);
        createPatientPnl.setLayout(createPatientPnlLayout);
        createPatientPnlLayout.setHorizontalGroup(
                createPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createPatientPnlLayout.createSequentialGroup()
                                .addGap(0, 403, Short.MAX_VALUE)
                                .addComponent(createpatientBtnCreatePatientPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(createPatientPnlLayout.createSequentialGroup()
                                .addGroup(createPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(createPatientPnlLayout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addGroup(createPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(nameLblCreatePatientPnl)
                                                        .addGroup(createPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addComponent(patientStreetLblCreatePatientPnl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(patientFamilyNameTxFldCreatePatientPnl, javax.swing.GroupLayout.Alignment.LEADING))
                                                        .addComponent(patientHousenumberLblCreatePatientPnl)
                                                        .addComponent(patientPostalCodeLblCreatePatientPnl)
                                                        .addComponent(patientCityLblCreatePatientPnl)))
                                        .addGroup(createPatientPnlLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(insurance_CreatepatientPnl))
                                        .addGroup(createPatientPnlLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(patientTitleLblCreatePatientPnl))
                                        .addGroup(createPatientPnlLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(patientEmailLblCreatePatientPnl))
                                        .addGroup(createPatientPnlLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(patientphoneLblCreatePatientPnl)))
                                .addGap(142, 142, 142)
                                .addGroup(createPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(patientPhoneTxtFld1CreatePatientPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(emailTxtFldCreatePatientPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(patienTtitleTxtFldCreatePatientPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(createPatientPnlLayout.createSequentialGroup()
                                                .addGroup(createPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(insuranceComboBox_createPatientPnl, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(patientnameTxtFldCreatePatientPnl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                                        .addComponent(patientFamilynameTxtFldCreatePatientPnl, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(patientStreetTxtFldCreatePatientPnl, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(patientHouseNumberTxtFldCreatePatientPnl, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(patientPostalCodeTxtFldCreatePatientPnl, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(patientCityTxtFldCreatePatientPnl, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addGap(18, 18, 18)
                                                .addGroup(createPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(weightLbl_CreatepatientPnl)
                                                        .addComponent(dateOfBirthtLbl_CreatepatientPnl)
                                                        .addComponent(paswordLbl_CreatepatientPnl))
                                                .addGap(14, 14, 14)
                                                .addGroup(createPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(weightTxtFld_CreatepatientPnl)
                                                        .addComponent(dateOfBirthTxtFld_CreatepatientPnl)
                                                        .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        createPatientPnlLayout.setVerticalGroup(
                createPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createPatientPnlLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(createPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(createPatientPnlLayout.createSequentialGroup()
                                                .addGroup(createPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(nameLblCreatePatientPnl)
                                                        .addComponent(patientnameTxtFldCreatePatientPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(7, 7, 7)
                                                .addGroup(createPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(patientFamilyNameTxFldCreatePatientPnl)
                                                        .addComponent(patientFamilynameTxtFldCreatePatientPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(createPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(patientStreetLblCreatePatientPnl)
                                                        .addComponent(patientStreetTxtFldCreatePatientPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(createPatientPnlLayout.createSequentialGroup()
                                                .addGroup(createPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(weightLbl_CreatepatientPnl)
                                                        .addComponent(weightTxtFld_CreatepatientPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(createPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(dateOfBirthtLbl_CreatepatientPnl)
                                                        .addComponent(dateOfBirthTxtFld_CreatepatientPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(createPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(paswordLbl_CreatepatientPnl)
                                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(createPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(patientHousenumberLblCreatePatientPnl)
                                        .addComponent(patientHouseNumberTxtFldCreatePatientPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(createPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(patientPostalCodeLblCreatePatientPnl)
                                        .addComponent(patientPostalCodeTxtFldCreatePatientPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(createPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(patientCityLblCreatePatientPnl)
                                        .addComponent(patientCityTxtFldCreatePatientPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4)
                                .addGroup(createPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(insurance_CreatepatientPnl)
                                        .addComponent(insuranceComboBox_createPatientPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addGroup(createPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(patientTitleLblCreatePatientPnl)
                                        .addComponent(patienTtitleTxtFldCreatePatientPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(createPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(patientEmailLblCreatePatientPnl)
                                        .addComponent(emailTxtFldCreatePatientPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(createPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(patientphoneLblCreatePatientPnl)
                                        .addComponent(patientPhoneTxtFld1CreatePatientPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                .addComponent(createpatientBtnCreatePatientPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68))
        );

        jPanel3.add(createPatientPnl, "card2");

        mainPnl.add(jPanel3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(mainPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mainPnl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void userMnagmentBtnActionPerformed(java.awt.event.ActionEvent evt) {

        editPatientPnl.setVisible(false);
        editPhyPnl.setVisible(false);
        editAppointmentPnl.setVisible(false);
        createPhysiciantPnl.setVisible(false);
        createPatientPnl.setVisible(false);
        userMngPnl.setVisible(true);
    }

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {

        dispose();

    }

    private void physicianIconLblUserMngPnlMouseClicked(java.awt.event.MouseEvent evt) {

        editPatientPnl.setVisible(false);
        editAppointmentPnl.setVisible(false);
        createPhysiciantPnl.setVisible(false);
        createPatientPnl.setVisible(false);
        userMngPnl.setVisible(false);
        editPhyPnl.setVisible(true);
    }

    private void patientIconLblUserMngPnlMouseClicked(java.awt.event.MouseEvent evt) {

        editAppointmentPnl.setVisible(false);
        createPhysiciantPnl.setVisible(false);
        createPatientPnl.setVisible(false);
        userMngPnl.setVisible(false);
        editPhyPnl.setVisible(false);
        editPatientPnl.setVisible(true);
    }

    private void appointmenMenagmentBtnActionPerformed(java.awt.event.ActionEvent evt) {

        createPhysiciantPnl.setVisible(false);
        createPatientPnl.setVisible(false);
        userMngPnl.setVisible(false);
        editPhyPnl.setVisible(false);
        editPatientPnl.setVisible(false);
        editAppointmentPnl.setVisible(true);
    }

    private void createPhysicianBtnEditPhyPnlActionPerformed(java.awt.event.ActionEvent evt) {

        createPatientPnl.setVisible(false);
        userMngPnl.setVisible(false);
        editPhyPnl.setVisible(false);
        editPatientPnl.setVisible(false);
        editAppointmentPnl.setVisible(false);
        createPhysiciantPnl.setVisible(true);
    }

    private void searchTxtFldEditPhyPnlActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void searchTxtFldEditPhyPnlMouseClicked(java.awt.event.MouseEvent evt) {
        searchTxtFldEditPhyPnl.setText("");
        searchTxtFldEditPhyPnl.setForeground(Color.black);
    }

    private void createPatientBtnEditPatintPnlActionPerformed(java.awt.event.ActionEvent evt) {

        userMngPnl.setVisible(false);
        editPhyPnl.setVisible(false);
        editPatientPnl.setVisible(false);
        editAppointmentPnl.setVisible(false);
        createPhysiciantPnl.setVisible(false);
        createPatientPnl.setVisible(true);
    }

    private void SearchTexFealdEditPatintPnlActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void SearchTexFealdEditPatintPnlMouseClicked(java.awt.event.MouseEvent evt) {
        SearchTexFealdEditPatintPnl.setText("");
        SearchTexFealdEditPatintPnl.setForeground(Color.black);

    }

    private void searchTxtFldEditPhyPnlKeyPressed(java.awt.event.KeyEvent evt) {
        DefaultTableModel model=(DefaultTableModel)adminPhysicianlisttable.getModel();
        TableRowSorter<DefaultTableModel>tr= new TableRowSorter<DefaultTableModel>(model);
        adminPhysicianlisttable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(searchTxtFldEditPhyPnl.getText().trim()));
    }

    private void searchTxtFldEditPhyPnlKeyReleased(java.awt.event.KeyEvent evt) {
        DefaultTableModel model=(DefaultTableModel)adminPhysicianlisttable.getModel();
        TableRowSorter<DefaultTableModel>tr= new TableRowSorter<DefaultTableModel>(model);
        adminPhysicianlisttable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(searchTxtFldEditPhyPnl.getText().trim()));
    }

    private void SearchTexFealdEditPatintPnlKeyPressed(java.awt.event.KeyEvent evt) {
        DefaultTableModel model=(DefaultTableModel)patientTable_editPatientPnl.getModel();
        TableRowSorter<DefaultTableModel>tr= new TableRowSorter<DefaultTableModel>(model);
        patientTable_editPatientPnl.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(SearchTexFealdEditPatintPnl.getText().trim()));        // TODO add your handling code here:
    }

    private void SearchTexFealdEditPatintPnlKeyReleased(java.awt.event.KeyEvent evt) {
        DefaultTableModel model=(DefaultTableModel)patientTable_editPatientPnl.getModel();
        TableRowSorter<DefaultTableModel>tr= new TableRowSorter<DefaultTableModel>(model);
        patientTable_editPatientPnl.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(SearchTexFealdEditPatintPnl.getText().trim()));        // TODO add your handling code here:
    }

    private void createpatientBtnCreatePatientPnlActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void createphysiciantBtnCreatePhysiciantPnlActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void deleteappointmentBtnEditAppPnlActionPerformed(java.awt.event.ActionEvent evt) {
        //delete appointment button
        DefaultTableModel model = (DefaultTableModel)EditAppointmentjTable1.getModel();

        int index=EditAppointmentjTable1.getSelectedRow();
        String PatientName=model.getValueAt(index,0).toString();
        String PhysicaianName=model.getValueAt(index,1).toString();
        String sDate1=model.getValueAt(index,2).toString();

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
        LocalDateTime dateTime = LocalDateTime.parse(sDate1, formatter);


        for(int i=0;i<appointments.length;i++){
            if(appointments[i].getPatient().getLastName().equals(PatientName)&&appointments[i].getDate().equals(dateTime)){
                try{

                    Databaseconnection databaseconnection = new Databaseconnection();
                    databaseconnection.deleteAppointment(appointments[i]);

                }catch (Exception e) {
                    System.out.println(e.getMessage());


                }
            }
        }


        //delete selected row in table
        int[] rows = EditAppointmentjTable1.getSelectedRows();
        for(int i=0;i<rows.length;i++){
            model.removeRow(rows[i]-i);
        }


    }

    private void deletepatientBtnEditPatintPnlActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void populateAllAppointmentTable(){


        try{
            DefaultTableModel model = (DefaultTableModel)EditAppointmentjTable1.getModel();
            Databaseconnection databaseconnection = new Databaseconnection();
            appointments=databaseconnection.getAllAppointments();
            for (Appointment appointment : appointments) {
                LocalDateTime dateTime = appointment.getDate();
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
                String formattedDateTime = dateTime.format(formatter);
                model.addRow(new Object[]{appointment.getPatient().getLastName(),
                        appointment.getPatient().getEmailAddress(),formattedDateTime});
            }
        }catch (Exception e) {
            System.out.println(e.getMessage());

        }

    }

    private void populatePhysicianTable(){


        try{
            DefaultTableModel model = (DefaultTableModel)adminPhysicianlisttable.getModel();
            Databaseconnection databaseconnection = new Databaseconnection();
            physicians=databaseconnection.getAllPhysicians();
            for (Physician physician : physicians) {
                model.addRow(new Object[]{physician.getFirstName(),physician.getLastName(),
                        physician.getSpecialization(),physician.getEmailAddress(),physician.getPhoneNUmber()});
            }
        }catch (Exception e) {
            System.out.println(e.getMessage());

        }

    }

    private void populatePatientTable(){

        try{
            DefaultTableModel model = (DefaultTableModel)patientTable_editPatientPnl.getModel();
            Databaseconnection databaseconnection = new Databaseconnection();
            patients=databaseconnection.getAllPatients();
            for (Patient patient : patients) {
                model.addRow(new Object[]{patient.getFirstName(),patient.getLastName(),
                        patient.getInsuranceName(),patient.getEmailAddress(),patient.getPhoneNUmber()});
            }
        }catch (Exception e) {
            System.out.println(e.getMessage());

        }

    }


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JTable EditAppointmentjTable1;
    private javax.swing.JTextField SearchTexFealdEditPatintPnl;
    private javax.swing.JLabel StreetLblCreatePhysiciantPnl;
    private javax.swing.JTable adminPhysicianlisttable;
    private keeptoo.KButton appointmenMenagmentBtn;
    private javax.swing.JLabel choseCategoryLblUserMngPnl;
    private javax.swing.JLabel cityLblCreatePhysiciantPnl;
    private javax.swing.JTextField cityTxtFldCreatePhysiciantPnl;
    private keeptoo.KButton createPatientBtnEditPatintPnl;
    private keeptoo.KGradientPanel createPatientPnl;
    private keeptoo.KButton createPhysicianBtnEditPhyPnl;
    private keeptoo.KGradientPanel createPhysiciantPnl;
    private keeptoo.KButton createpatientBtnCreatePatientPnl;
    private keeptoo.KButton createphysiciantBtnCreatePhysiciantPnl;
    private javax.swing.JTextField dateOfBirthTxtFld_CreatepatientPnl;
    private javax.swing.JLabel dateOfBirthtLbl_CreatepatientPnl;
    private keeptoo.KButton deleteButtonEditPhyPnl;
    private keeptoo.KButton deleteappointmentBtnEditAppPnl;
    private keeptoo.KButton deletepatientBtnEditPatintPnl;
    private javax.swing.JTextField eamilTxtFldCreatePhysiciantPnl;
    private keeptoo.KGradientPanel editAppointmentPnl;
    private keeptoo.KGradientPanel editPatientPnl;
    private keeptoo.KGradientPanel editPhyPnl;
    private javax.swing.JLabel emailLblCreatePhysiciantPnl;
    private javax.swing.JTextField emailTxtFldCreatePatientPnl;
    private keeptoo.KButton exitBtn;
    private javax.swing.JLabel familyNameLblCreatePhysiciantPnl;
    private javax.swing.JTextField familynameTxtFldCreatePhysiciantPnl;
    private javax.swing.JTextField houseNumberTxtFldCreatePhysiciantPnl;
    private javax.swing.JLabel housenumberLblCreatePhysiciantPnl;
    private javax.swing.JComboBox<String> insuranceComboBox_createPatientPnl;
    private javax.swing.JLabel insurance_CreatepatientPnl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField2;
    private keeptoo.KButton logoutBtn;
    private keeptoo.KGradientPanel mainPnl;
    private javax.swing.JLabel nameLblCreatePatientPnl;
    private javax.swing.JLabel nameLblCreatePhysiciantPnl;
    private javax.swing.JTextField nameTxtFldCreatePhysiciantPnl;
    private javax.swing.JLabel passLblCreatePhysiciantPnl;
    private javax.swing.JTextField passTxtFldCreatePhysiciantPnl;
    private javax.swing.JLabel paswordLbl_CreatepatientPnl;
    private javax.swing.JLabel pateintListLblEditPatintPnl;
    private javax.swing.JTextField patienTtitleTxtFldCreatePatientPnl;
    private javax.swing.JLabel patientCityLblCreatePatientPnl;
    private javax.swing.JTextField patientCityTxtFldCreatePatientPnl;
    private javax.swing.JLabel patientEmailLblCreatePatientPnl;
    private javax.swing.JLabel patientFamilyNameTxFldCreatePatientPnl;
    private javax.swing.JTextField patientFamilynameTxtFldCreatePatientPnl;
    private javax.swing.JTextField patientHouseNumberTxtFldCreatePatientPnl;
    private javax.swing.JLabel patientHousenumberLblCreatePatientPnl;
    private javax.swing.JLabel patientIconLblUserMngPnl;
    private javax.swing.JLabel patientLblUserMngPnl;
    private javax.swing.JTextField patientPhoneTxtFld1CreatePatientPnl;
    private javax.swing.JLabel patientPostalCodeLblCreatePatientPnl;
    private javax.swing.JTextField patientPostalCodeTxtFldCreatePatientPnl;
    private javax.swing.JLabel patientStreetLblCreatePatientPnl;
    private javax.swing.JTextField patientStreetTxtFldCreatePatientPnl;
    private javax.swing.JTable patientTable_editPatientPnl;
    private javax.swing.JLabel patientTitleLblCreatePatientPnl;
    private javax.swing.JTextField patientnameTxtFldCreatePatientPnl;
    private javax.swing.JLabel patientphoneLblCreatePatientPnl;
    private javax.swing.JLabel phoneLblCreatePhysiciantPnl;
    private javax.swing.JTextField phoneTxtFldCreatePhysiciantPnl;
    private javax.swing.JLabel physicianIconLblUserMngPnl;
    private javax.swing.JLabel physicianLblUserMngPnl;
    private javax.swing.JLabel physicianListlbl;
    private javax.swing.JLabel pictureLbl;
    private javax.swing.JPanel picturePanel;
    private javax.swing.JLabel postalCodeLblCreatePhysiciantPnl;
    private javax.swing.JTextField postalCodeTxtFldCreatePhysiciantPnl;
    private keeptoo.KButton searchBtnEditPhyPnl;
    private javax.swing.JTextField searchTxtFldEditPhyPnl;
    private keeptoo.KButton searchbtnEditPatintPnl;
    private javax.swing.JLabel specialisationLblCreatePhysiciantPnl;
    private javax.swing.JComboBox<String> specializationComboBox1;
    private javax.swing.JTextField streetTxtFldCreatePhysiciantPnl;
    private javax.swing.JLabel titleLblCreatePhysiciantPnl;
    private javax.swing.JTextField titleTxtFldCreatePhysiciantPnl;
    private keeptoo.KButton userMnagmentBtn;
    private keeptoo.KGradientPanel userMngPnl;
    private javax.swing.JLabel weightLbl_CreatepatientPnl;
    private javax.swing.JTextField weightTxtFld_CreatepatientPnl;
    private javax.swing.JLabel welcomeLbl;
    private javax.swing.JLabel welcomenameLbl;
    // End of variables declaration
}
