/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.awt.Color;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author Amar
 */
public class AdminGUI extends javax.swing.JFrame {

    /**
     * Creates new form AdminGUI
     */
    public AdminGUI() {
        setUndecorated(true);
        getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPnl = new keeptoo.KGradientPanel();
        picturePanel = new javax.swing.JPanel();
        pictureLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        userMnagmentBtn = new keeptoo.KButton();
        logoutBtn = new keeptoo.KButton();
        exitBtn = new keeptoo.KButton();
        welcomeLbl = new javax.swing.JLabel();
        welcomenameLbl = new javax.swing.JLabel();
        appointmenMenagmentBtn = new keeptoo.KButton();
        jPanel3 = new javax.swing.JPanel();
        userMngPnl = new keeptoo.KGradientPanel();
        physicianIconLbl = new javax.swing.JLabel();
        patientIconLbl = new javax.swing.JLabel();
        choseCategoryLbl = new javax.swing.JLabel();
        physicianLbl = new javax.swing.JLabel();
        patientLbl = new javax.swing.JLabel();
        editPhyPnl = new keeptoo.KGradientPanel();
        physicianListlbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        adminPhysicianlisttable = new javax.swing.JTable();
        searchBtn = new keeptoo.KButton();
        logoutBtn3 = new keeptoo.KButton();
        createPhysicianBtn = new keeptoo.KButton();
        jTextField1 = new javax.swing.JTextField();
        editPatientPnl = new keeptoo.KGradientPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        logoutBtn5 = new keeptoo.KButton();
        SearchTexFeald = new javax.swing.JTextField();
        deletepatientBtn = new keeptoo.KButton();
        createPatientBtn1 = new keeptoo.KButton();
        editAppointmentPnl = new keeptoo.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EditAppointmentjTable1 = new javax.swing.JTable();
        createappointmentBtn1 = new keeptoo.KButton();
        deleteappointmentBtn = new keeptoo.KButton();
        createAppointmentPnl = new keeptoo.KGradientPanel();
        creatappointmenttBtn2 = new keeptoo.KButton();
        patientNameLbl = new javax.swing.JLabel();
        physicianNameLbl = new javax.swing.JLabel();
        AppoinmentdateLbl = new javax.swing.JLabel();
        patientNameTxtFld = new javax.swing.JTextField();
        physicianTxtBox = new javax.swing.JTextField();
        appointmetTxtFld = new javax.swing.JTextField();
        createPhysiciantPnl = new keeptoo.KGradientPanel();
        createphysiciantBtn2 = new keeptoo.KButton();
        phoneLbl = new javax.swing.JLabel();
        SpecificationLbl = new javax.swing.JLabel();
        TitleLbl = new javax.swing.JLabel();
        housenumberLbl = new javax.swing.JLabel();
        emailLbl = new javax.swing.JLabel();
        StreetLbl = new javax.swing.JLabel();
        FamilyNameTexfld = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        postalCodeLbl = new javax.swing.JLabel();
        CityLbl = new javax.swing.JLabel();
        nameTxtFld = new javax.swing.JTextField();
        FamilynameTxtFld = new javax.swing.JTextField();
        StreetTxtFld = new javax.swing.JTextField();
        houseNumberTxtFld = new javax.swing.JTextField();
        postalCodeTxtFld = new javax.swing.JTextField();
        cityTxtFld = new javax.swing.JTextField();
        specificationTxtFld = new javax.swing.JTextField();
        titleTxtFld = new javax.swing.JTextField();
        eamilTxtFld = new javax.swing.JTextField();
        phoneTxtFld = new javax.swing.JTextField();
        createPatienttPnl = new keeptoo.KGradientPanel();
        createpatientBtn3 = new keeptoo.KButton();
        patientnameTxtFld = new javax.swing.JTextField();
        nameLbl1 = new javax.swing.JLabel();
        patientFamilynameTxtFld = new javax.swing.JTextField();
        patientFamilyNameTexfld = new javax.swing.JLabel();
        patientStreetLbl = new javax.swing.JLabel();
        patientStreetTxtFld = new javax.swing.JTextField();
        patientHousenumberLbl = new javax.swing.JLabel();
        patientHouseNumberTxtFld = new javax.swing.JTextField();
        patientPostalCodeTxtFld = new javax.swing.JTextField();
        patientPostalCodeLbl = new javax.swing.JLabel();
        patientCityLbl = new javax.swing.JLabel();
        patientSpecificationLbl = new javax.swing.JLabel();
        patientTitleLbl = new javax.swing.JLabel();
        patientEmailLbl = new javax.swing.JLabel();
        patientphoneLbl = new javax.swing.JLabel();
        patientPhoneTxtFld1 = new javax.swing.JTextField();
        emailTxtFld = new javax.swing.JTextField();
        patienTtitleTxtFld = new javax.swing.JTextField();
        patientSpecificationTxtFld = new javax.swing.JTextField();
        patientCityTxtFld = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPnl.setkEndColor(new java.awt.Color(255, 255, 255));
        mainPnl.setkStartColor(new java.awt.Color(153, 204, 255));
        mainPnl.setLayout(new java.awt.BorderLayout());

        pictureLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/adminpic.jpg"))); // NOI18N
        pictureLbl.setText("jLabel8");

        javax.swing.GroupLayout picturePanelLayout = new javax.swing.GroupLayout(picturePanel);
        picturePanel.setLayout(picturePanelLayout);
        picturePanelLayout.setHorizontalGroup(
            picturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pictureLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 891, Short.MAX_VALUE)
        );
        picturePanelLayout.setVerticalGroup(
            picturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(picturePanelLayout.createSequentialGroup()
                .addComponent(pictureLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        mainPnl.add(picturePanel, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        userMnagmentBtn.setBorder(null);
        userMnagmentBtn.setText("User management");
        userMnagmentBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        userMnagmentBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        userMnagmentBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        userMnagmentBtn.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        userMnagmentBtn.setkPressedColor(new java.awt.Color(0, 0, 0));
        userMnagmentBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        userMnagmentBtn.setkStartColor(new java.awt.Color(102, 102, 102));
        userMnagmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userMnagmentBtnActionPerformed(evt);
            }
        });

        logoutBtn.setBorder(null);
        logoutBtn.setText("Logout");
        logoutBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        logoutBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        logoutBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        logoutBtn.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        logoutBtn.setkPressedColor(new java.awt.Color(0, 0, 0));
        logoutBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        logoutBtn.setkStartColor(new java.awt.Color(102, 102, 102));

        exitBtn.setBorder(null);
        exitBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        exitBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        exitBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        exitBtn.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        exitBtn.setkPressedColor(new java.awt.Color(0, 0, 0));
        exitBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        exitBtn.setkStartColor(new java.awt.Color(102, 102, 102));
        exitBtn.setLabel("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        welcomeLbl.setFont(new java.awt.Font("Baskerville Old Face", 2, 20)); // NOI18N
        welcomeLbl.setText("Welcome");

        welcomenameLbl.setFont(new java.awt.Font("Baskerville Old Face", 2, 20)); // NOI18N
        welcomenameLbl.setText("Name");

        appointmenMenagmentBtn.setBorder(null);
        appointmenMenagmentBtn.setText("Appointment menagment");
        appointmenMenagmentBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        appointmenMenagmentBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        appointmenMenagmentBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        appointmenMenagmentBtn.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        appointmenMenagmentBtn.setkPressedColor(new java.awt.Color(0, 0, 0));
        appointmenMenagmentBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        appointmenMenagmentBtn.setkStartColor(new java.awt.Color(102, 102, 102));
        appointmenMenagmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointmenMenagmentBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoutBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
            .addComponent(exitBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(welcomeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(welcomenameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(appointmenMenagmentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(userMnagmentBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(welcomeLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(welcomenameLbl)
                .addGap(64, 64, 64)
                .addComponent(userMnagmentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(appointmenMenagmentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        mainPnl.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setLayout(new java.awt.CardLayout());

        userMngPnl.setkEndColor(new java.awt.Color(255, 255, 255));
        userMngPnl.setkStartColor(new java.awt.Color(153, 153, 153));

        physicianIconLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/doctor-3552.png"))); // NOI18N
        physicianIconLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        physicianIconLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                physicianIconLblMouseClicked(evt);
            }
        });

        patientIconLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/cough-3253 (1).png"))); // NOI18N
        patientIconLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        patientIconLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patientIconLblMouseClicked(evt);
            }
        });

        choseCategoryLbl.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        choseCategoryLbl.setText("Choose category");

        physicianLbl.setBackground(new java.awt.Color(255, 255, 255));
        physicianLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        physicianLbl.setText("Physician");

        patientLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        patientLbl.setText("Patient");

        javax.swing.GroupLayout userMngPnlLayout = new javax.swing.GroupLayout(userMngPnl);
        userMngPnl.setLayout(userMngPnlLayout);
        userMngPnlLayout.setHorizontalGroup(
            userMngPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userMngPnlLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(physicianLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(patientLbl)
                .addGap(130, 130, 130))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userMngPnlLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(userMngPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(choseCategoryLbl)
                    .addGroup(userMngPnlLayout.createSequentialGroup()
                        .addComponent(physicianIconLbl)
                        .addGap(51, 51, 51)
                        .addComponent(patientIconLbl)))
                .addGap(31, 31, 31))
        );
        userMngPnlLayout.setVerticalGroup(
            userMngPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userMngPnlLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(choseCategoryLbl)
                .addGap(33, 33, 33)
                .addGroup(userMngPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(physicianIconLbl)
                    .addComponent(patientIconLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(userMngPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(physicianLbl)
                    .addComponent(patientLbl))
                .addGap(64, 64, 64))
        );

        jPanel3.add(userMngPnl, "card4");

        editPhyPnl.setkEndColor(new java.awt.Color(255, 255, 255));
        editPhyPnl.setkStartColor(new java.awt.Color(153, 153, 153));

        physicianListlbl.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        physicianListlbl.setText("Physician list");

        adminPhysicianlisttable.setBackground(new java.awt.Color(204, 204, 204));
        adminPhysicianlisttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Amar", null, null, "wda", null},
                {"2", "Sascha", null, null, "dwda", null},
                {"3", "Achim", null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "First name", "Last name", "Specification", "E-Mail ", "Phone"
            }
        ));
        jScrollPane2.setViewportView(adminPhysicianlisttable);

        searchBtn.setBorder(null);
        searchBtn.setText("Search");
        searchBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        searchBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        searchBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        searchBtn.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        searchBtn.setkPressedColor(new java.awt.Color(0, 0, 0));
        searchBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        searchBtn.setkStartColor(new java.awt.Color(102, 102, 102));

        logoutBtn3.setBorder(null);
        logoutBtn3.setText("Delete Physician");
        logoutBtn3.setkEndColor(new java.awt.Color(255, 255, 255));
        logoutBtn3.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        logoutBtn3.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        logoutBtn3.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        logoutBtn3.setkPressedColor(new java.awt.Color(0, 0, 0));
        logoutBtn3.setkSelectedColor(new java.awt.Color(255, 255, 255));
        logoutBtn3.setkStartColor(new java.awt.Color(102, 102, 102));

        createPhysicianBtn.setBorder(null);
        createPhysicianBtn.setText("Create Physician");
        createPhysicianBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        createPhysicianBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        createPhysicianBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        createPhysicianBtn.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        createPhysicianBtn.setkPressedColor(new java.awt.Color(0, 0, 0));
        createPhysicianBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        createPhysicianBtn.setkStartColor(new java.awt.Color(102, 102, 102));
        createPhysicianBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPhysicianBtnActionPerformed(evt);
            }
        });

        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.setText("Type here to search...");
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout editPhyPnlLayout = new javax.swing.GroupLayout(editPhyPnl);
        editPhyPnl.setLayout(editPhyPnlLayout);
        editPhyPnlLayout.setHorizontalGroup(
            editPhyPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
            .addGroup(editPhyPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editPhyPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPhyPnlLayout.createSequentialGroup()
                        .addComponent(physicianListlbl)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPhyPnlLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(editPhyPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPhyPnlLayout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPhyPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(createPhysicianBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                .addComponent(logoutBtn3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        editPhyPnlLayout.setVerticalGroup(
            editPhyPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPhyPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(physicianListlbl)
                .addGap(22, 22, 22)
                .addGroup(editPhyPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(logoutBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(createPhysicianBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jPanel3.add(editPhyPnl, "card2");

        editPatientPnl.setkEndColor(new java.awt.Color(255, 255, 255));
        editPatientPnl.setkStartColor(new java.awt.Color(153, 153, 153));

        jTable3.setBackground(new java.awt.Color(204, 204, 204));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Dirk", null, null, "dsd", null},
                {"2", "Marcel", null, null, null, null},
                {"3", "Dino", null, null, "s", null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "First name", "Last name", "Address", "E-Mail ", "Phone"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel11.setText("Patient list");

        logoutBtn5.setBorder(null);
        logoutBtn5.setText("Search");
        logoutBtn5.setkEndColor(new java.awt.Color(255, 255, 255));
        logoutBtn5.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        logoutBtn5.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        logoutBtn5.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        logoutBtn5.setkPressedColor(new java.awt.Color(0, 0, 0));
        logoutBtn5.setkSelectedColor(new java.awt.Color(255, 255, 255));
        logoutBtn5.setkStartColor(new java.awt.Color(102, 102, 102));

        SearchTexFeald.setForeground(new java.awt.Color(204, 204, 204));
        SearchTexFeald.setText("Type here to search...");
        SearchTexFeald.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchTexFealdMouseClicked(evt);
            }
        });
        SearchTexFeald.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTexFealdActionPerformed(evt);
            }
        });
        SearchTexFeald.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SearchTexFealdKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchTexFealdKeyReleased(evt);
            }
        });

        deletepatientBtn.setBorder(null);
        deletepatientBtn.setText("Delete patient");
        deletepatientBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        deletepatientBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        deletepatientBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        deletepatientBtn.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        deletepatientBtn.setkPressedColor(new java.awt.Color(0, 0, 0));
        deletepatientBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        deletepatientBtn.setkStartColor(new java.awt.Color(102, 102, 102));

        createPatientBtn1.setBorder(null);
        createPatientBtn1.setText("Create patient");
        createPatientBtn1.setkEndColor(new java.awt.Color(255, 255, 255));
        createPatientBtn1.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        createPatientBtn1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        createPatientBtn1.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        createPatientBtn1.setkPressedColor(new java.awt.Color(0, 0, 0));
        createPatientBtn1.setkSelectedColor(new java.awt.Color(255, 255, 255));
        createPatientBtn1.setkStartColor(new java.awt.Color(102, 102, 102));
        createPatientBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPatientBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editPatientPnlLayout = new javax.swing.GroupLayout(editPatientPnl);
        editPatientPnl.setLayout(editPatientPnlLayout);
        editPatientPnlLayout.setHorizontalGroup(
            editPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPatientPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                    .addGroup(editPatientPnlLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPatientPnlLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(editPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPatientPnlLayout.createSequentialGroup()
                                .addComponent(SearchTexFeald, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(logoutBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(createPatientBtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deletepatientBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        editPatientPnlLayout.setVerticalGroup(
            editPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPatientPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(8, 8, 8)
                .addGroup(editPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchTexFeald, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(deletepatientBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(createPatientBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jPanel3.add(editPatientPnl, "card2");

        editAppointmentPnl.setkEndColor(new java.awt.Color(255, 255, 255));
        editAppointmentPnl.setkStartColor(new java.awt.Color(153, 153, 153));

        EditAppointmentjTable1.setBackground(new java.awt.Color(204, 204, 204));
        EditAppointmentjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Patient", "Physician", "Appointment date and time"
            }
        ));
        jScrollPane1.setViewportView(EditAppointmentjTable1);

        createappointmentBtn1.setBorder(null);
        createappointmentBtn1.setText("Create appointment");
        createappointmentBtn1.setkEndColor(new java.awt.Color(255, 255, 255));
        createappointmentBtn1.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        createappointmentBtn1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        createappointmentBtn1.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        createappointmentBtn1.setkPressedColor(new java.awt.Color(0, 0, 0));
        createappointmentBtn1.setkSelectedColor(new java.awt.Color(255, 255, 255));
        createappointmentBtn1.setkStartColor(new java.awt.Color(102, 102, 102));
        createappointmentBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createappointmentBtn1ActionPerformed(evt);
            }
        });

        deleteappointmentBtn.setBorder(null);
        deleteappointmentBtn.setText("Delete appointment");
        deleteappointmentBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        deleteappointmentBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        deleteappointmentBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        deleteappointmentBtn.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        deleteappointmentBtn.setkPressedColor(new java.awt.Color(0, 0, 0));
        deleteappointmentBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        deleteappointmentBtn.setkStartColor(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout editAppointmentPnlLayout = new javax.swing.GroupLayout(editAppointmentPnl);
        editAppointmentPnl.setLayout(editAppointmentPnlLayout);
        editAppointmentPnlLayout.setHorizontalGroup(
            editAppointmentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editAppointmentPnlLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(editAppointmentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createappointmentBtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteappointmentBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        editAppointmentPnlLayout.setVerticalGroup(
            editAppointmentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editAppointmentPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(createappointmentBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(deleteappointmentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        jPanel3.add(editAppointmentPnl, "card2");

        createAppointmentPnl.setkEndColor(new java.awt.Color(255, 255, 255));
        createAppointmentPnl.setkStartColor(new java.awt.Color(153, 153, 153));

        creatappointmenttBtn2.setBorder(null);
        creatappointmenttBtn2.setText("Create appointment");
        creatappointmenttBtn2.setkEndColor(new java.awt.Color(255, 255, 255));
        creatappointmenttBtn2.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        creatappointmenttBtn2.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        creatappointmenttBtn2.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        creatappointmenttBtn2.setkPressedColor(new java.awt.Color(0, 0, 0));
        creatappointmenttBtn2.setkSelectedColor(new java.awt.Color(255, 255, 255));
        creatappointmenttBtn2.setkStartColor(new java.awt.Color(102, 102, 102));

        patientNameLbl.setText("Patient name");

        physicianNameLbl.setText("Physician name");

        AppoinmentdateLbl.setText("Appoinment date");

        javax.swing.GroupLayout createAppointmentPnlLayout = new javax.swing.GroupLayout(createAppointmentPnl);
        createAppointmentPnl.setLayout(createAppointmentPnlLayout);
        createAppointmentPnlLayout.setHorizontalGroup(
            createAppointmentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createAppointmentPnlLayout.createSequentialGroup()
                .addGap(0, 403, Short.MAX_VALUE)
                .addComponent(creatappointmenttBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(createAppointmentPnlLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addGroup(createAppointmentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AppoinmentdateLbl)
                    .addComponent(physicianNameLbl)
                    .addComponent(patientNameLbl))
                .addGap(50, 50, 50)
                .addGroup(createAppointmentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(patientNameTxtFld)
                    .addComponent(physicianTxtBox)
                    .addComponent(appointmetTxtFld, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        createAppointmentPnlLayout.setVerticalGroup(
            createAppointmentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createAppointmentPnlLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(createAppointmentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientNameLbl)
                    .addComponent(patientNameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(createAppointmentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(physicianNameLbl)
                    .addComponent(physicianTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(createAppointmentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AppoinmentdateLbl)
                    .addComponent(appointmetTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addComponent(creatappointmenttBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        jPanel3.add(createAppointmentPnl, "card2");

        createPhysiciantPnl.setkEndColor(new java.awt.Color(255, 255, 255));
        createPhysiciantPnl.setkStartColor(new java.awt.Color(153, 153, 153));

        createphysiciantBtn2.setBorder(null);
        createphysiciantBtn2.setText("Create Physician");
        createphysiciantBtn2.setkEndColor(new java.awt.Color(255, 255, 255));
        createphysiciantBtn2.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        createphysiciantBtn2.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        createphysiciantBtn2.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        createphysiciantBtn2.setkPressedColor(new java.awt.Color(0, 0, 0));
        createphysiciantBtn2.setkSelectedColor(new java.awt.Color(255, 255, 255));
        createphysiciantBtn2.setkStartColor(new java.awt.Color(102, 102, 102));

        phoneLbl.setText("Phone");

        SpecificationLbl.setText("Specification");

        TitleLbl.setText("Title");

        housenumberLbl.setText("House Number");

        emailLbl.setText("E-Mail");

        StreetLbl.setText("Street");

        FamilyNameTexfld.setText("Family name");

        nameLbl.setText("Name");

        postalCodeLbl.setText("Postal code");

        CityLbl.setText("City");

        javax.swing.GroupLayout createPhysiciantPnlLayout = new javax.swing.GroupLayout(createPhysiciantPnl);
        createPhysiciantPnl.setLayout(createPhysiciantPnlLayout);
        createPhysiciantPnlLayout.setHorizontalGroup(
            createPhysiciantPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPhysiciantPnlLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(createPhysiciantPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(createPhysiciantPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nameLbl)
                        .addGroup(createPhysiciantPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(StreetLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FamilyNameTexfld, javax.swing.GroupLayout.Alignment.LEADING))
                        .addComponent(housenumberLbl)
                        .addComponent(postalCodeLbl)
                        .addComponent(CityLbl)
                        .addComponent(SpecificationLbl)
                        .addComponent(TitleLbl)
                        .addComponent(emailLbl))
                    .addGroup(createPhysiciantPnlLayout.createSequentialGroup()
                        .addComponent(phoneLbl)
                        .addGap(42, 42, 42)))
                .addGap(142, 142, 142)
                .addGroup(createPhysiciantPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameTxtFld)
                    .addComponent(FamilynameTxtFld)
                    .addComponent(StreetTxtFld)
                    .addComponent(houseNumberTxtFld)
                    .addComponent(postalCodeTxtFld)
                    .addComponent(cityTxtFld)
                    .addComponent(specificationTxtFld)
                    .addComponent(titleTxtFld)
                    .addComponent(eamilTxtFld)
                    .addComponent(phoneTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(164, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createPhysiciantPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createphysiciantBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        createPhysiciantPnlLayout.setVerticalGroup(
            createPhysiciantPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createPhysiciantPnlLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(createPhysiciantPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLbl)
                    .addComponent(nameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(createPhysiciantPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FamilyNameTexfld)
                    .addComponent(FamilynameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createPhysiciantPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StreetLbl)
                    .addComponent(StreetTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createPhysiciantPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(housenumberLbl)
                    .addComponent(houseNumberTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createPhysiciantPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(postalCodeLbl)
                    .addComponent(postalCodeTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createPhysiciantPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CityLbl)
                    .addComponent(cityTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createPhysiciantPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(specificationTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpecificationLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createPhysiciantPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TitleLbl)
                    .addComponent(titleTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createPhysiciantPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLbl)
                    .addComponent(eamilTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createPhysiciantPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLbl)
                    .addComponent(phoneTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(createphysiciantBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jPanel3.add(createPhysiciantPnl, "card2");

        createPatienttPnl.setkEndColor(new java.awt.Color(255, 255, 255));
        createPatienttPnl.setkStartColor(new java.awt.Color(153, 153, 153));

        createpatientBtn3.setBorder(null);
        createpatientBtn3.setText("Create patient");
        createpatientBtn3.setkEndColor(new java.awt.Color(255, 255, 255));
        createpatientBtn3.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        createpatientBtn3.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        createpatientBtn3.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        createpatientBtn3.setkPressedColor(new java.awt.Color(0, 0, 0));
        createpatientBtn3.setkSelectedColor(new java.awt.Color(255, 255, 255));
        createpatientBtn3.setkStartColor(new java.awt.Color(102, 102, 102));

        nameLbl1.setText("Name");

        patientFamilyNameTexfld.setText("Family name");

        patientStreetLbl.setText("Street");

        patientHousenumberLbl.setText("House Number");

        patientPostalCodeLbl.setText("Postal code");

        patientCityLbl.setText("City");

        patientSpecificationLbl.setText("Specification");

        patientTitleLbl.setText("Title");

        patientEmailLbl.setText("E-Mail");

        patientphoneLbl.setText("Phone");

        javax.swing.GroupLayout createPatienttPnlLayout = new javax.swing.GroupLayout(createPatienttPnl);
        createPatienttPnl.setLayout(createPatienttPnlLayout);
        createPatienttPnlLayout.setHorizontalGroup(
            createPatienttPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createPatienttPnlLayout.createSequentialGroup()
                .addGap(0, 403, Short.MAX_VALUE)
                .addComponent(createpatientBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(createPatienttPnlLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(createPatienttPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(createPatienttPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nameLbl1)
                        .addGroup(createPatienttPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(patientStreetLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(patientFamilyNameTexfld, javax.swing.GroupLayout.Alignment.LEADING))
                        .addComponent(patientHousenumberLbl)
                        .addComponent(patientPostalCodeLbl)
                        .addComponent(patientCityLbl)
                        .addComponent(patientSpecificationLbl)
                        .addComponent(patientTitleLbl)
                        .addComponent(patientEmailLbl))
                    .addGroup(createPatienttPnlLayout.createSequentialGroup()
                        .addComponent(patientphoneLbl)
                        .addGap(42, 42, 42)))
                .addGap(142, 142, 142)
                .addGroup(createPatienttPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(patientnameTxtFld)
                    .addComponent(patientFamilynameTxtFld)
                    .addComponent(patientStreetTxtFld)
                    .addComponent(patientHouseNumberTxtFld)
                    .addComponent(patientPostalCodeTxtFld)
                    .addComponent(patientCityTxtFld)
                    .addComponent(patientSpecificationTxtFld)
                    .addComponent(patienTtitleTxtFld)
                    .addComponent(emailTxtFld)
                    .addComponent(patientPhoneTxtFld1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        createPatienttPnlLayout.setVerticalGroup(
            createPatienttPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createPatienttPnlLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(createPatienttPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLbl1)
                    .addComponent(patientnameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(createPatienttPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientFamilyNameTexfld)
                    .addComponent(patientFamilynameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createPatienttPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientStreetLbl)
                    .addComponent(patientStreetTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createPatienttPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientHousenumberLbl)
                    .addComponent(patientHouseNumberTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createPatienttPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientPostalCodeLbl)
                    .addComponent(patientPostalCodeTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createPatienttPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientCityLbl)
                    .addComponent(patientCityTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createPatienttPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientSpecificationTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientSpecificationLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createPatienttPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientTitleLbl)
                    .addComponent(patienTtitleTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createPatienttPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientEmailLbl)
                    .addComponent(emailTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createPatienttPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientphoneLbl)
                    .addComponent(patientPhoneTxtFld1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(createpatientBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        jPanel3.add(createPatienttPnl, "card2");

        mainPnl.add(jPanel3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(mainPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPnl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userMnagmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userMnagmentBtnActionPerformed
        createAppointmentPnl.setVisible(false);
        editPatientPnl.setVisible(false);
        editPhyPnl.setVisible(false);
        editAppointmentPnl.setVisible(false);
        createPhysiciantPnl.setVisible(false);
        createPatienttPnl.setVisible(false);
        userMngPnl.setVisible(true);
    }//GEN-LAST:event_userMnagmentBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed

        dispose();

    }//GEN-LAST:event_exitBtnActionPerformed

    private void physicianIconLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_physicianIconLblMouseClicked
       createAppointmentPnl.setVisible(false);
        editPatientPnl.setVisible(false);
        editAppointmentPnl.setVisible(false);
        createPhysiciantPnl.setVisible(false);
        createPatienttPnl.setVisible(false);
        userMngPnl.setVisible(false);
        editPhyPnl.setVisible(true);
    }//GEN-LAST:event_physicianIconLblMouseClicked

    private void patientIconLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientIconLblMouseClicked
        createAppointmentPnl.setVisible(false);
        editAppointmentPnl.setVisible(false);
        createPhysiciantPnl.setVisible(false);
        createPatienttPnl.setVisible(false);
        userMngPnl.setVisible(false);
        editPhyPnl.setVisible(false);
        editPatientPnl.setVisible(true);
    }//GEN-LAST:event_patientIconLblMouseClicked

    private void appointmenMenagmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointmenMenagmentBtnActionPerformed
       createAppointmentPnl.setVisible(false);
        createPhysiciantPnl.setVisible(false);
        createPatienttPnl.setVisible(false);
        userMngPnl.setVisible(false);
        editPhyPnl.setVisible(false);
         editPatientPnl.setVisible(false);
         editAppointmentPnl.setVisible(true);
    }//GEN-LAST:event_appointmenMenagmentBtnActionPerformed

    private void createPhysicianBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPhysicianBtnActionPerformed
     createAppointmentPnl.setVisible(false);
        createPatienttPnl.setVisible(false);
        userMngPnl.setVisible(false);
        editPhyPnl.setVisible(false);
         editPatientPnl.setVisible(false);
         editAppointmentPnl.setVisible(false);
         createPhysiciantPnl.setVisible(true);
    }//GEN-LAST:event_createPhysicianBtnActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
    jTextField1.setText("");
    jTextField1.setForeground(Color.black);
    }//GEN-LAST:event_jTextField1MouseClicked

    private void createPatientBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPatientBtn1ActionPerformed
        createAppointmentPnl.setVisible(false);
        userMngPnl.setVisible(false);
        editPhyPnl.setVisible(false);
         editPatientPnl.setVisible(false);
         editAppointmentPnl.setVisible(false);
         createPhysiciantPnl.setVisible(false);
         createPatienttPnl.setVisible(true);
    }//GEN-LAST:event_createPatientBtn1ActionPerformed

    private void SearchTexFealdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTexFealdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchTexFealdActionPerformed

    private void SearchTexFealdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchTexFealdMouseClicked
        SearchTexFeald.setText("");
        SearchTexFeald.setForeground(Color.black);

    }//GEN-LAST:event_SearchTexFealdMouseClicked

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
    DefaultTableModel model=(DefaultTableModel)adminPhysicianlisttable.getModel();
    TableRowSorter<DefaultTableModel>tr= new TableRowSorter<DefaultTableModel>(model);
    adminPhysicianlisttable.setRowSorter(tr);
    tr.setRowFilter(RowFilter.regexFilter(jTextField1.getText().trim()));
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
    DefaultTableModel model=(DefaultTableModel)adminPhysicianlisttable.getModel();
    TableRowSorter<DefaultTableModel>tr= new TableRowSorter<DefaultTableModel>(model);
    adminPhysicianlisttable.setRowSorter(tr);
    tr.setRowFilter(RowFilter.regexFilter(jTextField1.getText().trim()));
    }//GEN-LAST:event_jTextField1KeyReleased

    private void SearchTexFealdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchTexFealdKeyPressed
    DefaultTableModel model=(DefaultTableModel)jTable3.getModel();
    TableRowSorter<DefaultTableModel>tr= new TableRowSorter<DefaultTableModel>(model);
    jTable3.setRowSorter(tr);
    tr.setRowFilter(RowFilter.regexFilter(SearchTexFeald.getText().trim()));        // TODO add your handling code here:
    }//GEN-LAST:event_SearchTexFealdKeyPressed

    private void SearchTexFealdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchTexFealdKeyReleased
    DefaultTableModel model=(DefaultTableModel)jTable3.getModel();
    TableRowSorter<DefaultTableModel>tr= new TableRowSorter<DefaultTableModel>(model);
    jTable3.setRowSorter(tr);
    tr.setRowFilter(RowFilter.regexFilter(SearchTexFeald.getText().trim()));        // TODO add your handling code here:
    }//GEN-LAST:event_SearchTexFealdKeyReleased

    private void createappointmentBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createappointmentBtn1ActionPerformed
         userMngPnl.setVisible(false);
        editPhyPnl.setVisible(false);
         editPatientPnl.setVisible(false);
         editAppointmentPnl.setVisible(false);
         createPhysiciantPnl.setVisible(false);
         createPatienttPnl.setVisible(false);
         createAppointmentPnl.setVisible(true);
    }//GEN-LAST:event_createappointmentBtn1ActionPerformed

    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AppoinmentdateLbl;
    private javax.swing.JLabel CityLbl;
    private javax.swing.JTable EditAppointmentjTable1;
    private javax.swing.JLabel FamilyNameTexfld;
    private javax.swing.JTextField FamilynameTxtFld;
    private javax.swing.JTextField SearchTexFeald;
    private javax.swing.JLabel SpecificationLbl;
    private javax.swing.JLabel StreetLbl;
    private javax.swing.JTextField StreetTxtFld;
    private javax.swing.JLabel TitleLbl;
    private javax.swing.JTable adminPhysicianlisttable;
    private keeptoo.KButton appointmenMenagmentBtn;
    private javax.swing.JTextField appointmetTxtFld;
    private javax.swing.JLabel choseCategoryLbl;
    private javax.swing.JTextField cityTxtFld;
    private keeptoo.KButton creatappointmenttBtn2;
    private keeptoo.KGradientPanel createAppointmentPnl;
    private keeptoo.KButton createPatientBtn1;
    private keeptoo.KGradientPanel createPatienttPnl;
    private keeptoo.KButton createPhysicianBtn;
    private keeptoo.KGradientPanel createPhysiciantPnl;
    private keeptoo.KButton createappointmentBtn1;
    private keeptoo.KButton createpatientBtn3;
    private keeptoo.KButton createphysiciantBtn2;
    private keeptoo.KButton deleteappointmentBtn;
    private keeptoo.KButton deletepatientBtn;
    private javax.swing.JTextField eamilTxtFld;
    private keeptoo.KGradientPanel editAppointmentPnl;
    private keeptoo.KGradientPanel editPatientPnl;
    private keeptoo.KGradientPanel editPhyPnl;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField emailTxtFld;
    private keeptoo.KButton exitBtn;
    private javax.swing.JTextField houseNumberTxtFld;
    private javax.swing.JLabel housenumberLbl;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private keeptoo.KButton logoutBtn;
    private keeptoo.KButton logoutBtn3;
    private keeptoo.KButton logoutBtn5;
    private keeptoo.KGradientPanel mainPnl;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JLabel nameLbl1;
    private javax.swing.JTextField nameTxtFld;
    private javax.swing.JTextField patienTtitleTxtFld;
    private javax.swing.JLabel patientCityLbl;
    private javax.swing.JTextField patientCityTxtFld;
    private javax.swing.JLabel patientEmailLbl;
    private javax.swing.JLabel patientFamilyNameTexfld;
    private javax.swing.JTextField patientFamilynameTxtFld;
    private javax.swing.JTextField patientHouseNumberTxtFld;
    private javax.swing.JLabel patientHousenumberLbl;
    private javax.swing.JLabel patientIconLbl;
    private javax.swing.JLabel patientLbl;
    private javax.swing.JLabel patientNameLbl;
    private javax.swing.JTextField patientNameTxtFld;
    private javax.swing.JTextField patientPhoneTxtFld1;
    private javax.swing.JLabel patientPostalCodeLbl;
    private javax.swing.JTextField patientPostalCodeTxtFld;
    private javax.swing.JLabel patientSpecificationLbl;
    private javax.swing.JTextField patientSpecificationTxtFld;
    private javax.swing.JLabel patientStreetLbl;
    private javax.swing.JTextField patientStreetTxtFld;
    private javax.swing.JLabel patientTitleLbl;
    private javax.swing.JTextField patientnameTxtFld;
    private javax.swing.JLabel patientphoneLbl;
    private javax.swing.JLabel phoneLbl;
    private javax.swing.JTextField phoneTxtFld;
    private javax.swing.JLabel physicianIconLbl;
    private javax.swing.JLabel physicianLbl;
    private javax.swing.JLabel physicianListlbl;
    private javax.swing.JLabel physicianNameLbl;
    private javax.swing.JTextField physicianTxtBox;
    private javax.swing.JLabel pictureLbl;
    private javax.swing.JPanel picturePanel;
    private javax.swing.JLabel postalCodeLbl;
    private javax.swing.JTextField postalCodeTxtFld;
    private keeptoo.KButton searchBtn;
    private javax.swing.JTextField specificationTxtFld;
    private javax.swing.JTextField titleTxtFld;
    private keeptoo.KButton userMnagmentBtn;
    private keeptoo.KGradientPanel userMngPnl;
    private javax.swing.JLabel welcomeLbl;
    private javax.swing.JLabel welcomenameLbl;
    // End of variables declaration//GEN-END:variables
}
