/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import javax.swing.*;
import java.sql.SQLException;

/**
 *
 * @author Amar
 */
public class LoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form loginV2
     */
    public LoginGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        transparentLoginPanel = new javax.swing.JPanel();
        loginLbl = new javax.swing.JLabel();
        userEmailLoginLbl = new javax.swing.JLabel();
        passwordLblLogin = new javax.swing.JLabel();
        userEmailLoginTxdFld = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        logintBtn = new keeptoo.KButton();
        newRegistrationLbl = new javax.swing.JLabel();
        forgotPassLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        registerPhysicianPanel = new javax.swing.JPanel();
        registerPhysicainTransparentPnl1 = new javax.swing.JPanel();
        RegistrationLblPhysician = new javax.swing.JLabel();
        emailLblPhysician = new javax.swing.JLabel();
        passwordLblPhysician = new javax.swing.JLabel();
        emailTxtPhysician = new javax.swing.JTextField();
        passwordTxtFldPhysician = new javax.swing.JPasswordField();
        registrationPhysicinaBackBtn = new keeptoo.KButton();
        firstNameLblPhysician = new javax.swing.JLabel();
        lastNameLblPhysician = new javax.swing.JLabel();
        titleLblPhysician = new javax.swing.JLabel();
        postalCodeLblPhysician = new javax.swing.JLabel();
        cityLblPhysician = new javax.swing.JLabel();
        specializationLblPhysician = new javax.swing.JLabel();
        housenumberLblPhysician = new javax.swing.JLabel();
        firstNameTxtFldPhysician = new javax.swing.JTextField();
        lastNameTxtFldPhysician = new javax.swing.JTextField();
        houseNummberTxtfldPhysician = new javax.swing.JTextField();
        titleTxtFldPhysician = new javax.swing.JTextField();
        postalCodeTextFldPhysician = new javax.swing.JTextField();
        cityTxtFldPhysician = new javax.swing.JTextField();
        SteetLblPhysician = new javax.swing.JLabel();
        streetTxtFldPhysician = new javax.swing.JTextField();
        registerbtnPhysician = new keeptoo.KButton();
        phoneLblPhysician = new javax.swing.JLabel();
        phoneTxtFldPhysician = new javax.swing.JTextField();
        specializationComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        registerPatientPanel = new javax.swing.JPanel();
        registerPatientTransparentPnl = new javax.swing.JPanel();
        RegistrationLblPatient = new javax.swing.JLabel();
        emailLblPatient = new javax.swing.JLabel();
        passwordLblPatient = new javax.swing.JLabel();
        eMailTxtFldPatient = new javax.swing.JTextField();
        passwordTxtFldPatient = new javax.swing.JPasswordField();
        registerbtnPatient = new keeptoo.KButton();
        firstNameLblPatient = new javax.swing.JLabel();
        lastNameLblPatient = new javax.swing.JLabel();
        cityLblPatient = new javax.swing.JLabel();
        postalCodeLblPatient = new javax.swing.JLabel();
        dateOfBirthLblPatient = new javax.swing.JLabel();
        TitelLblPatient = new javax.swing.JLabel();
        housenumberLblPatient = new javax.swing.JLabel();
        firstNameTxtFldPatient = new javax.swing.JTextField();
        lastNameTxtFldPatient = new javax.swing.JTextField();
        houseNummberTxtFldPatient = new javax.swing.JTextField();
        AddressTxtFld1 = new javax.swing.JTextField();
        postalCodeTextFldPatient = new javax.swing.JTextField();
        dateOfBirthTxtFldPatient = new javax.swing.JTextField();
        titleTxtFldPatient = new javax.swing.JTextField();
        SteetLblPatient = new javax.swing.JLabel();
        streetTxtFldPatient = new javax.swing.JTextField();
        phoneLbl = new javax.swing.JLabel();
        phoneTxtfld = new javax.swing.JTextField();
        registrationPatientBackBtn1 = new keeptoo.KButton();
        insuranceLblPatient = new javax.swing.JLabel();
        weightLblPatient = new javax.swing.JLabel();
        weightTxtFldPatient = new javax.swing.JTextField();
        InsuranceComboBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        resetPassPanel = new javax.swing.JPanel();
        resetPasswordTransparentPnl = new javax.swing.JPanel();
        resetPassLbl = new javax.swing.JLabel();
        odlPassLbl = new javax.swing.JLabel();
        newPassLbl = new javax.swing.JLabel();
        oldPassTxtfld = new javax.swing.JTextField();
        resetBtn = new keeptoo.KButton();
        newPassTxtfld = new javax.swing.JTextField();
        repeatPass = new javax.swing.JLabel();
        repeatPassTxtfld = new javax.swing.JTextField();
        registrationForgottBackBtn2 = new keeptoo.KButton();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        transparentLoginPanel.setBackground(new java.awt.Color(0, 0, 0,150));

        loginLbl.setFont(new java.awt.Font("Californian FB", 2, 48)); // NOI18N
        loginLbl.setForeground(new java.awt.Color(255, 255, 255));
        loginLbl.setText("Login");

        userEmailLoginLbl.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        userEmailLoginLbl.setForeground(new java.awt.Color(255, 255, 255));
        userEmailLoginLbl.setText("User name");

        passwordLblLogin.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        passwordLblLogin.setForeground(new java.awt.Color(255, 255, 255));
        passwordLblLogin.setText("Password");

        logintBtn.setBorder(null);
        logintBtn.setText("Login");
        logintBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        logintBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        logintBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        logintBtn.setkHoverStartColor(new java.awt.Color(0, 102, 204));
        logintBtn.setkPressedColor(new java.awt.Color(0, 102, 204));
        logintBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        logintBtn.setkStartColor(new java.awt.Color(0, 102, 204));
        logintBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logintBtnActionPerformed(evt);
            }
        });

        newRegistrationLbl.setForeground(new java.awt.Color(255, 255, 255));
        newRegistrationLbl.setText("Register as Patient");
        newRegistrationLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newRegistrationLblMouseClicked(evt);
            }
        });

        forgotPassLbl.setForeground(new java.awt.Color(255, 255, 255));
        forgotPassLbl.setText("Forgot password");
        forgotPassLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotPassLblMouseClicked(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Register as Physician");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout transparentLoginPanelLayout = new javax.swing.GroupLayout(transparentLoginPanel);
        transparentLoginPanel.setLayout(transparentLoginPanelLayout);
        transparentLoginPanelLayout.setHorizontalGroup(
                transparentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(transparentLoginPanelLayout.createSequentialGroup()
                                .addGroup(transparentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(transparentLoginPanelLayout.createSequentialGroup()
                                                .addGap(143, 143, 143)
                                                .addComponent(loginLbl))
                                        .addGroup(transparentLoginPanelLayout.createSequentialGroup()
                                                .addGap(60, 60, 60)
                                                .addGroup(transparentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(passwordLblLogin)
                                                        .addGroup(transparentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addGroup(transparentLoginPanelLayout.createSequentialGroup()
                                                                        .addGroup(transparentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(newRegistrationLbl)
                                                                                .addComponent(jLabel1)
                                                                                .addComponent(forgotPassLbl))
                                                                        .addGap(84, 84, 84))
                                                                .addGroup(transparentLoginPanelLayout.createSequentialGroup()
                                                                        .addComponent(userEmailLoginLbl)
                                                                        .addGap(67, 67, 67)
                                                                        .addGroup(transparentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(logintBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGroup(transparentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                        .addComponent(userEmailLoginTxdFld, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                                                                        .addComponent(jPasswordField1))))))))
                                .addContainerGap(52, Short.MAX_VALUE))
        );
        transparentLoginPanelLayout.setVerticalGroup(
                transparentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(transparentLoginPanelLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(loginLbl)
                                .addGap(55, 55, 55)
                                .addGroup(transparentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(userEmailLoginLbl)
                                        .addComponent(userEmailLoginTxdFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(transparentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(passwordLblLogin)
                                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addComponent(logintBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(newRegistrationLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(forgotPassLbl)
                                .addContainerGap(38, Short.MAX_VALUE))
        );

        loginPanel.add(transparentLoginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 400, 420));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/loginpic3.png"))); // NOI18N
        loginPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 892, 604));

        getContentPane().add(loginPanel, "card2");

        registerPhysicianPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registerPhysicainTransparentPnl1.setBackground(new java.awt.Color(0, 0, 0,150));

        RegistrationLblPhysician.setFont(new java.awt.Font("Californian FB", 2, 48)); // NOI18N
        RegistrationLblPhysician.setForeground(new java.awt.Color(255, 255, 255));
        RegistrationLblPhysician.setText("Registration");

        emailLblPhysician.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        emailLblPhysician.setForeground(new java.awt.Color(255, 255, 255));
        emailLblPhysician.setText("Email");

        passwordLblPhysician.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        passwordLblPhysician.setForeground(new java.awt.Color(255, 255, 255));
        passwordLblPhysician.setText("Password");

        registrationPhysicinaBackBtn.setBorder(null);
        registrationPhysicinaBackBtn.setText("Back");
        registrationPhysicinaBackBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        registrationPhysicinaBackBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        registrationPhysicinaBackBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        registrationPhysicinaBackBtn.setkHoverStartColor(new java.awt.Color(0, 102, 204));
        registrationPhysicinaBackBtn.setkPressedColor(new java.awt.Color(0, 102, 204));
        registrationPhysicinaBackBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        registrationPhysicinaBackBtn.setkStartColor(new java.awt.Color(0, 102, 204));
        registrationPhysicinaBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationPhysicinaBackBtnActionPerformed(evt);
            }
        });

        firstNameLblPhysician.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        firstNameLblPhysician.setForeground(new java.awt.Color(255, 255, 255));
        firstNameLblPhysician.setText("Frist name");

        lastNameLblPhysician.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        lastNameLblPhysician.setForeground(new java.awt.Color(255, 255, 255));
        lastNameLblPhysician.setText("Last name");

        titleLblPhysician.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        titleLblPhysician.setForeground(new java.awt.Color(255, 255, 255));
        titleLblPhysician.setText("Title");

        postalCodeLblPhysician.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        postalCodeLblPhysician.setForeground(new java.awt.Color(255, 255, 255));
        postalCodeLblPhysician.setText("Postal code");

        cityLblPhysician.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        cityLblPhysician.setForeground(new java.awt.Color(255, 255, 255));
        cityLblPhysician.setText("City");

        specializationLblPhysician.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        specializationLblPhysician.setForeground(new java.awt.Color(255, 255, 255));
        specializationLblPhysician.setText("Specialization");

        housenumberLblPhysician.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        housenumberLblPhysician.setForeground(new java.awt.Color(255, 255, 255));
        housenumberLblPhysician.setText("House number");

        cityTxtFldPhysician.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityTxtFldPhysicianActionPerformed(evt);
            }
        });

        SteetLblPhysician.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        SteetLblPhysician.setForeground(new java.awt.Color(255, 255, 255));
        SteetLblPhysician.setText("Street");

        registerbtnPhysician.setBorder(null);
        registerbtnPhysician.setText("Register");
        registerbtnPhysician.setkEndColor(new java.awt.Color(255, 255, 255));
        registerbtnPhysician.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        registerbtnPhysician.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        registerbtnPhysician.setkHoverStartColor(new java.awt.Color(0, 102, 204));
        registerbtnPhysician.setkPressedColor(new java.awt.Color(0, 102, 204));
        registerbtnPhysician.setkSelectedColor(new java.awt.Color(255, 255, 255));
        registerbtnPhysician.setkStartColor(new java.awt.Color(0, 102, 204));

        phoneLblPhysician.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        phoneLblPhysician.setForeground(new java.awt.Color(255, 255, 255));
        phoneLblPhysician.setText("Phone");

        specializationComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Allgemeinmedizin", "Anästhesiologie", "Anatomie", "Arbeitsmedizin", "Augenheilkunde", "Biochemie", "Chirurgie", "Chirurgie_Allgemeine Chirurgie", "Forensische Psychiatrie", "Frauenheilkunde und Geburtshilfe", "Gefäßchirurgie", "Gynäkologische Onkologie", "Hals-Nasen-Ohrenheilkunde", "Haut- und Geschlechtskrankheiten", "Herzchirurgie", "Humangenetik", "Hygiene und Umweltmedizin", "Innere Medizin ", "Innere Medizin und Endokrinologie und Diabetologie", "Innere Medizin und Gastroenterologie", "Innere Medizin und Hämatologie und Onkologie", "Innere Medizin und Kardiologie", "Innere Medizin und Nephrologie", "Innere Medizin und Pneumologie", "Innere Medizin und Rheumatologie", "Kinder- und Jugendmedizin", "Kinder- und Jugendpsychiatrie und -psychotherapie", "Kinderchirurgie", "Kinderradiologie", "Klinische Pharmakologie", "Laboratoriumsmedizin", "Mikrobiologie, Virologie und Infektionsepidemiologie", "Mund-Kiefer-Gesichtschirurgie", "Neurochirurgie", "Neurologie", "Neuroradiologie", "Nuklearmedizin", "Orthopädie und Unfallchirurgie", "Pathologie ", "Pharmakologie und Toxikologie", "Phoniatrie und Pädaudiologie", "Physikalische und Rehabilitative Medizin", "Physiologie", "Plastische, Rekonstruktive und Ästhetische Chirurgie", "Psychiatrie und Psychotherapie", "Psychosomatische Medizin und Psychotherapie", "Radiologie", "Rechtsmedizin", "SP Gynäkologische Endokrinologie und Reproduktionsmedizin", "SP Kinder-Hämatologie und -Onkologie", "SP Kinder-Kardiologie", "SP Neonatologie", "SP Neuropädiatrie", "Spezielle Geburtshilfe und Perinatalmedizin", "Strahlentherapie", "Thoraxchirurgie", "Transfusionsmedizin", "Urologie", "Viszeralchirurgie", "Innere Medizin und Angiologie", "Öffentliches Gesundheitswesen", " ", " ", " " }));

        javax.swing.GroupLayout registerPhysicainTransparentPnl1Layout = new javax.swing.GroupLayout(registerPhysicainTransparentPnl1);
        registerPhysicainTransparentPnl1.setLayout(registerPhysicainTransparentPnl1Layout);
        registerPhysicainTransparentPnl1Layout.setHorizontalGroup(
                registerPhysicainTransparentPnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(registerPhysicainTransparentPnl1Layout.createSequentialGroup()
                                .addGroup(registerPhysicainTransparentPnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(registerPhysicainTransparentPnl1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(registrationPhysicinaBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(33, 33, 33)
                                                .addComponent(registerbtnPhysician, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(registerPhysicainTransparentPnl1Layout.createSequentialGroup()
                                                .addGap(113, 113, 113)
                                                .addComponent(RegistrationLblPhysician))
                                        .addGroup(registerPhysicainTransparentPnl1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(registerPhysicainTransparentPnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(registerPhysicainTransparentPnl1Layout.createSequentialGroup()
                                                                .addGroup(registerPhysicainTransparentPnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(titleLblPhysician)
                                                                        .addComponent(housenumberLblPhysician)
                                                                        .addComponent(emailLblPhysician, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(passwordLblPhysician, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(SteetLblPhysician, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(lastNameLblPhysician)
                                                                        .addComponent(phoneLblPhysician)
                                                                        .addComponent(cityLblPhysician, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(registerPhysicainTransparentPnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                                .addComponent(specializationLblPhysician, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(postalCodeLblPhysician, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                                .addGap(28, 28, 28))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPhysicainTransparentPnl1Layout.createSequentialGroup()
                                                                .addComponent(firstNameLblPhysician, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(48, 48, 48)))
                                                .addGroup(registerPhysicainTransparentPnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(lastNameTxtFldPhysician, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(streetTxtFldPhysician, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(houseNummberTxtfldPhysician, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(titleTxtFldPhysician, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(postalCodeTextFldPhysician, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(phoneTxtFldPhysician, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(cityTxtFldPhysician, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(emailTxtPhysician, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(specializationComboBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(firstNameTxtFldPhysician)
                                                        .addComponent(passwordTxtFldPhysician, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 128, Short.MAX_VALUE))
        );
        registerPhysicainTransparentPnl1Layout.setVerticalGroup(
                registerPhysicainTransparentPnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(registerPhysicainTransparentPnl1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(RegistrationLblPhysician)
                                .addGap(5, 5, 5)
                                .addGroup(registerPhysicainTransparentPnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(phoneTxtFldPhysician, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(registerPhysicainTransparentPnl1Layout.createSequentialGroup()
                                                .addGroup(registerPhysicainTransparentPnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(firstNameTxtFldPhysician, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(firstNameLblPhysician))
                                                .addGap(10, 10, 10)
                                                .addGroup(registerPhysicainTransparentPnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lastNameLblPhysician)
                                                        .addComponent(lastNameTxtFldPhysician, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(registerPhysicainTransparentPnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(streetTxtFldPhysician, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(SteetLblPhysician))
                                                .addGap(12, 12, 12)
                                                .addGroup(registerPhysicainTransparentPnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(houseNummberTxtfldPhysician, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(housenumberLblPhysician))
                                                .addGap(13, 13, 13)
                                                .addGroup(registerPhysicainTransparentPnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(titleLblPhysician)
                                                        .addComponent(titleTxtFldPhysician, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(registerPhysicainTransparentPnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(postalCodeLblPhysician)
                                                        .addComponent(postalCodeTextFldPhysician, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(phoneLblPhysician)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(registerPhysicainTransparentPnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cityLblPhysician)
                                        .addComponent(cityTxtFldPhysician, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(registerPhysicainTransparentPnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(specializationLblPhysician)
                                        .addComponent(specializationComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(registerPhysicainTransparentPnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(emailLblPhysician)
                                        .addComponent(emailTxtPhysician, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(registerPhysicainTransparentPnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(passwordLblPhysician)
                                        .addComponent(passwordTxtFldPhysician, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(registerPhysicainTransparentPnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(registerbtnPhysician, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(registrationPhysicinaBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(110, Short.MAX_VALUE))
        );

        registerPhysicianPanel.add(registerPhysicainTransparentPnl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 400, 570));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/loginpic3.png"))); // NOI18N
        registerPhysicianPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 892, 604));

        getContentPane().add(registerPhysicianPanel, "card2");

        registerPatientPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registerPatientTransparentPnl.setBackground(new java.awt.Color(0, 0, 0,150));
        registerPatientTransparentPnl.setPreferredSize(new java.awt.Dimension(364, 600));

        RegistrationLblPatient.setFont(new java.awt.Font("Californian FB", 2, 36)); // NOI18N
        RegistrationLblPatient.setForeground(new java.awt.Color(255, 255, 255));
        RegistrationLblPatient.setText("Registration");

        emailLblPatient.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        emailLblPatient.setForeground(new java.awt.Color(255, 255, 255));
        emailLblPatient.setText("Email");

        passwordLblPatient.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        passwordLblPatient.setForeground(new java.awt.Color(255, 255, 255));
        passwordLblPatient.setText("Password");

        registerbtnPatient.setBorder(null);
        registerbtnPatient.setText("Register");
        registerbtnPatient.setkEndColor(new java.awt.Color(255, 255, 255));
        registerbtnPatient.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        registerbtnPatient.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        registerbtnPatient.setkHoverStartColor(new java.awt.Color(0, 102, 204));
        registerbtnPatient.setkPressedColor(new java.awt.Color(0, 102, 204));
        registerbtnPatient.setkSelectedColor(new java.awt.Color(255, 255, 255));
        registerbtnPatient.setkStartColor(new java.awt.Color(0, 102, 204));

        firstNameLblPatient.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        firstNameLblPatient.setForeground(new java.awt.Color(255, 255, 255));
        firstNameLblPatient.setText("Frist name");

        lastNameLblPatient.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        lastNameLblPatient.setForeground(new java.awt.Color(255, 255, 255));
        lastNameLblPatient.setText("Last name");

        cityLblPatient.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        cityLblPatient.setForeground(new java.awt.Color(255, 255, 255));
        cityLblPatient.setText("City");

        postalCodeLblPatient.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        postalCodeLblPatient.setForeground(new java.awt.Color(255, 255, 255));
        postalCodeLblPatient.setText("Postal code");

        dateOfBirthLblPatient.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        dateOfBirthLblPatient.setForeground(new java.awt.Color(255, 255, 255));
        dateOfBirthLblPatient.setText("Date of birth");

        TitelLblPatient.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        TitelLblPatient.setForeground(new java.awt.Color(255, 255, 255));
        TitelLblPatient.setText("Title");

        housenumberLblPatient.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        housenumberLblPatient.setForeground(new java.awt.Color(255, 255, 255));
        housenumberLblPatient.setText("House number");

        postalCodeTextFldPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postalCodeTextFldPatientActionPerformed(evt);
            }
        });

        SteetLblPatient.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        SteetLblPatient.setForeground(new java.awt.Color(255, 255, 255));
        SteetLblPatient.setText("Street");

        phoneLbl.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        phoneLbl.setForeground(new java.awt.Color(255, 255, 255));
        phoneLbl.setText("Phone");

        registrationPatientBackBtn1.setBorder(null);
        registrationPatientBackBtn1.setText("Back");
        registrationPatientBackBtn1.setkEndColor(new java.awt.Color(255, 255, 255));
        registrationPatientBackBtn1.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        registrationPatientBackBtn1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        registrationPatientBackBtn1.setkHoverStartColor(new java.awt.Color(0, 102, 204));
        registrationPatientBackBtn1.setkPressedColor(new java.awt.Color(0, 102, 204));
        registrationPatientBackBtn1.setkSelectedColor(new java.awt.Color(255, 255, 255));
        registrationPatientBackBtn1.setkStartColor(new java.awt.Color(0, 102, 204));
        registrationPatientBackBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationPatientBackBtn1ActionPerformed(evt);
            }
        });

        insuranceLblPatient.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        insuranceLblPatient.setForeground(new java.awt.Color(255, 255, 255));
        insuranceLblPatient.setText("Insurance");

        weightLblPatient.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        weightLblPatient.setForeground(new java.awt.Color(255, 255, 255));
        weightLblPatient.setText("Weight");

        InsuranceComboBox.setForeground(new java.awt.Color(255, 255, 255));
        InsuranceComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AOK", "KKH", "TK", "Allianz" }));

        javax.swing.GroupLayout registerPatientTransparentPnlLayout = new javax.swing.GroupLayout(registerPatientTransparentPnl);
        registerPatientTransparentPnl.setLayout(registerPatientTransparentPnlLayout);
        registerPatientTransparentPnlLayout.setHorizontalGroup(
                registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPatientTransparentPnlLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(RegistrationLblPatient)
                                .addGap(101, 101, 101))
                        .addGroup(registerPatientTransparentPnlLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(registerPatientTransparentPnlLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(registrationPatientBackBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(registerbtnPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, registerPatientTransparentPnlLayout.createSequentialGroup()
                                                .addGroup(registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(cityLblPatient)
                                                        .addComponent(housenumberLblPatient))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(AddressTxtFld1)
                                                        .addComponent(houseNummberTxtFldPatient, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, registerPatientTransparentPnlLayout.createSequentialGroup()
                                                .addComponent(passwordLblPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(passwordTxtFldPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, registerPatientTransparentPnlLayout.createSequentialGroup()
                                                .addComponent(phoneLbl)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(phoneTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, registerPatientTransparentPnlLayout.createSequentialGroup()
                                                .addComponent(emailLblPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(eMailTxtFldPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, registerPatientTransparentPnlLayout.createSequentialGroup()
                                                .addComponent(TitelLblPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(titleTxtFldPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, registerPatientTransparentPnlLayout.createSequentialGroup()
                                                .addComponent(lastNameLblPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lastNameTxtFldPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, registerPatientTransparentPnlLayout.createSequentialGroup()
                                                .addComponent(firstNameLblPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(firstNameTxtFldPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(registerPatientTransparentPnlLayout.createSequentialGroup()
                                                .addGroup(registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(insuranceLblPatient)
                                                        .addComponent(weightLblPatient))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(weightTxtFldPatient, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                                        .addComponent(InsuranceComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, registerPatientTransparentPnlLayout.createSequentialGroup()
                                                .addComponent(SteetLblPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(streetTxtFldPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, registerPatientTransparentPnlLayout.createSequentialGroup()
                                                .addGroup(registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(registerPatientTransparentPnlLayout.createSequentialGroup()
                                                                .addComponent(postalCodeLblPatient)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGroup(registerPatientTransparentPnlLayout.createSequentialGroup()
                                                                .addComponent(dateOfBirthLblPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGap(62, 62, 62)))
                                                .addGroup(registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(postalCodeTextFldPatient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(dateOfBirthTxtFldPatient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(55, 55, 55))
        );
        registerPatientTransparentPnlLayout.setVerticalGroup(
                registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(registerPatientTransparentPnlLayout.createSequentialGroup()
                                .addComponent(RegistrationLblPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(firstNameLblPatient)
                                        .addComponent(firstNameTxtFldPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lastNameLblPatient)
                                        .addComponent(lastNameTxtFldPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(SteetLblPatient)
                                        .addComponent(streetTxtFldPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(housenumberLblPatient)
                                        .addComponent(houseNummberTxtFldPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(AddressTxtFld1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cityLblPatient))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(insuranceLblPatient)
                                        .addComponent(InsuranceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(weightLblPatient)
                                        .addComponent(weightTxtFldPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(postalCodeLblPatient)
                                        .addComponent(postalCodeTextFldPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(dateOfBirthLblPatient)
                                        .addComponent(dateOfBirthTxtFldPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(TitelLblPatient)
                                        .addComponent(titleTxtFldPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(emailLblPatient)
                                        .addComponent(eMailTxtFldPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(phoneLbl)
                                        .addComponent(phoneTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(passwordLblPatient)
                                        .addComponent(passwordTxtFldPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(registrationPatientBackBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(registerbtnPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(171, Short.MAX_VALUE))
        );

        registerPatientPanel.add(registerPatientTransparentPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 400, 520));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/loginpic3.png"))); // NOI18N
        registerPatientPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 892, 604));

        getContentPane().add(registerPatientPanel, "card2");

        resetPassPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resetPasswordTransparentPnl.setBackground(new java.awt.Color(0, 0, 0,150));

        resetPassLbl.setFont(new java.awt.Font("Californian FB", 2, 48)); // NOI18N
        resetPassLbl.setForeground(new java.awt.Color(255, 255, 255));
        resetPassLbl.setText("Reset your password");

        odlPassLbl.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        odlPassLbl.setForeground(new java.awt.Color(255, 255, 255));
        odlPassLbl.setText("Old password:");

        newPassLbl.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        newPassLbl.setForeground(new java.awt.Color(255, 255, 255));
        newPassLbl.setText("New  password");

        resetBtn.setBorder(null);
        resetBtn.setText("Reset");
        resetBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        resetBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        resetBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        resetBtn.setkHoverStartColor(new java.awt.Color(0, 102, 204));
        resetBtn.setkPressedColor(new java.awt.Color(0, 102, 204));
        resetBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        resetBtn.setkStartColor(new java.awt.Color(0, 102, 204));

        repeatPass.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        repeatPass.setForeground(new java.awt.Color(255, 255, 255));
        repeatPass.setText("Repeat password");

        registrationForgottBackBtn2.setBorder(null);
        registrationForgottBackBtn2.setText("Back");
        registrationForgottBackBtn2.setkEndColor(new java.awt.Color(255, 255, 255));
        registrationForgottBackBtn2.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        registrationForgottBackBtn2.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        registrationForgottBackBtn2.setkHoverStartColor(new java.awt.Color(0, 102, 204));
        registrationForgottBackBtn2.setkPressedColor(new java.awt.Color(0, 102, 204));
        registrationForgottBackBtn2.setkSelectedColor(new java.awt.Color(255, 255, 255));
        registrationForgottBackBtn2.setkStartColor(new java.awt.Color(0, 102, 204));
        registrationForgottBackBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationForgottBackBtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout resetPasswordTransparentPnlLayout = new javax.swing.GroupLayout(resetPasswordTransparentPnl);
        resetPasswordTransparentPnl.setLayout(resetPasswordTransparentPnlLayout);
        resetPasswordTransparentPnlLayout.setHorizontalGroup(
                resetPasswordTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(resetPasswordTransparentPnlLayout.createSequentialGroup()
                                .addGroup(resetPasswordTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(resetPasswordTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(resetPasswordTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(resetPasswordTransparentPnlLayout.createSequentialGroup()
                                                                .addGap(60, 60, 60)
                                                                .addGroup(resetPasswordTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(resetPasswordTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resetPasswordTransparentPnlLayout.createSequentialGroup()
                                                                                        .addComponent(odlPassLbl)
                                                                                        .addGap(83, 83, 83))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resetPasswordTransparentPnlLayout.createSequentialGroup()
                                                                                        .addComponent(newPassLbl)
                                                                                        .addGap(76, 76, 76)))
                                                                        .addGroup(resetPasswordTransparentPnlLayout.createSequentialGroup()
                                                                                .addComponent(repeatPass)
                                                                                .addGap(64, 64, 64)))
                                                                .addGroup(resetPasswordTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(oldPassTxtfld, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                                                        .addComponent(newPassTxtfld)
                                                                        .addComponent(repeatPassTxtfld)))
                                                        .addGroup(resetPasswordTransparentPnlLayout.createSequentialGroup()
                                                                .addGap(36, 36, 36)
                                                                .addComponent(resetPassLbl))))
                                        .addGroup(resetPasswordTransparentPnlLayout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(registrationForgottBackBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(25, Short.MAX_VALUE))
        );
        resetPasswordTransparentPnlLayout.setVerticalGroup(
                resetPasswordTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(resetPasswordTransparentPnlLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(resetPassLbl)
                                .addGap(59, 59, 59)
                                .addGroup(resetPasswordTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(odlPassLbl)
                                        .addComponent(oldPassTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(resetPasswordTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(newPassLbl)
                                        .addComponent(newPassTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(resetPasswordTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(repeatPass)
                                        .addComponent(repeatPassTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(resetPasswordTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(resetBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(registrationForgottBackBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(78, Short.MAX_VALUE))
        );

        resetPassPanel.add(resetPasswordTransparentPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 400, 420));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/loginpic3.png"))); // NOI18N
        resetPassPanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 890, 620));

        getContentPane().add(resetPassPanel, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void logintBtnActionPerformed(java.awt.event.ActionEvent evt) {
        Databaseconnection databaseconnection = new Databaseconnection();
        String DatabasePw = null;
        try {
            DatabasePw = databaseconnection.getUserPw(userEmailLoginTxdFld.getText());
        } catch (SQLException | ClassNotFoundException sqlException) {
            sqlException.printStackTrace();
        }
        if(DatabasePw == null) {
            JOptionPane.showMessageDialog(loginPanel,"eMail-Address not found", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            String password = String.valueOf(jPasswordField1.getPassword());
            int check = -1;
            while (check == -1) {
                if (evt.getSource() == logintBtn) {
                    if (userEmailLoginTxdFld.getText().equals("") || password.equals("")) {
                        JOptionPane.showMessageDialog(loginPanel, "Fields cannot be empty! Please enter your data.");
                        break;
                    } else if ((org.mindrot.jbcrypt.BCrypt.checkpw(password,DatabasePw))) {
                        JOptionPane.showMessageDialog(loginPanel, "Login successful!");
                        check = 0;
                        new LoginGUI().setVisible(true);
                        dispose();
                    } else {
                        System.out.println(User.hashPassword(password));
                        JOptionPane.showMessageDialog(loginPanel, "Login unsuccessful!", "Error", JOptionPane.ERROR_MESSAGE);
                        break;
                    }
                }
            }

        }
    }

    private void newRegistrationLblMouseClicked(java.awt.event.MouseEvent evt) {
        loginPanel.setVisible(false);
        resetPassPanel.setVisible(false);
        registerPhysicianPanel.setVisible(false);
        registerPatientPanel.setVisible(true);
        // TODO add your handling code here:
    }

    private void forgotPassLblMouseClicked(java.awt.event.MouseEvent evt) {
        loginPanel.setVisible(false);
        registerPhysicianPanel.setVisible(false);
        registerPatientPanel.setVisible(false);
        resetPassPanel.setVisible(true);    // TODO add your handling code here:
    }

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {
        loginPanel.setVisible(false);
        resetPassPanel.setVisible(false);
        registerPatientPanel.setVisible(false);
        registerPhysicianPanel.setVisible(true);
    }

    private void postalCodeTextFldPatientActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void registrationPhysicinaBackBtnActionPerformed(java.awt.event.ActionEvent evt) {
        resetPassPanel.setVisible(false);
        registerPhysicianPanel.setVisible(false);
        registerPatientPanel.setVisible(false);
        loginPanel.setVisible(true);
    }

    private void registrationPatientBackBtn1ActionPerformed(java.awt.event.ActionEvent evt) {
        resetPassPanel.setVisible(false);
        registerPhysicianPanel.setVisible(false);
        registerPatientPanel.setVisible(false);
        loginPanel.setVisible(true);
    }

    private void registrationForgottBackBtn2ActionPerformed(java.awt.event.ActionEvent evt) {
        resetPassPanel.setVisible(false);
        registerPhysicianPanel.setVisible(false);
        registerPatientPanel.setVisible(false);
        loginPanel.setVisible(true);
    }

    private void cityTxtFldPhysicianActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JTextField AddressTxtFld1;
    private javax.swing.JComboBox<String> InsuranceComboBox;
    private javax.swing.JLabel RegistrationLblPatient;
    private javax.swing.JLabel RegistrationLblPhysician;
    private javax.swing.JLabel SteetLblPatient;
    private javax.swing.JLabel SteetLblPhysician;
    private javax.swing.JLabel TitelLblPatient;
    private javax.swing.JLabel cityLblPatient;
    private javax.swing.JLabel cityLblPhysician;
    private javax.swing.JTextField cityTxtFldPhysician;
    private javax.swing.JLabel dateOfBirthLblPatient;
    private javax.swing.JTextField dateOfBirthTxtFldPatient;
    private javax.swing.JTextField eMailTxtFldPatient;
    private javax.swing.JLabel emailLblPatient;
    private javax.swing.JLabel emailLblPhysician;
    private javax.swing.JTextField emailTxtPhysician;
    private javax.swing.JLabel firstNameLblPatient;
    private javax.swing.JLabel firstNameLblPhysician;
    private javax.swing.JTextField firstNameTxtFldPatient;
    private javax.swing.JTextField firstNameTxtFldPhysician;
    private javax.swing.JLabel forgotPassLbl;
    private javax.swing.JTextField houseNummberTxtFldPatient;
    private javax.swing.JTextField houseNummberTxtfldPhysician;
    private javax.swing.JLabel housenumberLblPatient;
    private javax.swing.JLabel housenumberLblPhysician;
    private javax.swing.JLabel insuranceLblPatient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel lastNameLblPatient;
    private javax.swing.JLabel lastNameLblPhysician;
    private javax.swing.JTextField lastNameTxtFldPatient;
    private javax.swing.JTextField lastNameTxtFldPhysician;
    private javax.swing.JLabel loginLbl;
    private javax.swing.JPanel loginPanel;
    private keeptoo.KButton logintBtn;
    private javax.swing.JLabel newPassLbl;
    private javax.swing.JTextField newPassTxtfld;
    private javax.swing.JLabel newRegistrationLbl;
    private javax.swing.JLabel odlPassLbl;
    private javax.swing.JTextField oldPassTxtfld;
    private javax.swing.JLabel passwordLblLogin;
    private javax.swing.JLabel passwordLblPatient;
    private javax.swing.JLabel passwordLblPhysician;
    private javax.swing.JPasswordField passwordTxtFldPatient;
    private javax.swing.JPasswordField passwordTxtFldPhysician;
    private javax.swing.JLabel phoneLbl;
    private javax.swing.JLabel phoneLblPhysician;
    private javax.swing.JTextField phoneTxtFldPhysician;
    private javax.swing.JTextField phoneTxtfld;
    private javax.swing.JLabel postalCodeLblPatient;
    private javax.swing.JLabel postalCodeLblPhysician;
    private javax.swing.JTextField postalCodeTextFldPatient;
    private javax.swing.JTextField postalCodeTextFldPhysician;
    private javax.swing.JPanel registerPatientPanel;
    private javax.swing.JPanel registerPatientTransparentPnl;
    private javax.swing.JPanel registerPhysicainTransparentPnl1;
    private javax.swing.JPanel registerPhysicianPanel;
    private keeptoo.KButton registerbtnPatient;
    private keeptoo.KButton registerbtnPhysician;
    private keeptoo.KButton registrationForgottBackBtn2;
    private keeptoo.KButton registrationPatientBackBtn1;
    private keeptoo.KButton registrationPhysicinaBackBtn;
    private javax.swing.JLabel repeatPass;
    private javax.swing.JTextField repeatPassTxtfld;
    private keeptoo.KButton resetBtn;
    private javax.swing.JLabel resetPassLbl;
    private javax.swing.JPanel resetPassPanel;
    private javax.swing.JPanel resetPasswordTransparentPnl;
    private javax.swing.JComboBox<String> specializationComboBox1;
    private javax.swing.JLabel specializationLblPhysician;
    private javax.swing.JTextField streetTxtFldPatient;
    private javax.swing.JTextField streetTxtFldPhysician;
    private javax.swing.JLabel titleLblPhysician;
    private javax.swing.JTextField titleTxtFldPatient;
    private javax.swing.JTextField titleTxtFldPhysician;
    private javax.swing.JPanel transparentLoginPanel;
    private javax.swing.JLabel userEmailLoginLbl;
    private javax.swing.JTextField userEmailLoginTxdFld;
    private javax.swing.JLabel weightLblPatient;
    private javax.swing.JTextField weightTxtFldPatient;
    // End of variables declaration
}
