/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import javax.swing.*;
import java.sql.SQLException;

/**
 *
 * @author Amar
 */
public class LoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form loginV2
     */
    public LoginGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        transparentLoginPanel = new javax.swing.JPanel();
        loginLbl = new javax.swing.JLabel();
        userNameLbl = new javax.swing.JLabel();
        passwordLbl = new javax.swing.JLabel();
        userNameTexFld = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        logintBtn = new keeptoo.KButton();
        newRegistrationLbl = new javax.swing.JLabel();
        forgotPassLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        registerPhysicianPanel = new javax.swing.JPanel();
        registerPhysicainTransparentPnl1 = new javax.swing.JPanel();
        RegistrationLbl2 = new javax.swing.JLabel();
        EmailLbl2 = new javax.swing.JLabel();
        passLbl2 = new javax.swing.JLabel();
        eamilTexFld = new javax.swing.JTextField();
        passwordTxtFld2 = new javax.swing.JPasswordField();
        registrationPhysicinaBackBtn = new keeptoo.KButton();
        firstNameLbl2 = new javax.swing.JLabel();
        lastNameLbl2 = new javax.swing.JLabel();
        addressLbl2 = new javax.swing.JLabel();
        postalCodeLbl1 = new javax.swing.JLabel();
        cityLbl2 = new javax.swing.JLabel();
        TitelLbl2 = new javax.swing.JLabel();
        dateOfBirthLbl2 = new javax.swing.JLabel();
        firstNameTxtFld2 = new javax.swing.JTextField();
        lastNameTxtFld2 = new javax.swing.JTextField();
        houseNummberTxtfld1 = new javax.swing.JTextField();
        AddressTxtFld2 = new javax.swing.JTextField();
        postalCodeTextFld1 = new javax.swing.JTextField();
        phoneTxtFld2 = new javax.swing.JTextField();
        titleTxtFld2 = new javax.swing.JTextField();
        SteetLbl1 = new javax.swing.JLabel();
        streetTxtFld1 = new javax.swing.JTextField();
        registerbtn3 = new keeptoo.KButton();
        jLabel9 = new javax.swing.JLabel();
        registerPatientPanel = new javax.swing.JPanel();
        registerPatientTransparentPnl = new javax.swing.JPanel();
        RegistrationLbl1 = new javax.swing.JLabel();
        emailLbl = new javax.swing.JLabel();
        passLbl1 = new javax.swing.JLabel();
        eMailTxtFld1 = new javax.swing.JTextField();
        passwordTxtFld1 = new javax.swing.JPasswordField();
        registerbtn1 = new keeptoo.KButton();
        firstNameLbl1 = new javax.swing.JLabel();
        lastNameLbl1 = new javax.swing.JLabel();
        addressLbl1 = new javax.swing.JLabel();
        postalCodeLbl = new javax.swing.JLabel();
        phoneLbl1 = new javax.swing.JLabel();
        TitelLbl1 = new javax.swing.JLabel();
        dateOfBirthLbl1 = new javax.swing.JLabel();
        firstNameTxtFld1 = new javax.swing.JTextField();
        lastNameTxtFld1 = new javax.swing.JTextField();
        houseNummberTxtfld = new javax.swing.JTextField();
        AddressTxtFld1 = new javax.swing.JTextField();
        postalCodeTextFld = new javax.swing.JTextField();
        phoneTxtFld1 = new javax.swing.JTextField();
        titleTxtFld1 = new javax.swing.JTextField();
        SteetLbl = new javax.swing.JLabel();
        streetTxtFld = new javax.swing.JTextField();
        phoneLbl = new javax.swing.JLabel();
        phoneTxtfld = new javax.swing.JTextField();
        registrationPatientBackBtn1 = new keeptoo.KButton();
        jLabel10 = new javax.swing.JLabel();
        resetPassPanel = new javax.swing.JPanel();
        resetPasswordTransparentPnl = new javax.swing.JPanel();
        resetPassLbl = new javax.swing.JLabel();
        odlPassLbl = new javax.swing.JLabel();
        newPassLbl = new javax.swing.JLabel();
        oldPassTxtfld = new javax.swing.JTextField();
        resetBtn = new keeptoo.KButton();
        newPassTxtfld = new javax.swing.JTextField();
        repeatPass = new javax.swing.JLabel();
        repeatPassTxtfld = new javax.swing.JTextField();
        registrationForgottBackBtn2 = new keeptoo.KButton();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        transparentLoginPanel.setBackground(new java.awt.Color(0, 0, 0,150));

        loginLbl.setFont(new java.awt.Font("Californian FB", 2, 48)); // NOI18N
        loginLbl.setForeground(new java.awt.Color(255, 255, 255));
        loginLbl.setText("Login");

        userNameLbl.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        userNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        userNameLbl.setText("User name");

        passwordLbl.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        passwordLbl.setForeground(new java.awt.Color(255, 255, 255));
        passwordLbl.setText("Password");

        logintBtn.setBorder(null);
        logintBtn.setText("Login");
        logintBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        logintBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        logintBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        logintBtn.setkHoverStartColor(new java.awt.Color(0, 102, 204));
        logintBtn.setkPressedColor(new java.awt.Color(0, 102, 204));
        logintBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        logintBtn.setkStartColor(new java.awt.Color(0, 102, 204));
        logintBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    logintBtnActionPerformed(evt);
                } catch (SQLException | ClassNotFoundException throwables) {
                    throwables.printStackTrace();
                }
            }
        });

        newRegistrationLbl.setForeground(new java.awt.Color(255, 255, 255));
        newRegistrationLbl.setText("Register as Patient");
        newRegistrationLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newRegistrationLblMouseClicked(evt);
            }
        });

        forgotPassLbl.setForeground(new java.awt.Color(255, 255, 255));
        forgotPassLbl.setText("Forgot password");
        forgotPassLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotPassLblMouseClicked(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Register as Physician");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout transparentLoginPanelLayout = new javax.swing.GroupLayout(transparentLoginPanel);
        transparentLoginPanel.setLayout(transparentLoginPanelLayout);
        transparentLoginPanelLayout.setHorizontalGroup(
                transparentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(transparentLoginPanelLayout.createSequentialGroup()
                                .addGroup(transparentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(transparentLoginPanelLayout.createSequentialGroup()
                                                .addGap(143, 143, 143)
                                                .addComponent(loginLbl))
                                        .addGroup(transparentLoginPanelLayout.createSequentialGroup()
                                                .addGap(60, 60, 60)
                                                .addGroup(transparentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(passwordLbl)
                                                        .addGroup(transparentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addGroup(transparentLoginPanelLayout.createSequentialGroup()
                                                                        .addGroup(transparentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(newRegistrationLbl)
                                                                                .addComponent(jLabel1)
                                                                                .addComponent(forgotPassLbl))
                                                                        .addGap(84, 84, 84))
                                                                .addGroup(transparentLoginPanelLayout.createSequentialGroup()
                                                                        .addComponent(userNameLbl)
                                                                        .addGap(67, 67, 67)
                                                                        .addGroup(transparentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(logintBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGroup(transparentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                        .addComponent(userNameTexFld, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                                                                        .addComponent(jPasswordField1))))))))
                                .addContainerGap(52, Short.MAX_VALUE))
        );
        transparentLoginPanelLayout.setVerticalGroup(
                transparentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(transparentLoginPanelLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(loginLbl)
                                .addGap(55, 55, 55)
                                .addGroup(transparentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(userNameLbl)
                                        .addComponent(userNameTexFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(transparentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(passwordLbl)
                                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addComponent(logintBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(newRegistrationLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(forgotPassLbl)
                                .addContainerGap(38, Short.MAX_VALUE))
        );

        loginPanel.add(transparentLoginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 400, 420));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/loginpic3.png"))); // NOI18N
        loginPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 892, 604));

        getContentPane().add(loginPanel, "card2");

        registerPhysicianPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registerPhysicainTransparentPnl1.setBackground(new java.awt.Color(0, 0, 0,150));

        RegistrationLbl2.setFont(new java.awt.Font("Californian FB", 2, 48)); // NOI18N
        RegistrationLbl2.setForeground(new java.awt.Color(255, 255, 255));
        RegistrationLbl2.setText("Registration");

        EmailLbl2.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        EmailLbl2.setForeground(new java.awt.Color(255, 255, 255));
        EmailLbl2.setText("Email");

        passLbl2.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        passLbl2.setForeground(new java.awt.Color(255, 255, 255));
        passLbl2.setText("Password");

        registrationPhysicinaBackBtn.setBorder(null);
        registrationPhysicinaBackBtn.setText("Back");
        registrationPhysicinaBackBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        registrationPhysicinaBackBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        registrationPhysicinaBackBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        registrationPhysicinaBackBtn.setkHoverStartColor(new java.awt.Color(0, 102, 204));
        registrationPhysicinaBackBtn.setkPressedColor(new java.awt.Color(0, 102, 204));
        registrationPhysicinaBackBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        registrationPhysicinaBackBtn.setkStartColor(new java.awt.Color(0, 102, 204));
        registrationPhysicinaBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationPhysicinaBackBtnActionPerformed(evt);
            }
        });

        firstNameLbl2.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        firstNameLbl2.setForeground(new java.awt.Color(255, 255, 255));
        firstNameLbl2.setText("Frist name");

        lastNameLbl2.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        lastNameLbl2.setForeground(new java.awt.Color(255, 255, 255));
        lastNameLbl2.setText("Last name");

        addressLbl2.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        addressLbl2.setForeground(new java.awt.Color(255, 255, 255));
        addressLbl2.setText("Address");

        postalCodeLbl1.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        postalCodeLbl1.setForeground(new java.awt.Color(255, 255, 255));
        postalCodeLbl1.setText("Postal code");

        cityLbl2.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        cityLbl2.setForeground(new java.awt.Color(255, 255, 255));
        cityLbl2.setText("City");

        TitelLbl2.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        TitelLbl2.setForeground(new java.awt.Color(255, 255, 255));
        TitelLbl2.setText("Specialization");

        dateOfBirthLbl2.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        dateOfBirthLbl2.setForeground(new java.awt.Color(255, 255, 255));
        dateOfBirthLbl2.setText("House number");

        SteetLbl1.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        SteetLbl1.setForeground(new java.awt.Color(255, 255, 255));
        SteetLbl1.setText("Street");

        registerbtn3.setBorder(null);
        registerbtn3.setText("Register");
        registerbtn3.setkEndColor(new java.awt.Color(255, 255, 255));
        registerbtn3.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        registerbtn3.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        registerbtn3.setkHoverStartColor(new java.awt.Color(0, 102, 204));
        registerbtn3.setkPressedColor(new java.awt.Color(0, 102, 204));
        registerbtn3.setkSelectedColor(new java.awt.Color(255, 255, 255));
        registerbtn3.setkStartColor(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout registerPhysicainTransparentPnl1Layout = new javax.swing.GroupLayout(registerPhysicainTransparentPnl1);
        registerPhysicainTransparentPnl1.setLayout(registerPhysicainTransparentPnl1Layout);
        registerPhysicainTransparentPnl1Layout.setHorizontalGroup(
                registerPhysicainTransparentPnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(registerPhysicainTransparentPnl1Layout.createSequentialGroup()
                                .addGroup(registerPhysicainTransparentPnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(registerPhysicainTransparentPnl1Layout.createSequentialGroup()
                                                .addGap(113, 113, 113)
                                                .addComponent(RegistrationLbl2))
                                        .addGroup(registerPhysicainTransparentPnl1Layout.createSequentialGroup()
                                                .addGroup(registerPhysicainTransparentPnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(registerPhysicainTransparentPnl1Layout.createSequentialGroup()
                                                                .addGap(72, 72, 72)
                                                                .addGroup(registerPhysicainTransparentPnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(addressLbl2)
                                                                        .addComponent(dateOfBirthLbl2)
                                                                        .addComponent(postalCodeLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(cityLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(TitelLbl2)
                                                                        .addComponent(EmailLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(passLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(SteetLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(lastNameLbl2))
                                                                .addGap(33, 33, 33))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPhysicainTransparentPnl1Layout.createSequentialGroup()
                                                                .addGap(47, 47, 47)
                                                                .addGroup(registerPhysicainTransparentPnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPhysicainTransparentPnl1Layout.createSequentialGroup()
                                                                                .addComponent(firstNameLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(54, 54, 54))
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPhysicainTransparentPnl1Layout.createSequentialGroup()
                                                                                .addComponent(registrationPhysicinaBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                                                .addGroup(registerPhysicainTransparentPnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(passwordTxtFld2)
                                                        .addComponent(phoneTxtFld2)
                                                        .addComponent(titleTxtFld2)
                                                        .addComponent(houseNummberTxtfld1, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lastNameTxtFld2)
                                                        .addComponent(firstNameTxtFld2)
                                                        .addComponent(AddressTxtFld2)
                                                        .addComponent(eamilTexFld, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                                        .addComponent(postalCodeTextFld1)
                                                        .addComponent(streetTxtFld1)
                                                        .addComponent(registerbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                                .addContainerGap(21, Short.MAX_VALUE))
        );
        registerPhysicainTransparentPnl1Layout.setVerticalGroup(
                registerPhysicainTransparentPnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(registerPhysicainTransparentPnl1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(RegistrationLbl2)
                                .addGap(5, 5, 5)
                                .addGroup(registerPhysicainTransparentPnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(firstNameTxtFld2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(firstNameLbl2))
                                .addGap(10, 10, 10)
                                .addGroup(registerPhysicainTransparentPnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lastNameLbl2)
                                        .addComponent(lastNameTxtFld2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(registerPhysicainTransparentPnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(SteetLbl1)
                                        .addComponent(streetTxtFld1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(registerPhysicainTransparentPnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(dateOfBirthLbl2)
                                        .addComponent(houseNummberTxtfld1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(registerPhysicainTransparentPnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(addressLbl2)
                                        .addComponent(AddressTxtFld2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(registerPhysicainTransparentPnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(postalCodeLbl1)
                                        .addComponent(postalCodeTextFld1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(registerPhysicainTransparentPnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cityLbl2)
                                        .addComponent(phoneTxtFld2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(registerPhysicainTransparentPnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(TitelLbl2)
                                        .addComponent(titleTxtFld2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(registerPhysicainTransparentPnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(EmailLbl2)
                                        .addComponent(eamilTexFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(registerPhysicainTransparentPnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(passLbl2)
                                        .addComponent(passwordTxtFld2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(registerPhysicainTransparentPnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(registerbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(registrationPhysicinaBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(92, Short.MAX_VALUE))
        );

        registerPhysicianPanel.add(registerPhysicainTransparentPnl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 400, 570));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/loginpic3.png"))); // NOI18N
        registerPhysicianPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 892, 604));

        getContentPane().add(registerPhysicianPanel, "card2");

        registerPatientPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registerPatientTransparentPnl.setBackground(new java.awt.Color(0, 0, 0,150));

        RegistrationLbl1.setFont(new java.awt.Font("Californian FB", 2, 48)); // NOI18N
        RegistrationLbl1.setForeground(new java.awt.Color(255, 255, 255));
        RegistrationLbl1.setText("Registration");

        emailLbl.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        emailLbl.setForeground(new java.awt.Color(255, 255, 255));
        emailLbl.setText("Email");

        passLbl1.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        passLbl1.setForeground(new java.awt.Color(255, 255, 255));
        passLbl1.setText("Password");

        registerbtn1.setBorder(null);
        registerbtn1.setText("Register");
        registerbtn1.setkEndColor(new java.awt.Color(255, 255, 255));
        registerbtn1.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        registerbtn1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        registerbtn1.setkHoverStartColor(new java.awt.Color(0, 102, 204));
        registerbtn1.setkPressedColor(new java.awt.Color(0, 102, 204));
        registerbtn1.setkSelectedColor(new java.awt.Color(255, 255, 255));
        registerbtn1.setkStartColor(new java.awt.Color(0, 102, 204));

        firstNameLbl1.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        firstNameLbl1.setForeground(new java.awt.Color(255, 255, 255));
        firstNameLbl1.setText("Frist name");

        lastNameLbl1.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        lastNameLbl1.setForeground(new java.awt.Color(255, 255, 255));
        lastNameLbl1.setText("Last name");

        addressLbl1.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        addressLbl1.setForeground(new java.awt.Color(255, 255, 255));
        addressLbl1.setText("Address");

        postalCodeLbl.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        postalCodeLbl.setForeground(new java.awt.Color(255, 255, 255));
        postalCodeLbl.setText("Postal code");

        phoneLbl1.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        phoneLbl1.setForeground(new java.awt.Color(255, 255, 255));
        phoneLbl1.setText("Phone");

        TitelLbl1.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        TitelLbl1.setForeground(new java.awt.Color(255, 255, 255));
        TitelLbl1.setText("Title");

        dateOfBirthLbl1.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        dateOfBirthLbl1.setForeground(new java.awt.Color(255, 255, 255));
        dateOfBirthLbl1.setText("House number");

        postalCodeTextFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postalCodeTextFldActionPerformed(evt);
            }
        });

        SteetLbl.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        SteetLbl.setForeground(new java.awt.Color(255, 255, 255));
        SteetLbl.setText("Street");

        phoneLbl.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        phoneLbl.setForeground(new java.awt.Color(255, 255, 255));
        phoneLbl.setText("Phone");

        registrationPatientBackBtn1.setBorder(null);
        registrationPatientBackBtn1.setText("Back");
        registrationPatientBackBtn1.setkEndColor(new java.awt.Color(255, 255, 255));
        registrationPatientBackBtn1.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        registrationPatientBackBtn1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        registrationPatientBackBtn1.setkHoverStartColor(new java.awt.Color(0, 102, 204));
        registrationPatientBackBtn1.setkPressedColor(new java.awt.Color(0, 102, 204));
        registrationPatientBackBtn1.setkSelectedColor(new java.awt.Color(255, 255, 255));
        registrationPatientBackBtn1.setkStartColor(new java.awt.Color(0, 102, 204));
        registrationPatientBackBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationPatientBackBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registerPatientTransparentPnlLayout = new javax.swing.GroupLayout(registerPatientTransparentPnl);
        registerPatientTransparentPnl.setLayout(registerPatientTransparentPnlLayout);
        registerPatientTransparentPnlLayout.setHorizontalGroup(
                registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(registerPatientTransparentPnlLayout.createSequentialGroup()
                                .addGroup(registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(registerPatientTransparentPnlLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(registrationPatientBackBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(registerbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(registerPatientTransparentPnlLayout.createSequentialGroup()
                                                        .addGap(81, 81, 81)
                                                        .addGroup(registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(firstNameLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(lastNameLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(SteetLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(dateOfBirthLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(addressLbl1)
                                                                .addComponent(postalCodeLbl)
                                                                .addComponent(phoneLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(TitelLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(titleTxtFld1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(phoneTxtFld1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(postalCodeTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(streetTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(lastNameTxtFld1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(firstNameTxtFld1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(houseNummberTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(AddressTxtFld1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(registerPatientTransparentPnlLayout.createSequentialGroup()
                                                        .addGap(113, 113, 113)
                                                        .addComponent(RegistrationLbl1))
                                                .addGroup(registerPatientTransparentPnlLayout.createSequentialGroup()
                                                        .addGap(81, 81, 81)
                                                        .addGroup(registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(phoneTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(registerPatientTransparentPnlLayout.createSequentialGroup()
                                                                        .addGroup(registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(emailLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(phoneLbl)
                                                                                .addComponent(passLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(registerPatientTransparentPnlLayout.createSequentialGroup()
                                                                                        .addGap(15, 15, 15)
                                                                                        .addComponent(eMailTxtFld1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPatientTransparentPnlLayout.createSequentialGroup()
                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                        .addComponent(passwordTxtFld1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                                .addContainerGap(46, Short.MAX_VALUE))
        );
        registerPatientTransparentPnlLayout.setVerticalGroup(
                registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(registerPatientTransparentPnlLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(RegistrationLbl1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(registerPatientTransparentPnlLayout.createSequentialGroup()
                                                .addGroup(registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(firstNameLbl1)
                                                        .addComponent(firstNameTxtFld1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lastNameTxtFld1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lastNameLbl1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(SteetLbl)
                                        .addComponent(streetTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(houseNummberTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dateOfBirthLbl1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(AddressTxtFld1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(addressLbl1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(postalCodeLbl)
                                        .addComponent(postalCodeTextFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(phoneLbl1)
                                        .addComponent(phoneTxtFld1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(titleTxtFld1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TitelLbl1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(emailLbl)
                                        .addComponent(eMailTxtFld1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(phoneTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(phoneLbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(passwordTxtFld1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(passLbl1))
                                .addGap(18, 18, 18)
                                .addGroup(registerPatientTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(registerbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(registrationPatientBackBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(87, 87, 87))
        );

        registerPatientPanel.add(registerPatientTransparentPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 400, 520));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/loginpic3.png"))); // NOI18N
        registerPatientPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 892, 604));

        getContentPane().add(registerPatientPanel, "card2");

        resetPassPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resetPasswordTransparentPnl.setBackground(new java.awt.Color(0, 0, 0,150));

        resetPassLbl.setFont(new java.awt.Font("Californian FB", 2, 48)); // NOI18N
        resetPassLbl.setForeground(new java.awt.Color(255, 255, 255));
        resetPassLbl.setText("Reset your password");

        odlPassLbl.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        odlPassLbl.setForeground(new java.awt.Color(255, 255, 255));
        odlPassLbl.setText("Old password:");

        newPassLbl.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        newPassLbl.setForeground(new java.awt.Color(255, 255, 255));
        newPassLbl.setText("New  password");

        resetBtn.setBorder(null);
        resetBtn.setText("Reset");
        resetBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        resetBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        resetBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        resetBtn.setkHoverStartColor(new java.awt.Color(0, 102, 204));
        resetBtn.setkPressedColor(new java.awt.Color(0, 102, 204));
        resetBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        resetBtn.setkStartColor(new java.awt.Color(0, 102, 204));

        repeatPass.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        repeatPass.setForeground(new java.awt.Color(255, 255, 255));
        repeatPass.setText("Repeat password");

        registrationForgottBackBtn2.setBorder(null);
        registrationForgottBackBtn2.setText("Back");
        registrationForgottBackBtn2.setkEndColor(new java.awt.Color(255, 255, 255));
        registrationForgottBackBtn2.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        registrationForgottBackBtn2.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        registrationForgottBackBtn2.setkHoverStartColor(new java.awt.Color(0, 102, 204));
        registrationForgottBackBtn2.setkPressedColor(new java.awt.Color(0, 102, 204));
        registrationForgottBackBtn2.setkSelectedColor(new java.awt.Color(255, 255, 255));
        registrationForgottBackBtn2.setkStartColor(new java.awt.Color(0, 102, 204));
        registrationForgottBackBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationForgottBackBtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout resetPasswordTransparentPnlLayout = new javax.swing.GroupLayout(resetPasswordTransparentPnl);
        resetPasswordTransparentPnl.setLayout(resetPasswordTransparentPnlLayout);
        resetPasswordTransparentPnlLayout.setHorizontalGroup(
                resetPasswordTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(resetPasswordTransparentPnlLayout.createSequentialGroup()
                                .addGroup(resetPasswordTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(resetPasswordTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(resetPasswordTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(resetPasswordTransparentPnlLayout.createSequentialGroup()
                                                                .addGap(60, 60, 60)
                                                                .addGroup(resetPasswordTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(resetPasswordTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resetPasswordTransparentPnlLayout.createSequentialGroup()
                                                                                        .addComponent(odlPassLbl)
                                                                                        .addGap(83, 83, 83))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resetPasswordTransparentPnlLayout.createSequentialGroup()
                                                                                        .addComponent(newPassLbl)
                                                                                        .addGap(76, 76, 76)))
                                                                        .addGroup(resetPasswordTransparentPnlLayout.createSequentialGroup()
                                                                                .addComponent(repeatPass)
                                                                                .addGap(64, 64, 64)))
                                                                .addGroup(resetPasswordTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(oldPassTxtfld, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                                                        .addComponent(newPassTxtfld)
                                                                        .addComponent(repeatPassTxtfld)))
                                                        .addGroup(resetPasswordTransparentPnlLayout.createSequentialGroup()
                                                                .addGap(36, 36, 36)
                                                                .addComponent(resetPassLbl))))
                                        .addGroup(resetPasswordTransparentPnlLayout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(registrationForgottBackBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(25, Short.MAX_VALUE))
        );
        resetPasswordTransparentPnlLayout.setVerticalGroup(
                resetPasswordTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(resetPasswordTransparentPnlLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(resetPassLbl)
                                .addGap(59, 59, 59)
                                .addGroup(resetPasswordTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(odlPassLbl)
                                        .addComponent(oldPassTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(resetPasswordTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(newPassLbl)
                                        .addComponent(newPassTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(resetPasswordTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(repeatPass)
                                        .addComponent(repeatPassTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(resetPasswordTransparentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(resetBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(registrationForgottBackBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(78, Short.MAX_VALUE))
        );

        resetPassPanel.add(resetPasswordTransparentPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 400, 420));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/loginpic3.png"))); // NOI18N
        resetPassPanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 892, 604));

        getContentPane().add(resetPassPanel, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void logintBtnActionPerformed(java.awt.event.ActionEvent evt) throws SQLException, ClassNotFoundException {
        Databaseconnection databaseconnection = new Databaseconnection();
        String DatabasePw = null;
        try {
            DatabasePw = databaseconnection.getUserPw(userNameTexFld.getText());
        } catch (SQLException | ClassNotFoundException sqlException) {
            sqlException.printStackTrace();
        }
        if(DatabasePw == null) {
            JOptionPane.showMessageDialog(loginPanel,"eMail-Address not found", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            String password = String.valueOf(jPasswordField1.getPassword());
            int check = -1;
            while (check == -1) {
                if (evt.getSource() == logintBtn) {
                    if (userNameTexFld.getText().equals("") || password.equals("")) {
                        JOptionPane.showMessageDialog(loginPanel, "Fields cannot be empty! Please enter your data.");
                        break;
                    } else if ((org.mindrot.jbcrypt.BCrypt.checkpw(password,DatabasePw))) {

                        if(databaseconnection.checkPhysician(userNameTexFld.getText())){
                            JOptionPane.showMessageDialog(loginPanel, "Login successful!");
                            dispose();
                            check = 0;
                            PhysicianGUI phyG = new PhysicianGUI(databaseconnection.getPhysician(userNameTexFld.getText()));
                            phyG.setVisible(true);
                        }else if(databaseconnection.checkPatient(userNameTexFld.getText())){
                            JOptionPane.showMessageDialog(loginPanel, "Login successful!");
                            dispose();
                            check = 0;
                            PatientGUI patG = new PatientGUI();
                            patG.setVisible(true);
                        }
                    } else {
                        System.out.println(User.hashPassword(password));
                        JOptionPane.showMessageDialog(loginPanel, "Login unsuccessful!", "Error", JOptionPane.ERROR_MESSAGE);
                        break;
                    }
                }
            }

        }
    }

    private void newRegistrationLblMouseClicked(java.awt.event.MouseEvent evt) {
        loginPanel.setVisible(false);
        resetPassPanel.setVisible(false);
        registerPhysicianPanel.setVisible(false);
        registerPatientPanel.setVisible(true);
        // TODO add your handling code here:
    }

    private void forgotPassLblMouseClicked(java.awt.event.MouseEvent evt) {
        loginPanel.setVisible(false);
        registerPhysicianPanel.setVisible(false);
        registerPatientPanel.setVisible(false);
        resetPassPanel.setVisible(true);    // TODO add your handling code here:
    }

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {
        loginPanel.setVisible(false);
        resetPassPanel.setVisible(false);
        registerPatientPanel.setVisible(false);
        registerPhysicianPanel.setVisible(true);
    }

    private void postalCodeTextFldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void registrationPhysicinaBackBtnActionPerformed(java.awt.event.ActionEvent evt) {
        resetPassPanel.setVisible(false);
        registerPhysicianPanel.setVisible(false);
        registerPatientPanel.setVisible(false);
        loginPanel.setVisible(true);
    }

    private void registrationPatientBackBtn1ActionPerformed(java.awt.event.ActionEvent evt) {
        resetPassPanel.setVisible(false);
        registerPhysicianPanel.setVisible(false);
        registerPatientPanel.setVisible(false);
        loginPanel.setVisible(true);
    }

    private void registrationForgottBackBtn2ActionPerformed(java.awt.event.ActionEvent evt) {
        resetPassPanel.setVisible(false);
        registerPhysicianPanel.setVisible(false);
        registerPatientPanel.setVisible(false);
        loginPanel.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */



    // Variables declaration - do not modify
    private javax.swing.JTextField AddressTxtFld1;
    private javax.swing.JTextField AddressTxtFld2;
    private javax.swing.JLabel EmailLbl2;
    private javax.swing.JLabel RegistrationLbl1;
    private javax.swing.JLabel RegistrationLbl2;
    private javax.swing.JLabel SteetLbl;
    private javax.swing.JLabel SteetLbl1;
    private javax.swing.JLabel TitelLbl1;
    private javax.swing.JLabel TitelLbl2;
    private javax.swing.JLabel addressLbl1;
    private javax.swing.JLabel addressLbl2;
    private javax.swing.JLabel cityLbl2;
    private javax.swing.JLabel dateOfBirthLbl1;
    private javax.swing.JLabel dateOfBirthLbl2;
    private javax.swing.JTextField eMailTxtFld1;
    private javax.swing.JTextField eamilTexFld;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JLabel firstNameLbl1;
    private javax.swing.JLabel firstNameLbl2;
    private javax.swing.JTextField firstNameTxtFld1;
    private javax.swing.JTextField firstNameTxtFld2;
    private javax.swing.JLabel forgotPassLbl;
    private javax.swing.JTextField houseNummberTxtfld;
    private javax.swing.JTextField houseNummberTxtfld1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel lastNameLbl1;
    private javax.swing.JLabel lastNameLbl2;
    private javax.swing.JTextField lastNameTxtFld1;
    private javax.swing.JTextField lastNameTxtFld2;
    private javax.swing.JLabel loginLbl;
    private javax.swing.JPanel loginPanel;
    private keeptoo.KButton logintBtn;
    private javax.swing.JLabel newPassLbl;
    private javax.swing.JTextField newPassTxtfld;
    private javax.swing.JLabel newRegistrationLbl;
    private javax.swing.JLabel odlPassLbl;
    private javax.swing.JTextField oldPassTxtfld;
    private javax.swing.JLabel passLbl1;
    private javax.swing.JLabel passLbl2;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JPasswordField passwordTxtFld1;
    private javax.swing.JPasswordField passwordTxtFld2;
    private javax.swing.JLabel phoneLbl;
    private javax.swing.JLabel phoneLbl1;
    private javax.swing.JTextField phoneTxtFld1;
    private javax.swing.JTextField phoneTxtFld2;
    private javax.swing.JTextField phoneTxtfld;
    private javax.swing.JLabel postalCodeLbl;
    private javax.swing.JLabel postalCodeLbl1;
    private javax.swing.JTextField postalCodeTextFld;
    private javax.swing.JTextField postalCodeTextFld1;
    private javax.swing.JPanel registerPatientPanel;
    private javax.swing.JPanel registerPatientTransparentPnl;
    private javax.swing.JPanel registerPhysicainTransparentPnl1;
    private javax.swing.JPanel registerPhysicianPanel;
    private keeptoo.KButton registerbtn1;
    private keeptoo.KButton registerbtn3;
    private keeptoo.KButton registrationForgottBackBtn2;
    private keeptoo.KButton registrationPatientBackBtn1;
    private keeptoo.KButton registrationPhysicinaBackBtn;
    private javax.swing.JLabel repeatPass;
    private javax.swing.JTextField repeatPassTxtfld;
    private keeptoo.KButton resetBtn;
    private javax.swing.JLabel resetPassLbl;
    private javax.swing.JPanel resetPassPanel;
    private javax.swing.JPanel resetPasswordTransparentPnl;
    private javax.swing.JTextField streetTxtFld;
    private javax.swing.JTextField streetTxtFld1;
    private javax.swing.JTextField titleTxtFld1;
    private javax.swing.JTextField titleTxtFld2;
    private javax.swing.JPanel transparentLoginPanel;
    private javax.swing.JLabel userNameLbl;
    private javax.swing.JTextField userNameTexFld;
    // End of variables declaration
}
