/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.awt.*;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Objects;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class PatientGUI extends javax.swing.JFrame {

    Appointment [] appointments;
    Appointment selectedAppointment;

    public PatientGUI(Patient patient) {

        setUndecorated(false);
        getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK));
        initComponents();




        populateTable(patient);
        populateEditProfilePnl(patient);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaulted="collapsed" desc="Generated Code">
    private void initComponents() {

        mainPnl = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        framePicLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        menuBarHomeBtn = new keeptoo.KButton();
        menuBarEditprofileBtn = new keeptoo.KButton();
        lmenuBarLogoutBtn = new keeptoo.KButton();
        menuBarExitBtn = new keeptoo.KButton();
        welcomeLbl = new javax.swing.JLabel();
        welcomNameLbl = new javax.swing.JLabel();
        menuBarNewAppBtn = new keeptoo.KButton();
        jPanel3 = new javax.swing.JPanel();
        p1 = new keeptoo.KGradientPanel();
        sendAlternativekButton6 = new keeptoo.KButton();
        patientAppointmentTable = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        yourAppointmenstLbl = new javax.swing.JLabel();
        sendAlternativekButton7 = new keeptoo.KButton();
        reminderkButton = new keeptoo.KButton();
        porfilePnl = new keeptoo.KGradientPanel();
        nameLbl = new javax.swing.JLabel();
        nameTxtfld = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        familyNameLbl = new javax.swing.JLabel();
        userNameLbl = new javax.swing.JLabel();
        titleLbl = new javax.swing.JLabel();
        specificationLbl = new javax.swing.JLabel();
        addressLbl = new javax.swing.JLabel();
        emailLbl = new javax.swing.JLabel();
        phoneLbl = new javax.swing.JLabel();
        familynameTxtfld = new javax.swing.JLabel();
        usernameTxtfld = new javax.swing.JTextField();
        titleTxtfld = new javax.swing.JTextField();
        specificationTxtfld = new javax.swing.JTextField();
        AddressTxtfld = new javax.swing.JTextField();
        emailTxtfld = new javax.swing.JTextField();
        phoneTxtfld = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        logoutBtn1 = new keeptoo.KButton();
        newAppPnl = new keeptoo.KGradientPanel();
        reminderTimeComboBox = new javax.swing.JComboBox<>();
        reminderLbl = new javax.swing.JLabel();
        searchdistanceLbl = new javax.swing.JLabel();
        searchDistanceTexfld = new javax.swing.JTextField();
        sendRequeskButton = new keeptoo.KButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        physicianListLbl = new javax.swing.JLabel();
        searchPhysicianBtn = new keeptoo.KButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        SendAlternative = new keeptoo.KGradientPanel();
        sendFirstAlternativejDateChooser = new com.toedter.calendar.JDateChooser();
        chooseFirstAterantivedateLbl = new javax.swing.JLabel();
        ChooseSecondAterantivedateLbl = new javax.swing.JLabel();
        sendSecondAlternativejDateChooser = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        addnoteTexFld = new javax.swing.JTextArea();
        addNotelbl = new javax.swing.JLabel();
        sendAppointmntRequestBtn = new keeptoo.KButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPnl.setkEndColor(new java.awt.Color(255, 255, 255));
        mainPnl.setkStartColor(new java.awt.Color(153, 204, 255));
        mainPnl.setLayout(new java.awt.BorderLayout());

        framePicLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/patient.jpg"))); // NOI18N
        framePicLbl.setText("jLabel8");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(framePicLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 891, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(framePicLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        mainPnl.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        menuBarHomeBtn.setBorder(null);
        menuBarHomeBtn.setText("Home");
        menuBarHomeBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        menuBarHomeBtn.setkForeGround(new java.awt.Color(0, 0, 0));
        menuBarHomeBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        menuBarHomeBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        menuBarHomeBtn.setkHoverStartColor(new java.awt.Color(51, 255, 51));
        menuBarHomeBtn.setkPressedColor(new java.awt.Color(51, 255, 51));
        menuBarHomeBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        menuBarHomeBtn.setkStartColor(new java.awt.Color(102, 255, 102));
        menuBarHomeBtn.addActionListener(this::menuBarHomeBtnActionPerformed);

        menuBarEditprofileBtn.setBorder(null);
        menuBarEditprofileBtn.setText("Edit Profile");
        menuBarEditprofileBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        menuBarEditprofileBtn.setkForeGround(new java.awt.Color(0, 0, 0));
        menuBarEditprofileBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        menuBarEditprofileBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        menuBarEditprofileBtn.setkHoverStartColor(new java.awt.Color(51, 255, 51));
        menuBarEditprofileBtn.setkPressedColor(new java.awt.Color(51, 255, 51));
        menuBarEditprofileBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        menuBarEditprofileBtn.setkStartColor(new java.awt.Color(102, 255, 102));
        menuBarEditprofileBtn.addActionListener(this::menuBarEditprofileBtnActionPerformed);

        lmenuBarLogoutBtn.setBorder(null);
        lmenuBarLogoutBtn.setText("Logout");
        lmenuBarLogoutBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        lmenuBarLogoutBtn.setkForeGround(new java.awt.Color(0, 0, 0));
        lmenuBarLogoutBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        lmenuBarLogoutBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        lmenuBarLogoutBtn.setkHoverStartColor(new java.awt.Color(51, 255, 51));
        lmenuBarLogoutBtn.setkPressedColor(new java.awt.Color(51, 255, 51));
        lmenuBarLogoutBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        lmenuBarLogoutBtn.setkStartColor(new java.awt.Color(102, 255, 102));
        lmenuBarLogoutBtn.addActionListener(this::lmenuBarLogoutBtnActionPerformed);

        menuBarExitBtn.setBorder(null);
        menuBarExitBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        menuBarExitBtn.setkForeGround(new java.awt.Color(51, 51, 51));
        menuBarExitBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        menuBarExitBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        menuBarExitBtn.setkHoverStartColor(new java.awt.Color(51, 255, 51));
        menuBarExitBtn.setkPressedColor(new java.awt.Color(51, 255, 51));
        menuBarExitBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        menuBarExitBtn.setkStartColor(new java.awt.Color(102, 255, 102));
        menuBarExitBtn.setText("Exit");
        menuBarExitBtn.addActionListener(this::menuBarExitBtnActionPerformed);

        welcomeLbl.setFont(new java.awt.Font("Baskerville Old Face", Font.ITALIC, 20)); // NOI18N
        welcomeLbl.setText("Welcome");

        welcomNameLbl.setFont(new java.awt.Font("Baskerville Old Face", Font.ITALIC, 20)); // NOI18N
        welcomNameLbl.setText("Name");

        menuBarNewAppBtn.setBorder(null);
        menuBarNewAppBtn.setText("New Appointment");
        menuBarNewAppBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        menuBarNewAppBtn.setkForeGround(new java.awt.Color(0, 0, 0));
        menuBarNewAppBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        menuBarNewAppBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        menuBarNewAppBtn.setkHoverStartColor(new java.awt.Color(51, 255, 51));
        menuBarNewAppBtn.setkPressedColor(new java.awt.Color(51, 255, 51));
        menuBarNewAppBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        menuBarNewAppBtn.setkStartColor(new java.awt.Color(102, 255, 102));
        menuBarNewAppBtn.addActionListener(this::menuBarNewAppBtnActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(menuBarHomeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                        .addComponent(menuBarEditprofileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lmenuBarLogoutBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(menuBarExitBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(welcomNameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(welcomeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(menuBarNewAppBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(welcomeLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(welcomNameLbl)
                                .addGap(32, 32, 32)
                                .addComponent(menuBarHomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(menuBarEditprofileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(menuBarNewAppBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lmenuBarLogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                .addComponent(menuBarExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62))
        );

        mainPnl.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setLayout(new java.awt.CardLayout());

        p1.setkEndColor(new java.awt.Color(255, 255, 255));
        p1.setkStartColor(new java.awt.Color(204, 255, 204));

        sendAlternativekButton6.setBorder(null);
        sendAlternativekButton6.setText("Print Healt Information");
        sendAlternativekButton6.setkEndColor(new java.awt.Color(102, 255, 102));
        sendAlternativekButton6.setkForeGround(new java.awt.Color(0, 0, 0));
        sendAlternativekButton6.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        sendAlternativekButton6.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        sendAlternativekButton6.setkHoverStartColor(new java.awt.Color(102, 255, 102));
        sendAlternativekButton6.setkPressedColor(new java.awt.Color(204, 255, 204));
        sendAlternativekButton6.setkSelectedColor(new java.awt.Color(255, 255, 255));
        sendAlternativekButton6.setkStartColor(new java.awt.Color(255, 255, 255));
        sendAlternativekButton6.addActionListener(this::sendAlternativekButton6ActionPerformed);

        jTable2.setBackground(new java.awt.Color(204, 255, 204));
        jTable2.getTableHeader().setReorderingAllowed(false);
        jTable2.getTableHeader().setResizingAllowed(false);
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "Physician", "Specalization", "Appointment date", "Physician E-Mail"
                }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });

        patientAppointmentTable.setViewportView(jTable2);

        yourAppointmenstLbl.setFont(new java.awt.Font("Times New Roman", Font.ITALIC, 18)); // NOI18N
        yourAppointmenstLbl.setText("Your Appointments");

        sendAlternativekButton7.setBorder(null);
        sendAlternativekButton7.setText("Send Alternative");
        sendAlternativekButton7.setkEndColor(new java.awt.Color(102, 255, 102));
        sendAlternativekButton7.setkForeGround(new java.awt.Color(0, 0, 0));
        sendAlternativekButton7.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        sendAlternativekButton7.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        sendAlternativekButton7.setkHoverStartColor(new java.awt.Color(102, 255, 102));
        sendAlternativekButton7.setkPressedColor(new java.awt.Color(204, 255, 204));
        sendAlternativekButton7.setkSelectedColor(new java.awt.Color(255, 255, 255));
        sendAlternativekButton7.setkStartColor(new java.awt.Color(255, 255, 255));
        sendAlternativekButton7.addActionListener(this::sendAlternativekButton7ActionPerformed);

        reminderkButton.setBorder(null);
        reminderkButton.setText("Reminder");
        reminderkButton.setkEndColor(new java.awt.Color(102, 255, 102));
        reminderkButton.setkForeGround(new java.awt.Color(0, 0, 0));
        reminderkButton.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        reminderkButton.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        reminderkButton.setkHoverStartColor(new java.awt.Color(102, 255, 102));
        reminderkButton.setkPressedColor(new java.awt.Color(204, 255, 204));
        reminderkButton.setkSelectedColor(new java.awt.Color(255, 255, 255));
        reminderkButton.setkStartColor(new java.awt.Color(255, 255, 255));
        reminderkButton.addActionListener(this::reminderkButtonActionPerformed);
        reminderkButton.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
               int index =  jTable2.getSelectedRow();
               String sDate1=jTable2.getValueAt(index,2).toString();

               DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
               LocalDateTime dateTime = LocalDateTime.parse(sDate1, formatter);
               int y = dateTime.getYear();
               int m = dateTime.getMonthValue()-1;
               int d = dateTime.getDayOfMonth();
               int h = dateTime.getHour();
               int mm =  dateTime.getMinute();
               int minutesBefore;
               int indexReminderComboBox = reminderTimeComboBox.getSelectedIndex();
               String timeInTextBefore;
                switch (indexReminderComboBox) {
                    case 0 -> {
                        minutesBefore = 24 * 60 * 7;
                        timeInTextBefore = Objects.requireNonNull(reminderTimeComboBox.getSelectedItem()).toString();//7 days
                    }
                    case 1 -> {
                        minutesBefore = 24 * 60 * 3;
                        timeInTextBefore = Objects.requireNonNull(reminderTimeComboBox.getSelectedItem()).toString();//3 days
                    }
                    case 2 -> {
                        minutesBefore = 60;
                        timeInTextBefore = Objects.requireNonNull(reminderTimeComboBox.getSelectedItem()).toString();//1 hour
                    }
                    case 3 -> {
                        minutesBefore = 10;
                        timeInTextBefore = Objects.requireNonNull(reminderTimeComboBox.getSelectedItem()).toString();//10 minutes
                    }
                    default -> throw new IllegalStateException("Unexpected value :-): " + indexReminderComboBox);
                }

               Appointment.reminder(y,m,d,h,mm,minutesBefore,timeInTextBefore);

            }

            @Override
            public void mousePressed(MouseEvent e) {

            }

            @Override
            public void mouseReleased(MouseEvent e) {

            }

            @Override
            public void mouseEntered(MouseEvent e) {

            }

            @Override
            public void mouseExited(MouseEvent e) {

            }
        });

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
                p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(p1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(p1Layout.createSequentialGroup()
                                                .addComponent(yourAppointmenstLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1Layout.createSequentialGroup()
                                                .addComponent(patientAppointmentTable, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                                                .addGap(18, 18, 18))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(sendAlternativekButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(reminderkButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap())))
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1Layout.createSequentialGroup()
                                        .addContainerGap(470, Short.MAX_VALUE)
                                        .addComponent(sendAlternativekButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)))
        );
        p1Layout.setVerticalGroup(
                p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(yourAppointmenstLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addComponent(patientAppointmentTable, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(reminderkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(sendAlternativekButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39))
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1Layout.createSequentialGroup()
                                        .addContainerGap(331, Short.MAX_VALUE)
                                        .addComponent(sendAlternativekButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(78, 78, 78)))
        );

        jPanel3.add(p1, "card2");

        porfilePnl.setkEndColor(new java.awt.Color(255, 255, 255));
        porfilePnl.setkStartColor(new java.awt.Color(204, 255, 204));

        nameLbl.setText("Name");

        nameTxtfld.setText("jLabel10");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/edit.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11mouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11mouseExited(evt);
            }
        });

        familyNameLbl.setText("Family name");

        userNameLbl.setText("User name");

        titleLbl.setText("Title");

        specificationLbl.setText("Specification");

        addressLbl.setText("Address");

        emailLbl.setText("E-Mail");

        phoneLbl.setText("Phone");

        familynameTxtfld.setText("jLabel18");

        usernameTxtfld.setText("jTextField1");

        titleTxtfld.setText("jTextField2");

        specificationTxtfld.setText("jTextField3");

        AddressTxtfld.setText("jTextField4");

        emailTxtfld.setText("jTextField5");

        phoneTxtfld.setText("jTextField6");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/edit.png"))); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel19mouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel19mouseExited(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/edit.png"))); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel21mouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel21mouseExited(evt);
            }
        });

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/edit.png"))); // NOI18N
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel22mouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel22mouseExited(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/edit.png"))); // NOI18N
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel23mouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel23mouseExited(evt);
            }
        });

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/edit.png"))); // NOI18N
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel24mouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel24mouseExited(evt);
            }
        });

        logoutBtn1.setBorder(null);
        logoutBtn1.setText("Save Changes");
        logoutBtn1.setkEndColor(new java.awt.Color(51, 255, 51));
        logoutBtn1.setkForeGround(new java.awt.Color(0, 0, 0));
        logoutBtn1.setkHoverEndColor(new java.awt.Color(102, 255, 102));
        logoutBtn1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        logoutBtn1.setkHoverStartColor(new java.awt.Color(102, 255, 102));
        logoutBtn1.setkPressedColor(new java.awt.Color(102, 255, 102));
        logoutBtn1.setkSelectedColor(new java.awt.Color(255, 255, 255));
        logoutBtn1.setkStartColor(new java.awt.Color(255, 255, 255));


        javax.swing.GroupLayout porfilePnlLayout = new javax.swing.GroupLayout(porfilePnl);
        porfilePnl.setLayout(porfilePnlLayout);
        porfilePnlLayout.setHorizontalGroup(
                porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(porfilePnlLayout.createSequentialGroup()
                                .addContainerGap(106, Short.MAX_VALUE)
                                .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(porfilePnlLayout.createSequentialGroup()
                                                .addComponent(addressLbl)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel21))
                                        .addGroup(porfilePnlLayout.createSequentialGroup()
                                                .addComponent(emailLbl)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel23))
                                        .addGroup(porfilePnlLayout.createSequentialGroup()
                                                .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, porfilePnlLayout.createSequentialGroup()
                                                                .addComponent(titleLbl)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(titleTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, porfilePnlLayout.createSequentialGroup()
                                                                .addComponent(phoneLbl)
                                                                .addGap(99, 99, 99)
                                                                .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(specificationTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(phoneTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(AddressTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(emailTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(specificationLbl)
                                                        .addGroup(porfilePnlLayout.createSequentialGroup()
                                                                .addComponent(userNameLbl)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(usernameTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)))
                                        .addGroup(porfilePnlLayout.createSequentialGroup()
                                                .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(familyNameLbl)
                                                        .addComponent(nameLbl))
                                                .addGap(70, 70, 70)
                                                .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(nameTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(familynameTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 99, Short.MAX_VALUE)))
                                .addContainerGap(216, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, porfilePnlLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(logoutBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        porfilePnlLayout.setVerticalGroup(
                porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(porfilePnlLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(nameLbl)
                                        .addComponent(nameTxtfld))
                                .addGap(18, 18, 18)
                                .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(familyNameLbl)
                                        .addComponent(familynameTxtfld))
                                .addGap(18, 18, 18)
                                .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(userNameLbl)
                                                .addComponent(usernameTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(titleLbl)
                                                .addComponent(titleTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(specificationLbl)
                                                .addComponent(specificationTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(addressLbl)
                                                .addComponent(AddressTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(emailLbl)
                                        .addComponent(emailTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(phoneLbl)
                                        .addComponent(phoneTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addComponent(logoutBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44))
        );

        jPanel3.add(porfilePnl, "card4");

        newAppPnl.setkEndColor(new java.awt.Color(255, 255, 255));
        newAppPnl.setkStartColor(new java.awt.Color(153, 255, 153));

        reminderTimeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "one week", "3 days", "1 hour", "10 min" }));

        reminderLbl.setText("Set reminder:");

        searchdistanceLbl.setText("Search distance:");

        searchDistanceTexfld.setText("2");

        sendRequeskButton.setBorder(null);
        sendRequeskButton.setText("Send Request");
        sendRequeskButton.setkEndColor(new java.awt.Color(255, 255, 255));
        sendRequeskButton.setkForeGround(new java.awt.Color(0, 0, 0));
        sendRequeskButton.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        sendRequeskButton.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        sendRequeskButton.setkHoverStartColor(new java.awt.Color(51, 255, 51));
        sendRequeskButton.setkPressedColor(new java.awt.Color(51, 255, 51));
        sendRequeskButton.setkSelectedColor(new java.awt.Color(255, 255, 255));
        sendRequeskButton.setkStartColor(new java.awt.Color(102, 255, 102));

        jTable1.setBackground(new java.awt.Color(204, 255, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {"Elena ", "Schmick", "General practitioner", "Heerstraße 53, 60488 Frankfurt am Main"},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "First name", "Last name", "Specification", "Address"
                }
        ));
        jScrollPane2.setViewportView(jTable1);

        physicianListLbl.setFont(new java.awt.Font("Baskerville Old Face", Font.ITALIC, 20)); // NOI18N
        physicianListLbl.setText("Physician list");

        searchPhysicianBtn.setBorder(null);
        searchPhysicianBtn.setText("Search for Physician");
        searchPhysicianBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        searchPhysicianBtn.setkForeGround(new java.awt.Color(0, 0, 0));
        searchPhysicianBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        searchPhysicianBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        searchPhysicianBtn.setkHoverStartColor(new java.awt.Color(51, 255, 51));
        searchPhysicianBtn.setkPressedColor(new java.awt.Color(51, 255, 51));
        searchPhysicianBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        searchPhysicianBtn.setkStartColor(new java.awt.Color(102, 255, 102));

        jLabel1.setText("Choose specification");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General practitioner", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout newAppPnlLayout = new javax.swing.GroupLayout(newAppPnl);
        newAppPnl.setLayout(newAppPnlLayout);
        newAppPnlLayout.setHorizontalGroup(
                newAppPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(newAppPnlLayout.createSequentialGroup()
                                .addGroup(newAppPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
                                        .addGroup(newAppPnlLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(physicianListLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newAppPnlLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(reminderLbl)
                                .addGap(142, 142, 142)
                                .addComponent(reminderTimeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newAppPnlLayout.createSequentialGroup()
                                .addContainerGap(348, Short.MAX_VALUE)
                                .addGroup(newAppPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sendRequeskButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(searchPhysicianBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newAppPnlLayout.createSequentialGroup()
                                                .addGroup(newAppPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(searchdistanceLbl)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(31, 31, 31)
                                                .addGroup(newAppPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(searchDistanceTexfld)
                                                        .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(23, 23, 23))))
        );
        newAppPnlLayout.setVerticalGroup(
                newAppPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(newAppPnlLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(physicianListLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addGroup(newAppPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(searchdistanceLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(searchDistanceTexfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2)
                                .addGroup(newAppPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(newAppPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(reminderLbl)
                                        .addComponent(reminderTimeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55)
                                .addComponent(searchPhysicianBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sendRequeskButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        jPanel3.add(newAppPnl, "card2");

        SendAlternative.setkEndColor(new java.awt.Color(255, 255, 255));
        SendAlternative.setkStartColor(new java.awt.Color(153, 255, 153));

        sendFirstAlternativejDateChooser.setBackground(new java.awt.Color(204, 255, 204));

        chooseFirstAterantivedateLbl.setText("Choose first alternative date:");

        ChooseSecondAterantivedateLbl.setText("Choose second alternative date:");

        sendSecondAlternativejDateChooser.setBackground(new java.awt.Color(204, 255, 204));

        addnoteTexFld.setColumns(20);
        addnoteTexFld.setRows(5);
        jScrollPane1.setViewportView(addnoteTexFld);

        addNotelbl.setText("Add note:");

        sendAppointmntRequestBtn.setBorder(null);
        sendAppointmntRequestBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/send-4008.png"))); // NOI18N
        sendAppointmntRequestBtn.setText(" Send Request");
        sendAppointmntRequestBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        sendAppointmntRequestBtn.setkForeGround(new java.awt.Color(0, 0, 0));
        sendAppointmntRequestBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        sendAppointmntRequestBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        sendAppointmntRequestBtn.setkHoverStartColor(new java.awt.Color(51, 255, 51));
        sendAppointmntRequestBtn.setkPressedColor(new java.awt.Color(51, 255, 51));
        sendAppointmntRequestBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        sendAppointmntRequestBtn.setkStartColor(new java.awt.Color(102, 255, 102));
        sendAppointmntRequestBtn.addActionListener(this::sendAppointmntRequestBtnActionPerformed);

        jLabel3.setText("Patient name");

        jLabel4.setText("Name");

        jLabel5.setText("E-Mail");

        jLabel6.setText("example@live.com");

        javax.swing.GroupLayout SendAlternativeLayout = new javax.swing.GroupLayout(SendAlternative);
        SendAlternative.setLayout(SendAlternativeLayout);
        SendAlternativeLayout.setHorizontalGroup(
                SendAlternativeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(SendAlternativeLayout.createSequentialGroup()
                                .addContainerGap(176, Short.MAX_VALUE)
                                .addGroup(SendAlternativeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sendAppointmntRequestBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SendAlternativeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SendAlternativeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(addNotelbl)
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(SendAlternativeLayout.createSequentialGroup()
                                                        .addGroup(SendAlternativeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel3)
                                                                .addComponent(jLabel5))
                                                        .addGap(29, 29, 29)
                                                        .addGroup(SendAlternativeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SendAlternativeLayout.createSequentialGroup()
                                                        .addGroup(SendAlternativeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(ChooseSecondAterantivedateLbl)
                                                                .addComponent(chooseFirstAterantivedateLbl))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(SendAlternativeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(sendFirstAlternativejDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                                                .addComponent(sendSecondAlternativejDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                .addGap(90, 90, 90))
        );
        SendAlternativeLayout.setVerticalGroup(
                SendAlternativeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(SendAlternativeLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(SendAlternativeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(chooseFirstAterantivedateLbl)
                                        .addComponent(sendFirstAlternativejDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(SendAlternativeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ChooseSecondAterantivedateLbl)
                                        .addComponent(sendSecondAlternativejDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(SendAlternativeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(SendAlternativeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addComponent(addNotelbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sendAppointmntRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49))
        );

        jPanel3.add(SendAlternative, "card2");

        mainPnl.add(jPanel3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(mainPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mainPnl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void menuBarHomeBtnActionPerformed(java.awt.event.ActionEvent evt) {
        newAppPnl.setVisible(false);
        SendAlternative.setVisible(false);
        porfilePnl.setVisible(false);
        p1.setVisible(true);

    }

    private void menuBarEditprofileBtnActionPerformed(java.awt.event.ActionEvent evt) {

        SendAlternative.setVisible(false);
        newAppPnl.setVisible(false);
        p1.setVisible(false);
        porfilePnl.setVisible(true);

    }

    private void menuBarExitBtnActionPerformed(java.awt.event.ActionEvent evt) {

        dispose();


    }

    private void sendAlternativekButton6ActionPerformed(java.awt.event.ActionEvent evt) {


    }

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {

    }

    private void jLabel11mouseEntered(java.awt.event.MouseEvent evt) {
        if(evt.getSource()==jLabel11){
            jLabel11.setBackground(new Color(153,204,255));
        }
    }

    private void jLabel11mouseExited(java.awt.event.MouseEvent evt) {
        if(evt.getSource()==jLabel11){
            jLabel11.setBackground(new Color(0,0,255));
        }
    }

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void jLabel19mouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void jLabel19mouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void jLabel21mouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void jLabel21mouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void jLabel22mouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void jLabel22mouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void jLabel23mouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void jLabel23mouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {

    }

    private void jLabel24mouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void jLabel24mouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void menuBarNewAppBtnActionPerformed(java.awt.event.ActionEvent evt) {
        porfilePnl.setVisible(false);
        p1.setVisible(false);
        SendAlternative.setVisible(false);
        newAppPnl.setVisible(true);
    }

    private void lmenuBarLogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
        new LoginGUI().setVisible(true);
    }

    private void sendAlternativekButton7ActionPerformed(java.awt.event.ActionEvent evt) {
        p1.setVisible(false);
        newAppPnl.setVisible(false);
        porfilePnl.setVisible(false);
        SendAlternative.setVisible(true);
    }

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {
       /*
        int index=jTable2.getSelectedRow();
        TableModel model=jTable2.getModel();
        jLabel6.setText(model.getValueAt(index,3).toString());
        jLabel4.setText(model.getValueAt(index,0).toString());
        String sDate1=model.getValueAt(index,2).toString();


        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
        LocalDateTime dateTime = LocalDateTime.parse(sDate1, formatter);


        for (Appointment appointment : appointments) {
            if (appointment.getPatient().getLastName().equals(jLabel4.getText()) && appointment.getDate().equals(dateTime)) {
                selectedAppointment = appointment;
            }
        }

        */
        // TODO add your handling code here:
    }

    private void sendAppointmntRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {
        LocalDateTime now = LocalDateTime.now();
        Date date1 =(java.sql.Timestamp.valueOf(now));
        Date date2 =(sendFirstAlternativejDateChooser.getDate());
        Date date3 =(sendSecondAlternativejDateChooser.getDate());



        if (date1.before(date2)&&date1.before(date3)) {

            new Mail().sendAppointmentRequest(selectedAppointment,date2,addnoteTexFld.getText(),date3); }
        else
            JOptionPane.showMessageDialog(this,"Appointment date cannot be set in the past !");
    }

    private void reminderkButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void populateTable(Patient patient) {


        try {
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            Databaseconnection databaseconnection = new Databaseconnection();
            appointments = databaseconnection.getAppointment(patient.getEmailAddress());
            for (Appointment appointment : appointments) {
                LocalDateTime dateTime = appointment.getDate();
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
                String formattedDateTime = dateTime.format(formatter);
                model.addRow(new Object[]{appointment.getPatient().getLastName(), "specPap",
                        formattedDateTime, appointment.getPatient().getEmailAddress()});

            }
        } catch (Exception e) {
            System.out.println(e.getMessage());

/*
        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
        for(int i=0;i<appointments.length;i++){
            LocalDateTime dateTime = appointments[i].getDate();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
            String formattedDateTime = dateTime.format(formatter);
            model.addRow(new Object[]{appointments[i].getPatient().getLastName(),"test",
                    formattedDateTime,appointments[i].getPatient().getEmailAddress()});
        }*/

            //////////////////////-----------------------

        }
    }
    private void populateEditProfilePnl(Patient p){

        nameTxtfld.setText(p.getFirstName());
        familynameTxtfld.setText(p.getLastName());
            /*titleTxtFld.setText(p.getTitle());
            //specificationTxtFld.setText(p.
            streetTxtFld.setText(p.getStreet());
            houseNumberTxtFld.setText(p.getHouseNumber());
            postalCodeTxtFld.setText(p.getPostalCode());
            cityTxtFld.setText(p.getCity());
            emailTxtFld.setText(p.getEmailAddress());
            phoneTxtFld.setText(p.getPhoneNUmber());*/

    }



    // Variables declaration - do not modify
    private javax.swing.JTextField AddressTxtfld;
    private javax.swing.JLabel ChooseSecondAterantivedateLbl;
    private keeptoo.KGradientPanel SendAlternative;
    private javax.swing.JLabel addNotelbl;
    private javax.swing.JTextArea addnoteTexFld;
    private javax.swing.JLabel addressLbl;
    private javax.swing.JLabel chooseFirstAterantivedateLbl;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField emailTxtfld;
    private javax.swing.JLabel familyNameLbl;
    private javax.swing.JLabel familynameTxtfld;
    private javax.swing.JLabel framePicLbl;
    private javax.swing.JComboBox<String> reminderTimeComboBox;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private keeptoo.KButton lmenuBarLogoutBtn;
    private keeptoo.KButton logoutBtn1;
    private keeptoo.KGradientPanel mainPnl;
    private keeptoo.KButton menuBarEditprofileBtn;
    private keeptoo.KButton menuBarExitBtn;
    private keeptoo.KButton menuBarHomeBtn;
    private keeptoo.KButton menuBarNewAppBtn;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JLabel nameTxtfld;
    private keeptoo.KGradientPanel newAppPnl;
    private keeptoo.KGradientPanel p1;
    private javax.swing.JScrollPane patientAppointmentTable;
    private javax.swing.JLabel phoneLbl;
    private javax.swing.JTextField phoneTxtfld;
    private javax.swing.JLabel physicianListLbl;
    private keeptoo.KGradientPanel porfilePnl;
    private javax.swing.JLabel reminderLbl;
    private keeptoo.KButton reminderkButton;
    private javax.swing.JTextField searchDistanceTexfld;
    private keeptoo.KButton searchPhysicianBtn;
    private javax.swing.JLabel searchdistanceLbl;
    private keeptoo.KButton sendAlternativekButton6;
    private keeptoo.KButton sendAlternativekButton7;
    private keeptoo.KButton sendAppointmntRequestBtn;
    private com.toedter.calendar.JDateChooser sendFirstAlternativejDateChooser;
    private keeptoo.KButton sendRequeskButton;
    private com.toedter.calendar.JDateChooser sendSecondAlternativejDateChooser;
    private javax.swing.JLabel specificationLbl;
    private javax.swing.JTextField specificationTxtfld;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JTextField titleTxtfld;
    private javax.swing.JLabel userNameLbl;
    private javax.swing.JTextField usernameTxtfld;
    private javax.swing.JLabel welcomNameLbl;
    private javax.swing.JLabel welcomeLbl;
    private javax.swing.JLabel yourAppointmenstLbl;
    // End of variables declaration
}
