
        package test;

        import java.awt.Color;
        import java.sql.SQLException;
        import java.text.ParseException;
        import java.text.SimpleDateFormat;
        import java.time.Instant;
        import java.time.LocalDateTime;
        import java.time.format.DateTimeFormatter;
        import java.util.Date;
        import java.util.logging.Level;
        import java.util.logging.Logger;
        import javax.swing.BorderFactory;
        import javax.swing.JLabel;
        import javax.swing.JOptionPane;
        import javax.swing.table.DefaultTableModel;
        import javax.swing.table.TableModel;

/**
 *
 * @author Amar
 */
        public class PhysicianGUI extends javax.swing.JFrame {

        Appointment [] appointments;
        Appointment selectedAppointment;

        public PhysicianGUI(Physician physician) {


        setUndecorated(true);
        getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK));

        initComponents();

        titleTxtFld.setOpaque(false);
        titleTxtFld.setBorder(null);
        titleTxtFld.setEditable(false);

        specificationTxtFld.setOpaque(false);
        specificationTxtFld.setBorder(null);
        specificationTxtFld.setEditable(false);

        streetTxtFld.setOpaque(false);
        streetTxtFld.setBorder(null);
        streetTxtFld.setEditable(false);

        houseNumberTxtFld.setOpaque(false);
        houseNumberTxtFld.setBorder(null);
        houseNumberTxtFld.setEditable(false);


        postalCodeTxtFld.setOpaque(false);
        postalCodeTxtFld.setBorder(null);
        postalCodeTxtFld.setEditable(false);

        cityTxtFld.setOpaque(false);
        cityTxtFld.setBorder(null);
        cityTxtFld.setEditable(false);

        emailTxtFld.setOpaque(false);
        emailTxtFld.setBorder(null);
        emailTxtFld.setEditable(false);


        phoneTxtFld.setOpaque(false);
        phoneTxtFld.setBorder(null);
        phoneTxtFld.setEditable(false);

        jTable1.getTableHeader().setBackground(Color.WHITE);
        welcomeLbl.setText(physician.getLastName());

        populateTable(physician);
        populateEditProfilePnl(physician);




        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

        mainPnl = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        homeBtn = new keeptoo.KButton();
        editprofileBtn = new keeptoo.KButton();
        logoutBtn = new keeptoo.KButton();
        exitBtn = new keeptoo.KButton();
        jLabel7 = new javax.swing.JLabel();
        welcomeLbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        homePanel = new keeptoo.KGradientPanel();
        sendAlternativekButton = new keeptoo.KButton();
        confirmkButton = new keeptoo.KButton();
        homeTable = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        porfilePnl = new keeptoo.KGradientPanel();
        nameLbl = new javax.swing.JLabel();
        nameTxtFld = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        FamilyNameTexfld = new javax.swing.JLabel();
        TitleLbl = new javax.swing.JLabel();
        SpecificationLbl = new javax.swing.JLabel();
        streetLbl = new javax.swing.JLabel();
        emailLbl = new javax.swing.JLabel();
        phoneLbl = new javax.swing.JLabel();
        familyNameTexFld = new javax.swing.JLabel();
        titleTxtFld = new javax.swing.JTextField();
        specificationTxtFld = new javax.swing.JTextField();
        streetTxtFld = new javax.swing.JTextField();
        emailTxtFld = new javax.swing.JTextField();
        phoneTxtFld = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        SaveButton = new keeptoo.KButton();
        houseNumberTxtFld = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        houseNumberLbl = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        postalCodeTxtFld = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        cityTxtFld = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        cityLbl = new javax.swing.JLabel();
        sendAtrernativePnl = new keeptoo.KGradientPanel();
        sendAternativejDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        sendBtn = new keeptoo.KButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mainPnl.setkEndColor(new java.awt.Color(255, 255, 255));
        mainPnl.setkStartColor(new java.awt.Color(153, 204, 255));
        mainPnl.setLayout(new java.awt.BorderLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/physicians-banner.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 743, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
        );

        mainPnl.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        homeBtn.setBorder(null);
        homeBtn.setText("Home");
        homeBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        homeBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        homeBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        homeBtn.setkHoverStartColor(new java.awt.Color(102, 204, 255));
        homeBtn.setkPressedColor(new java.awt.Color(102, 204, 255));
        homeBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        homeBtn.setkStartColor(new java.awt.Color(153, 204, 255));
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
        homeBtnActionPerformed(evt);
        }
        });

        editprofileBtn.setBorder(null);
        editprofileBtn.setText("Edit Profile");
        editprofileBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        editprofileBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        editprofileBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        editprofileBtn.setkHoverStartColor(new java.awt.Color(102, 204, 255));
        editprofileBtn.setkPressedColor(new java.awt.Color(102, 204, 255));
        editprofileBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        editprofileBtn.setkStartColor(new java.awt.Color(153, 204, 255));
        editprofileBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
        editprofileBtnActionPerformed(evt);
        }
        });

        logoutBtn.setBorder(null);
        logoutBtn.setText("Logout");
        logoutBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        logoutBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        logoutBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        logoutBtn.setkHoverStartColor(new java.awt.Color(102, 204, 255));
        logoutBtn.setkPressedColor(new java.awt.Color(102, 204, 255));
        logoutBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        logoutBtn.setkStartColor(new java.awt.Color(153, 204, 255));
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
        logoutBtnActionPerformed(evt);
        }
        });

        exitBtn.setBorder(null);
        exitBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        exitBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        exitBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        exitBtn.setkHoverStartColor(new java.awt.Color(102, 204, 255));
        exitBtn.setkPressedColor(new java.awt.Color(102, 204, 255));
        exitBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        exitBtn.setkStartColor(new java.awt.Color(153, 204, 255));
        exitBtn.setLabel("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
        exitBtnActionPerformed(evt);
        }
        });

        jLabel7.setFont(new java.awt.Font("Baskerville Old Face", 2, 20)); // NOI18N
        jLabel7.setText("Welcome");

        welcomeLbl.setFont(new java.awt.Font("Baskerville Old Face", 2, 20)); // NOI18N
        welcomeLbl.setText("Name");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(homeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
        .addComponent(editprofileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel2Layout.createSequentialGroup()
        .addGap(30, 30, 30)
        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        .addGap(74, 74, 74)
        .addComponent(welcomeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
        .addComponent(logoutBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(exitBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
        .addGap(23, 23, 23)
        .addComponent(jLabel7)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(welcomeLbl)
        .addGap(32, 32, 32)
        .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(editprofileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(113, Short.MAX_VALUE))
        );

        mainPnl.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setLayout(new java.awt.CardLayout());

        homePanel.setkEndColor(new java.awt.Color(255, 255, 255));
        homePanel.setkStartColor(new java.awt.Color(153, 204, 255));

        sendAlternativekButton.setBorder(null);
        sendAlternativekButton.setText("Send Alternative");
        sendAlternativekButton.setkEndColor(new java.awt.Color(102, 204, 255));
        sendAlternativekButton.setkForeGround(new java.awt.Color(102, 102, 102));
        sendAlternativekButton.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        sendAlternativekButton.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        sendAlternativekButton.setkHoverStartColor(new java.awt.Color(102, 204, 255));
        sendAlternativekButton.setkPressedColor(new java.awt.Color(102, 204, 255));
        sendAlternativekButton.setkSelectedColor(new java.awt.Color(255, 255, 255));
        sendAlternativekButton.setkStartColor(new java.awt.Color(255, 255, 255));
        sendAlternativekButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
        sendAlternativekButtonActionPerformed(evt);
        }
        });

        confirmkButton.setBorder(null);
        confirmkButton.setText("Confirm");
        confirmkButton.setkEndColor(new java.awt.Color(102, 204, 255));
        confirmkButton.setkForeGround(new java.awt.Color(102, 102, 102));
        confirmkButton.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        confirmkButton.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        confirmkButton.setkHoverStartColor(new java.awt.Color(102, 204, 255));
        confirmkButton.setkPressedColor(new java.awt.Color(102, 204, 255));
        confirmkButton.setkSelectedColor(new java.awt.Color(255, 255, 255));
        confirmkButton.setkStartColor(new java.awt.Color(255, 255, 255));

        jTable1.setBackground(new java.awt.Color(153, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
        "Name", "Date adn time", "E-Mail", "Status"
        }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
        jTable1MouseClicked(evt);
        }
        });
        homeTable.setViewportView(jTable1);

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
        homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(homePanelLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(homePanelLayout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(confirmkButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addComponent(sendAlternativekButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addComponent(homeTable, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)))
        );
        homePanelLayout.setVerticalGroup(
        homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
        .addGap(31, 31, 31)
        .addComponent(homeTable, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
        .addComponent(sendAlternativekButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(31, 31, 31)
        .addComponent(confirmkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(29, 29, 29))
        );

        jPanel3.add(homePanel, "card2");

        porfilePnl.setkEndColor(new java.awt.Color(255, 255, 255));
        porfilePnl.setkStartColor(new java.awt.Color(153, 204, 255));

        nameLbl.setText("Name");

        nameTxtFld.setText("jLabel10");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/edit.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
        jLabel11MouseClicked(evt);
        }
        public void mouseEntered(java.awt.event.MouseEvent evt) {
        PhysicianGUI.this.mouseEntered(evt);
        }
        });

        FamilyNameTexfld.setText("Family name");

        TitleLbl.setText("Title");

        SpecificationLbl.setText("Specification");

        streetLbl.setText("Street");

        emailLbl.setText("E-Mail");

        phoneLbl.setText("Phone");

        familyNameTexFld.setText("jLabel18");

        titleTxtFld.setText("jTextField2");

        specificationTxtFld.setText("jTextField3");

        streetTxtFld.setText("jTextField4");

        emailTxtFld.setText("jTextField5");

        phoneTxtFld.setText("jTextField6");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/edit.png"))); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
        jLabel19MouseClicked(evt);
        }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/edit.png"))); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
        jLabel21MouseClicked(evt);
        }
        });

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/edit.png"))); // NOI18N
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
        jLabel22MouseClicked(evt);
        }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/edit.png"))); // NOI18N
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
        jLabel23MouseClicked(evt);
        }
        });

        SaveButton.setBorder(null);
        SaveButton.setText("Save");
        SaveButton.setkEndColor(new java.awt.Color(102, 204, 255));
        SaveButton.setkForeGround(new java.awt.Color(102, 102, 102));
        SaveButton.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        SaveButton.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        SaveButton.setkHoverStartColor(new java.awt.Color(102, 204, 255));
        SaveButton.setkPressedColor(new java.awt.Color(102, 204, 255));
        SaveButton.setkSelectedColor(new java.awt.Color(255, 255, 255));
        SaveButton.setkStartColor(new java.awt.Color(255, 255, 255));
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
        SaveButtonActionPerformed(evt);
        }
        });

        houseNumberTxtFld.setText("jTextField4");

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/edit.png"))); // NOI18N
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
        jLabel24MouseClicked(evt);
        }
        });

        houseNumberLbl.setText("House Number");

        jLabel10.setText("Postal Code");

        postalCodeTxtFld.setText("jTextField4");

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/edit.png"))); // NOI18N
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
        jLabel25MouseClicked(evt);
        }
        });

        cityTxtFld.setText("jTextField4");

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/edit.png"))); // NOI18N
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
        jLabel26MouseClicked(evt);
        }
        });

        cityLbl.setText("City");

        javax.swing.GroupLayout porfilePnlLayout = new javax.swing.GroupLayout(porfilePnl);
        porfilePnl.setLayout(porfilePnlLayout);
        porfilePnlLayout.setHorizontalGroup(
        porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(porfilePnlLayout.createSequentialGroup()
        .addGap(57, 57, 57)
        .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
        .addGroup(porfilePnlLayout.createSequentialGroup()
        .addComponent(phoneLbl)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(phoneTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel11))
        .addComponent(SaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(porfilePnlLayout.createSequentialGroup()
        .addGap(129, 300, Short.MAX_VALUE)
        .addComponent(jLabel23))
        .addGroup(porfilePnlLayout.createSequentialGroup()
        .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(porfilePnlLayout.createSequentialGroup()
        .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
        .addGroup(porfilePnlLayout.createSequentialGroup()
        .addComponent(jLabel10)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(postalCodeTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, porfilePnlLayout.createSequentialGroup()
        .addComponent(SpecificationLbl)
        .addGap(69, 69, 69)
        .addComponent(specificationTxtFld))
        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, porfilePnlLayout.createSequentialGroup()
        .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(streetLbl)
        .addComponent(houseNumberLbl))
        .addGap(59, 59, 59)
        .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(houseNumberTxtFld)
        .addComponent(streetTxtFld)))
        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, porfilePnlLayout.createSequentialGroup()
        .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(FamilyNameTexfld)
        .addComponent(nameLbl)
        .addComponent(TitleLbl))
        .addGap(70, 70, 70)
        .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(titleTxtFld)
        .addGroup(porfilePnlLayout.createSequentialGroup()
        .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(nameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addComponent(familyNameTexFld, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(0, 0, Short.MAX_VALUE)))))
        .addGap(5, 5, 5))
        .addGroup(porfilePnlLayout.createSequentialGroup()
        .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(cityLbl)
        .addComponent(emailLbl))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
        .addComponent(cityTxtFld, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
        .addComponent(emailTxtFld))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
        .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
        .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
        .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
        .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
        .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
        .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING))))
        .addGap(167, 167, 167))
        );
        porfilePnlLayout.setVerticalGroup(
        porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(porfilePnlLayout.createSequentialGroup()
        .addGap(33, 33, 33)
        .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
        .addComponent(nameLbl)
        .addComponent(nameTxtFld))
        .addGap(18, 18, 18)
        .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
        .addComponent(FamilyNameTexfld)
        .addComponent(familyNameTexFld))
        .addGap(18, 18, 18)
        .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
        .addComponent(TitleLbl)
        .addComponent(titleTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
        .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
        .addComponent(SpecificationLbl)
        .addComponent(specificationTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
        .addComponent(streetLbl)
        .addComponent(streetTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(houseNumberTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addComponent(houseNumberLbl)
        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addComponent(postalCodeTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addComponent(jLabel10))
        .addGap(18, 18, 18)
        .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
        .addComponent(cityTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addComponent(cityLbl)))
        .addGap(18, 18, 18)
        .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
        .addComponent(emailLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addComponent(emailTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        .addGap(18, 18, 18)
        .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
        .addComponent(phoneLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addComponent(phoneTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
        .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(37, 37, 37))
        );

        jPanel3.add(porfilePnl, "card4");

        sendAtrernativePnl.setkEndColor(new java.awt.Color(255, 255, 255));
        sendAtrernativePnl.setkStartColor(new java.awt.Color(153, 204, 255));

        jLabel1.setText("Alternative date");

        jLabel2.setText("Add note");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        sendBtn.setBorder(null);
        sendBtn.setText("Send");
        sendBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        sendBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        sendBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        sendBtn.setkHoverStartColor(new java.awt.Color(102, 204, 255));
        sendBtn.setkPressedColor(new java.awt.Color(102, 204, 255));
        sendBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        sendBtn.setkStartColor(new java.awt.Color(153, 204, 255));
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
        sendBtnActionPerformed(evt);
        }
        });

        jLabel3.setText("Patient name");

        jLabel4.setText("Name");

        jLabel5.setText("E-Mail");

        jLabel6.setText("example@live.com");

        javax.swing.GroupLayout sendAtrernativePnlLayout = new javax.swing.GroupLayout(sendAtrernativePnl);
        sendAtrernativePnl.setLayout(sendAtrernativePnlLayout);
        sendAtrernativePnlLayout.setHorizontalGroup(
        sendAtrernativePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sendAtrernativePnlLayout.createSequentialGroup()
        .addContainerGap(179, Short.MAX_VALUE)
        .addGroup(sendAtrernativePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
        .addComponent(sendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGroup(sendAtrernativePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
        .addComponent(jScrollPane2)
        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, sendAtrernativePnlLayout.createSequentialGroup()
        .addComponent(jLabel1)
        .addGap(58, 58, 58)
        .addComponent(sendAternativejDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, sendAtrernativePnlLayout.createSequentialGroup()
        .addGroup(sendAtrernativePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jLabel3)
        .addComponent(jLabel5))
        .addGap(29, 29, 29)
        .addGroup(sendAtrernativePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        .addGap(100, 100, 100))
        );
        sendAtrernativePnlLayout.setVerticalGroup(
        sendAtrernativePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(sendAtrernativePnlLayout.createSequentialGroup()
        .addGap(97, 97, 97)
        .addGroup(sendAtrernativePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(sendAternativejDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addComponent(jLabel1))
        .addGap(20, 20, 20)
        .addGroup(sendAtrernativePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
        .addComponent(jLabel3)
        .addComponent(jLabel4))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(sendAtrernativePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
        .addComponent(jLabel5)
        .addComponent(jLabel6))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
        .addComponent(sendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(34, 34, 34))
        );

        jPanel3.add(sendAtrernativePnl, "card2");

        mainPnl.add(jPanel3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
        .addGap(0, 0, 0)
        .addComponent(mainPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(mainPnl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
        }// </editor-fold>

        private void populateTable(Physician physician){


        try{
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        Databaseconnection databaseconnection = new Databaseconnection();
        appointments=databaseconnection.getAppointment(physician.getEmailAddress());
        for (Appointment appointment : appointments) {
        LocalDateTime dateTime = appointment.getDate();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
        String formattedDateTime = dateTime.format(formatter);
        model.addRow(new Object[]{appointment.getPatient().getLastName(),
        formattedDateTime, appointment.getPatient().getEmailAddress()});

        }
        }catch (Exception e) {
        System.out.println(e.getMessage());


        }







        }

        private void populateEditProfilePnl(Physician p){

        nameTxtFld.setText(p.getFirstName());
        familyNameTexFld.setText(p.getLastName());
        titleTxtFld.setText(p.getTitle());
        //specificationTxtFld.setText(p.
        streetTxtFld.setText(p.getStreet());
        houseNumberTxtFld.setText(p.getHouseNumber());
        postalCodeTxtFld.setText(p.getPostalCode());
        cityTxtFld.setText(p.getCity());
        emailTxtFld.setText(p.getEmailAddress());
        phoneTxtFld.setText(p.getPhoneNUmber());

        }

        private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {

        sendAtrernativePnl.setVisible(false);
        porfilePnl.setVisible(false);
        homePanel.setVisible(true);


        }

        private void editprofileBtnActionPerformed(java.awt.event.ActionEvent evt) {

        sendAtrernativePnl.setVisible(false);
        homePanel.setVisible(false);
        porfilePnl.setVisible(true);

        // TODO add your handling code here:
        }

        private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {

        dispose();

        }

        private void mouseEntered(java.awt.event.MouseEvent evt) {
        if(evt.getSource()==jLabel11){
        jLabel11.setBackground(new Color(153,204,255));
        }
        }

        private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {
        phoneTxtFld.setEditable(true);
        }

        private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {
        titleTxtFld.setEditable(true);
        }

        private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {
        streetTxtFld.setEditable(true);
        }

        private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {

        specificationTxtFld.setEditable(true);
        }

        private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {
        emailTxtFld.setEditable(true);
        }

        private void sendAlternativekButtonActionPerformed(java.awt.event.ActionEvent evt) {
        porfilePnl.setVisible(false);
        homePanel.setVisible(false);
        sendAtrernativePnl.setVisible(true);

        }



        private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {

        LocalDateTime now = LocalDateTime.now();
        Date date1 =(java.sql.Timestamp.valueOf(now));
        Date date2 =(sendAternativejDateChooser.getDate());



        if (date1.before(date2)) {
        new Mail().sendAlternativeMail(selectedAppointment,date2,jTextArea1.getText()); }
        else
        JOptionPane.showMessageDialog(this,"Appointment date cannot be set in the past !");



        }

        private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {
        int index=jTable1.getSelectedRow();
        TableModel model=jTable1.getModel();
        jLabel6.setText(model.getValueAt(index,2).toString());
        jLabel4.setText(model.getValueAt(index,0).toString());
        String sDate1=model.getValueAt(index,1).toString();


        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
        LocalDateTime dateTime = LocalDateTime.parse(sDate1, formatter);


        for (Appointment appointment : appointments) {
        if (appointment.getPatient().getLastName().equals(jLabel4.getText()) && appointment.getDate().equals(dateTime)) {
        selectedAppointment = appointment;
        }
        }
        }

        private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {
        setVisible(false);
        new LoginGUI().setVisible(true);

        }

        private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {
        titleTxtFld.setEditable(false);
        specificationTxtFld.setEditable(false);
        streetTxtFld.setEditable(false);
        emailTxtFld.setEditable(false);
        phoneTxtFld.setEditable(false);
        postalCodeTxtFld.setEditable(false);
        cityTxtFld.setEditable(false);
        houseNumberTxtFld.setEditable(false);
        //update database function
        }

        private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {
        postalCodeTxtFld.setEditable(true);
        }

        private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {
        cityTxtFld.setEditable(true);
        }

        private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {
        houseNumberTxtFld.setEditable(true);
        }




        public static void main(String[] args) {
        Databaseconnection databaseconnection = new Databaseconnection();
        /* Set the Nimbus look and feel
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhysicianGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhysicianGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhysicianGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhysicianGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
         Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
        try {
        new PhysicianGUI(databaseconnection.getPhysician("Doctor")).setVisible(true);
        } catch (SQLException | ClassNotFoundException throwables) {
        throwables.printStackTrace();
        }
        }
        });
        }

        // Variables declaration - do not modify
        private javax.swing.JLabel FamilyNameTexfld;
        private keeptoo.KButton SaveButton;
        private javax.swing.JLabel SpecificationLbl;
        private javax.swing.JLabel TitleLbl;
        private javax.swing.JLabel cityLbl;
        private javax.swing.JTextField cityTxtFld;
        private keeptoo.KButton confirmkButton;
        private keeptoo.KButton editprofileBtn;
        private javax.swing.JLabel emailLbl;
        private javax.swing.JTextField emailTxtFld;
        private keeptoo.KButton exitBtn;
        private javax.swing.JLabel familyNameTexFld;
        private keeptoo.KButton homeBtn;
        private keeptoo.KGradientPanel homePanel;
        private javax.swing.JScrollPane homeTable;
        private javax.swing.JLabel houseNumberLbl;
        private javax.swing.JTextField houseNumberTxtFld;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel19;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel21;
        private javax.swing.JLabel jLabel22;
        private javax.swing.JLabel jLabel23;
        private javax.swing.JLabel jLabel24;
        private javax.swing.JLabel jLabel25;
        private javax.swing.JLabel jLabel26;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTable jTable1;
        private javax.swing.JTextArea jTextArea1;
        private keeptoo.KButton logoutBtn;
        private keeptoo.KGradientPanel mainPnl;
        private javax.swing.JLabel nameLbl;
        private javax.swing.JLabel nameTxtFld;
        private javax.swing.JLabel phoneLbl;
        private javax.swing.JTextField phoneTxtFld;
        private keeptoo.KGradientPanel porfilePnl;
        private javax.swing.JTextField postalCodeTxtFld;
        private keeptoo.KButton sendAlternativekButton;
        private com.toedter.calendar.JDateChooser sendAternativejDateChooser;
        private keeptoo.KGradientPanel sendAtrernativePnl;
        private keeptoo.KButton sendBtn;
        private javax.swing.JTextField specificationTxtFld;
        private javax.swing.JLabel streetLbl;
        private javax.swing.JTextField streetTxtFld;
        private javax.swing.JTextField titleTxtFld;
        private javax.swing.JLabel welcomeLbl;
        // End of variables declaration
        }

